// Agora deck. Free. Drop-in compatible with the bundled deck format.
var deck = {
  "id": "pro:french-starter",
  "name": "French Starter 40",
  "lang": "fr",
  "cards": [
    { "id": "fr-0001", "front": "bonjour", "back": "hello / good morning", "example": "Bonjour, comment ça va ?" },
    { "id": "fr-0002", "front": "au revoir", "back": "goodbye", "example": "Au revoir, à demain." },
    { "id": "fr-0003", "front": "merci", "back": "thank you", "example": "Merci beaucoup pour ton aide." },
    { "id": "fr-0004", "front": "s'il vous plaît", "back": "please", "example": "Une table pour deux, s'il vous plaît." },
    { "id": "fr-0005", "front": "oui", "back": "yes", "example": "Oui, je veux un café." },
    { "id": "fr-0006", "front": "non", "back": "no", "example": "Non, merci, ça va." },
    { "id": "fr-0007", "front": "bonsoir", "back": "good evening", "example": "Bonsoir, vous allez bien ?" },
    { "id": "fr-0008", "front": "bonne nuit", "back": "good night", "example": "Bonne nuit, dors bien." },
    { "id": "fr-0009", "front": "l'eau", "back": "the water", "example": "Je voudrais un verre d'eau, s'il vous plaît." },
    { "id": "fr-0010", "front": "le café", "back": "the coffee", "example": "J'aime le café le matin." },
    { "id": "fr-0011", "front": "la maison", "back": "the house", "example": "Ma maison est près du parc." },
    { "id": "fr-0012", "front": "le chien", "back": "the dog", "example": "Le chien court dans le parc." },
    { "id": "fr-0013", "front": "le chat", "back": "the cat", "example": "Le chat dort sur le canapé." },
    { "id": "fr-0014", "front": "la nourriture", "back": "the food", "example": "La nourriture est très bonne." },
    { "id": "fr-0015", "front": "l'ami", "back": "the friend (male)", "example": "Mon ami habite à Paris." },
    { "id": "fr-0016", "front": "la famille", "back": "the family", "example": "Ma famille est très grande." },
    { "id": "fr-0017", "front": "le jour", "back": "the day", "example": "Aujourd'hui est un bon jour." },
    { "id": "fr-0018", "front": "la nuit", "back": "the night", "example": "Je travaille pendant la nuit." },
    { "id": "fr-0019", "front": "le temps", "back": "the time / the weather", "example": "Je n'ai pas le temps maintenant." },
    { "id": "fr-0020", "front": "la rue", "back": "the street", "example": "Le magasin est dans cette rue." },
    { "id": "fr-0021", "front": "être", "back": "to be", "example": "Je veux être médecin." },
    { "id": "fr-0022", "front": "avoir", "back": "to have", "example": "J'ai deux frères." },
    { "id": "fr-0023", "front": "faire", "back": "to do / to make", "example": "Qu'est-ce que tu veux faire aujourd'hui ?" },
    { "id": "fr-0024", "front": "aller", "back": "to go", "example": "Je vais à l'école chaque jour." },
    { "id": "fr-0025", "front": "manger", "back": "to eat", "example": "J'aime manger des fruits." },
    { "id": "fr-0026", "front": "boire", "back": "to drink", "example": "Je veux boire un peu d'eau." },
    { "id": "fr-0027", "front": "parler", "back": "to speak / to talk", "example": "Je veux bien parler français." },
    { "id": "fr-0028", "front": "vouloir", "back": "to want", "example": "Je veux apprendre plus de mots." },
    { "id": "fr-0029", "front": "pouvoir", "back": "to be able to / can", "example": "Peux-tu m'aider, s'il te plaît ?" },
    { "id": "fr-0030", "front": "savoir", "back": "to know (a fact)", "example": "Je ne sais pas où il est." },
    { "id": "fr-0031", "front": "grand", "back": "big / tall", "example": "Cette ville est très grande." },
    { "id": "fr-0032", "front": "petit", "back": "small", "example": "J'ai un petit chien." },
    { "id": "fr-0033", "front": "bon", "back": "good", "example": "Ce livre est très bon." },
    { "id": "fr-0034", "front": "mauvais", "back": "bad", "example": "Il fait mauvais temps aujourd'hui." },
    { "id": "fr-0035", "front": "un", "back": "one / a", "example": "Je veux seulement un, merci." },
    { "id": "fr-0036", "front": "deux", "back": "two", "example": "J'ai deux chats à la maison." },
    { "id": "fr-0037", "front": "trois", "back": "three", "example": "Il est trois heures de l'après-midi." },
    { "id": "fr-0038", "front": "aujourd'hui", "back": "today", "example": "Aujourd'hui je vais au marché." },
    { "id": "fr-0039", "front": "demain", "back": "tomorrow", "example": "Demain, mon nouveau travail commence." },
    { "id": "fr-0040", "front": "où ?", "back": "where?", "example": "Où sont les toilettes ?" }
  ]
};
if (typeof module !== "undefined" && module.exports) module.exports = deck;
