// Agora deck. Free. Drop-in compatible with the bundled deck format.
var deck = {
  "id": "pro:german-starter",
  "name": "German Starter 40",
  "lang": "de",
  "cards": [
    { "id": "de-0001", "front": "hallo", "back": "hello", "example": "Hallo, wie geht es dir?" },
    { "id": "de-0002", "front": "auf Wiedersehen", "back": "goodbye", "example": "Auf Wiedersehen, bis morgen." },
    { "id": "de-0003", "front": "danke", "back": "thank you", "example": "Vielen Dank für deine Hilfe." },
    { "id": "de-0004", "front": "bitte", "back": "please / you're welcome", "example": "Einen Tisch für zwei, bitte." },
    { "id": "de-0005", "front": "ja", "back": "yes", "example": "Ja, ich möchte einen Kaffee." },
    { "id": "de-0006", "front": "nein", "back": "no", "example": "Nein, danke, mir geht's gut." },
    { "id": "de-0007", "front": "guten Morgen", "back": "good morning", "example": "Guten Morgen, wie geht's?" },
    { "id": "de-0008", "front": "gute Nacht", "back": "good night", "example": "Gute Nacht, schlaf gut." },
    { "id": "de-0009", "front": "das Wasser", "back": "the water", "example": "Ich möchte ein Glas Wasser, bitte." },
    { "id": "de-0010", "front": "der Kaffee", "back": "the coffee", "example": "Ich mag Kaffee am Morgen." },
    { "id": "de-0011", "front": "das Haus", "back": "the house", "example": "Mein Haus ist in der Nähe des Parks." },
    { "id": "de-0012", "front": "der Hund", "back": "the dog", "example": "Der Hund läuft im Park." },
    { "id": "de-0013", "front": "die Katze", "back": "the cat", "example": "Die Katze schläft auf dem Sofa." },
    { "id": "de-0014", "front": "das Essen", "back": "the food / meal", "example": "Das Essen ist sehr lecker." },
    { "id": "de-0015", "front": "der Freund", "back": "the friend (male)", "example": "Mein Freund wohnt in Berlin." },
    { "id": "de-0016", "front": "die Familie", "back": "the family", "example": "Meine Familie ist sehr groß." },
    { "id": "de-0017", "front": "der Tag", "back": "the day", "example": "Heute ist ein guter Tag." },
    { "id": "de-0018", "front": "die Nacht", "back": "the night", "example": "Ich arbeite während der Nacht." },
    { "id": "de-0019", "front": "die Zeit", "back": "the time", "example": "Ich habe jetzt keine Zeit." },
    { "id": "de-0020", "front": "die Straße", "back": "the street", "example": "Das Geschäft ist in dieser Straße." },
    { "id": "de-0021", "front": "sein", "back": "to be", "example": "Ich möchte Arzt sein." },
    { "id": "de-0022", "front": "haben", "back": "to have", "example": "Ich habe zwei Brüder." },
    { "id": "de-0023", "front": "machen", "back": "to do / to make", "example": "Was möchtest du heute machen?" },
    { "id": "de-0024", "front": "gehen", "back": "to go", "example": "Ich gehe jeden Tag zur Schule." },
    { "id": "de-0025", "front": "essen", "back": "to eat", "example": "Ich esse gern Obst." },
    { "id": "de-0026", "front": "trinken", "back": "to drink", "example": "Ich möchte etwas Wasser trinken." },
    { "id": "de-0027", "front": "sprechen", "back": "to speak", "example": "Ich möchte gut Deutsch sprechen." },
    { "id": "de-0028", "front": "wollen", "back": "to want", "example": "Ich will mehr Wörter lernen." },
    { "id": "de-0029", "front": "können", "back": "to be able to / can", "example": "Kannst du mir bitte helfen?" },
    { "id": "de-0030", "front": "wissen", "back": "to know (a fact)", "example": "Ich weiß nicht, wo er ist." },
    { "id": "de-0031", "front": "groß", "back": "big / tall", "example": "Diese Stadt ist sehr groß." },
    { "id": "de-0032", "front": "klein", "back": "small", "example": "Ich habe einen kleinen Hund." },
    { "id": "de-0033", "front": "gut", "back": "good", "example": "Dieses Buch ist sehr gut." },
    { "id": "de-0034", "front": "schlecht", "back": "bad", "example": "Heute ist schlechtes Wetter." },
    { "id": "de-0035", "front": "eins", "back": "one", "example": "Ich möchte nur eins, danke." },
    { "id": "de-0036", "front": "zwei", "back": "two", "example": "Ich habe zwei Katzen zu Hause." },
    { "id": "de-0037", "front": "drei", "back": "three", "example": "Es ist drei Uhr nachmittags." },
    { "id": "de-0038", "front": "heute", "back": "today", "example": "Heute gehe ich zum Markt." },
    { "id": "de-0039", "front": "morgen", "back": "tomorrow / morning", "example": "Morgen beginnt meine neue Arbeit." },
    { "id": "de-0040", "front": "wo?", "back": "where?", "example": "Wo ist die Toilette?" }
  ]
};
if (typeof module !== "undefined" && module.exports) module.exports = deck;
