// Agora deck. Free.
var deck = {
  "id": "bundled:french",
  "name": "French 500",
  "lang": "fr",
  "cards": [
    { "id": "fr-0001", "front": "bonjour", "back": "hello / good morning", "example": "Bonjour, comment ça va ?", "exampleEn": "Hello, how are you?" },
    { "id": "fr-0002", "front": "bonsoir", "back": "good evening", "example": "Bonsoir, tu as passé une bonne journée ?", "exampleEn": "Good evening, did you have a good day?" },
    { "id": "fr-0003", "front": "salut", "back": "hi / bye (informal)", "example": "Salut, on se voit demain !", "exampleEn": "Hey, see you tomorrow!" },
    { "id": "fr-0004", "front": "au revoir", "back": "goodbye", "example": "Au revoir, à bientôt !", "exampleEn": "Goodbye, see you soon!" },
    { "id": "fr-0005", "front": "bonne nuit", "back": "good night", "example": "Bonne nuit, dors bien.", "exampleEn": "Good night, sleep well." },
    { "id": "fr-0006", "front": "merci", "back": "thank you", "example": "Merci beaucoup pour ton aide.", "exampleEn": "Thank you very much for your help." },
    { "id": "fr-0007", "front": "de rien", "back": "you're welcome", "example": "Merci ! De rien, c'est normal.", "exampleEn": "Thank you! You're welcome, it's nothing." },
    { "id": "fr-0008", "front": "s'il vous plaît", "back": "please (formal)", "example": "Un café, s'il vous plaît.", "exampleEn": "A coffee, please." },
    { "id": "fr-0009", "front": "s'il te plaît", "back": "please (informal)", "example": "Passe-moi le sel, s'il te plaît.", "exampleEn": "Pass me the salt, please." },
    { "id": "fr-0010", "front": "pardon", "back": "sorry / excuse me", "example": "Pardon, je ne vous ai pas entendu.", "exampleEn": "Sorry, I didn't hear you." },
    { "id": "fr-0011", "front": "excusez-moi", "back": "excuse me (formal)", "example": "Excusez-moi, où sont les toilettes ?", "exampleEn": "Excuse me, where are the restrooms?" },
    { "id": "fr-0012", "front": "oui", "back": "yes", "example": "Oui, je suis d'accord.", "exampleEn": "Yes, I agree." },
    { "id": "fr-0013", "front": "non", "back": "no", "example": "Non, merci, ça va.", "exampleEn": "No, thank you, I'm fine." },
    { "id": "fr-0014", "front": "peut-être", "back": "maybe", "example": "Peut-être que je viendrai ce soir.", "exampleEn": "Maybe I'll come tonight." },
    { "id": "fr-0015", "front": "d'accord", "back": "okay / agreed", "example": "D'accord, on fait comme ça.", "exampleEn": "Alright, let's do it that way." },
    { "id": "fr-0016", "front": "bienvenue", "back": "welcome", "example": "Bienvenue chez nous !", "exampleEn": "Welcome to our home!" },
    { "id": "fr-0017", "front": "enchanté", "back": "nice to meet you", "example": "Enchanté, je m'appelle Marc.", "exampleEn": "Nice to meet you, my name is Marc." },
    { "id": "fr-0018", "front": "comment ça va ?", "back": "how are you?", "example": "Salut, comment ça va aujourd'hui ?", "exampleEn": "Hi, how are you today?" },
    { "id": "fr-0019", "front": "ça va", "back": "I'm fine / it's okay", "example": "Ça va bien, et toi ?", "exampleEn": "I'm doing well, and you?" },
    { "id": "fr-0020", "front": "à bientôt", "back": "see you soon", "example": "À bientôt, prends soin de toi.", "exampleEn": "See you soon, take care of yourself." },
    { "id": "fr-0021", "front": "à demain", "back": "see you tomorrow", "example": "À demain au bureau !", "exampleEn": "See you tomorrow at the office!" },
    { "id": "fr-0022", "front": "à tout à l'heure", "back": "see you later (today)", "example": "Je sors un peu, à tout à l'heure.", "exampleEn": "I'm stepping out for a bit, see you later." },
    { "id": "fr-0023", "front": "zéro", "back": "zero", "example": "Il fait zéro degré ce matin.", "exampleEn": "It's zero degrees this morning." },
    { "id": "fr-0024", "front": "un", "back": "one", "example": "J'ai un frère et deux sœurs.", "exampleEn": "I have one brother and two sisters." },
    { "id": "fr-0025", "front": "deux", "back": "two", "example": "Je voudrais deux croissants.", "exampleEn": "I'd like two croissants." },
    { "id": "fr-0026", "front": "trois", "back": "three", "example": "Le film commence dans trois minutes.", "exampleEn": "The movie starts in three minutes." },
    { "id": "fr-0027", "front": "quatre", "back": "four", "example": "Nous sommes quatre à table.", "exampleEn": "There are four of us at the table." },
    { "id": "fr-0028", "front": "cinq", "back": "five", "example": "Le train part à cinq heures.", "exampleEn": "The train leaves at five o'clock." },
    { "id": "fr-0029", "front": "six", "back": "six", "example": "Il a six ans aujourd'hui.", "exampleEn": "He is six years old today." },
    { "id": "fr-0030", "front": "sept", "back": "seven", "example": "Je travaille sept jours par semaine.", "exampleEn": "I work seven days a week." },
    { "id": "fr-0031", "front": "huit", "back": "eight", "example": "Le magasin ouvre à huit heures.", "exampleEn": "The store opens at eight o'clock." },
    { "id": "fr-0032", "front": "neuf", "back": "nine", "example": "Il est presque neuf heures.", "exampleEn": "It's almost nine o'clock." },
    { "id": "fr-0033", "front": "dix", "back": "ten", "example": "J'ai dix euros dans ma poche.", "exampleEn": "I have ten euros in my pocket." },
    { "id": "fr-0034", "front": "onze", "back": "eleven", "example": "Le cours finit à onze heures.", "exampleEn": "The class ends at eleven o'clock." },
    { "id": "fr-0035", "front": "douze", "back": "twelve", "example": "Il y a douze mois dans une année.", "exampleEn": "There are twelve months in a year." },
    { "id": "fr-0036", "front": "treize", "back": "thirteen", "example": "Ma fille a treize ans.", "exampleEn": "My daughter is thirteen years old." },
    { "id": "fr-0037", "front": "quatorze", "back": "fourteen", "example": "Le bus passe à quatorze heures.", "exampleEn": "The bus comes at two in the afternoon." },
    { "id": "fr-0038", "front": "quinze", "back": "fifteen", "example": "Attends quinze minutes, s'il te plaît.", "exampleEn": "Wait fifteen minutes, please." },
    { "id": "fr-0039", "front": "seize", "back": "sixteen", "example": "Il a seize ans cette année.", "exampleEn": "He is sixteen years old this year." },
    { "id": "fr-0040", "front": "dix-sept", "back": "seventeen", "example": "Le livre coûte dix-sept euros.", "exampleEn": "The book costs seventeen euros." },
    { "id": "fr-0041", "front": "dix-huit", "back": "eighteen", "example": "On est majeur à dix-huit ans.", "exampleEn": "You become an adult at eighteen." },
    { "id": "fr-0042", "front": "dix-neuf", "back": "nineteen", "example": "Elle habite au dix-neuf de cette rue.", "exampleEn": "She lives at number nineteen on this street." },
    { "id": "fr-0043", "front": "vingt", "back": "twenty", "example": "Il me reste vingt minutes.", "exampleEn": "I have twenty minutes left." },
    { "id": "fr-0044", "front": "trente", "back": "thirty", "example": "Ce mois a trente jours.", "exampleEn": "This month has thirty days." },
    { "id": "fr-0045", "front": "quarante", "back": "forty", "example": "Mon père a quarante ans.", "exampleEn": "My father is forty years old." },
    { "id": "fr-0046", "front": "cinquante", "back": "fifty", "example": "Le ticket coûte cinquante euros.", "exampleEn": "The ticket costs fifty euros." },
    { "id": "fr-0047", "front": "soixante", "back": "sixty", "example": "Une heure fait soixante minutes.", "exampleEn": "One hour has sixty minutes." },
    { "id": "fr-0048", "front": "soixante-dix", "back": "seventy", "example": "Ma grand-mère a soixante-dix ans.", "exampleEn": "My grandmother is seventy years old." },
    { "id": "fr-0049", "front": "quatre-vingts", "back": "eighty", "example": "Il y a quatre-vingts élèves ici.", "exampleEn": "There are eighty students here." },
    { "id": "fr-0050", "front": "quatre-vingt-dix", "back": "ninety", "example": "Le trajet dure quatre-vingt-dix minutes.", "exampleEn": "The trip takes ninety minutes." },
    { "id": "fr-0051", "front": "cent", "back": "one hundred", "example": "Ce manteau coûte cent euros.", "exampleEn": "This coat costs one hundred euros." },
    { "id": "fr-0052", "front": "mille", "back": "one thousand", "example": "La ville compte mille habitants.", "exampleEn": "The town has one thousand inhabitants." },
    { "id": "fr-0053", "front": "lundi", "back": "Monday", "example": "Je commence le travail lundi.", "exampleEn": "I start work on Monday." },
    { "id": "fr-0054", "front": "mardi", "back": "Tuesday", "example": "Mardi, j'ai un rendez-vous.", "exampleEn": "On Tuesday, I have an appointment." },
    { "id": "fr-0055", "front": "mercredi", "back": "Wednesday", "example": "Les enfants ne vont pas à l'école le mercredi.", "exampleEn": "Children don't go to school on Wednesdays." },
    { "id": "fr-0056", "front": "jeudi", "back": "Thursday", "example": "On dîne ensemble jeudi soir.", "exampleEn": "We're having dinner together Thursday evening." },
    { "id": "fr-0057", "front": "vendredi", "back": "Friday", "example": "Vendredi, c'est presque le week-end.", "exampleEn": "Friday, it's almost the weekend." },
    { "id": "fr-0058", "front": "samedi", "back": "Saturday", "example": "Samedi, je fais les courses.", "exampleEn": "On Saturday, I do the grocery shopping." },
    { "id": "fr-0059", "front": "dimanche", "back": "Sunday", "example": "Le dimanche, je me repose.", "exampleEn": "On Sundays, I rest." },
    { "id": "fr-0060", "front": "janvier", "back": "January", "example": "Mon anniversaire est en janvier.", "exampleEn": "My birthday is in January." },
    { "id": "fr-0061", "front": "février", "back": "February", "example": "Il neige souvent en février.", "exampleEn": "It often snows in February." },
    { "id": "fr-0062", "front": "mars", "back": "March", "example": "Le printemps commence en mars.", "exampleEn": "Spring begins in March." },
    { "id": "fr-0063", "front": "avril", "back": "April", "example": "En avril, il pleut beaucoup.", "exampleEn": "In April, it rains a lot." },
    { "id": "fr-0064", "front": "mai", "back": "May", "example": "Nous partons en vacances en mai.", "exampleEn": "We're going on vacation in May." },
    { "id": "fr-0065", "front": "juin", "back": "June", "example": "Les examens sont en juin.", "exampleEn": "The exams are in June." },
    { "id": "fr-0066", "front": "juillet", "back": "July", "example": "Il fait très chaud en juillet.", "exampleEn": "It's very hot in July." },
    { "id": "fr-0067", "front": "août", "back": "August", "example": "Beaucoup de gens sont en congé en août.", "exampleEn": "A lot of people are on leave in August." },
    { "id": "fr-0068", "front": "septembre", "back": "September", "example": "La rentrée a lieu en septembre.", "exampleEn": "The new school year starts in September." },
    { "id": "fr-0069", "front": "octobre", "back": "October", "example": "Les feuilles tombent en octobre.", "exampleEn": "The leaves fall in October." },
    { "id": "fr-0070", "front": "novembre", "back": "November", "example": "Il fait froid en novembre.", "exampleEn": "It's cold in November." },
    { "id": "fr-0071", "front": "décembre", "back": "December", "example": "Noël est en décembre.", "exampleEn": "Christmas is in December." },
    { "id": "fr-0072", "front": "aujourd'hui", "back": "today", "example": "Aujourd'hui, il fait beau.", "exampleEn": "Today, the weather is nice." },
    { "id": "fr-0073", "front": "demain", "back": "tomorrow", "example": "Demain, je vais au travail.", "exampleEn": "Tomorrow, I'm going to work." },
    { "id": "fr-0074", "front": "hier", "back": "yesterday", "example": "Hier, j'ai vu un ami.", "exampleEn": "Yesterday, I saw a friend." },
    { "id": "fr-0075", "front": "maintenant", "back": "now", "example": "Je dois partir maintenant.", "exampleEn": "I have to leave now." },
    { "id": "fr-0076", "front": "le matin", "back": "the morning", "example": "Le matin, je bois un café.", "exampleEn": "In the morning, I drink a coffee." },
    { "id": "fr-0077", "front": "l'après-midi", "back": "the afternoon", "example": "L'après-midi, je fais une sieste.", "exampleEn": "In the afternoon, I take a nap." },
    { "id": "fr-0078", "front": "le soir", "back": "the evening", "example": "Le soir, je lis un livre.", "exampleEn": "In the evening, I read a book." },
    { "id": "fr-0079", "front": "la nuit", "back": "the night", "example": "La nuit, tout est calme.", "exampleEn": "At night, everything is quiet." },
    { "id": "fr-0080", "front": "l'heure", "back": "the hour / time", "example": "Quelle heure est-il ?", "exampleEn": "What time is it?" },
    { "id": "fr-0081", "front": "la minute", "back": "the minute", "example": "Attends une minute, j'arrive.", "exampleEn": "Wait a minute, I'm coming." },
    { "id": "fr-0082", "front": "la semaine", "back": "the week", "example": "Cette semaine est très chargée.", "exampleEn": "This week is very busy." },
    { "id": "fr-0083", "front": "le mois", "back": "the month", "example": "Le mois prochain, je déménage.", "exampleEn": "Next month, I'm moving." },
    { "id": "fr-0084", "front": "l'année", "back": "the year", "example": "Bonne année à tous !", "exampleEn": "Happy New Year to everyone!" },
    { "id": "fr-0085", "front": "le jour", "back": "the day", "example": "Quel beau jour aujourd'hui !", "exampleEn": "What a beautiful day today!" },
    { "id": "fr-0086", "front": "qui", "back": "who", "example": "Qui est à la porte ?", "exampleEn": "Who's at the door?" },
    { "id": "fr-0087", "front": "quoi", "back": "what", "example": "Quoi ? Je n'ai pas compris.", "exampleEn": "What? I didn't understand." },
    { "id": "fr-0088", "front": "où", "back": "where", "example": "Où habites-tu ?", "exampleEn": "Where do you live?" },
    { "id": "fr-0089", "front": "quand", "back": "when", "example": "Quand arrives-tu ?", "exampleEn": "When are you arriving?" },
    { "id": "fr-0090", "front": "pourquoi", "back": "why", "example": "Pourquoi es-tu triste ?", "exampleEn": "Why are you sad?" },
    { "id": "fr-0091", "front": "comment", "back": "how", "example": "Comment tu t'appelles ?", "exampleEn": "What's your name?" },
    { "id": "fr-0092", "front": "combien", "back": "how much / how many", "example": "Combien ça coûte ?", "exampleEn": "How much does it cost?" },
    { "id": "fr-0093", "front": "quel", "back": "which / what (m.)", "example": "Quel est ton nom ?", "exampleEn": "What is your name?" },
    { "id": "fr-0094", "front": "je", "back": "I", "example": "Je suis fatigué ce soir.", "exampleEn": "I'm tired this evening." },
    { "id": "fr-0095", "front": "tu", "back": "you (informal)", "example": "Tu es très gentil.", "exampleEn": "You are very kind." },
    { "id": "fr-0096", "front": "il", "back": "he / it", "example": "Il travaille à Paris.", "exampleEn": "He works in Paris." },
    { "id": "fr-0097", "front": "elle", "back": "she / it", "example": "Elle aime le chocolat.", "exampleEn": "She loves chocolate." },
    { "id": "fr-0098", "front": "nous", "back": "we", "example": "Nous allons au cinéma.", "exampleEn": "We're going to the movies." },
    { "id": "fr-0099", "front": "vous", "back": "you (formal/plural)", "example": "Vous êtes très aimable.", "exampleEn": "You are very kind." },
    { "id": "fr-0100", "front": "ils", "back": "they (m.)", "example": "Ils jouent au football.", "exampleEn": "They're playing football." },
    { "id": "fr-0101", "front": "elles", "back": "they (f.)", "example": "Elles chantent ensemble.", "exampleEn": "They're singing together." },
    { "id": "fr-0102", "front": "on", "back": "we / one (informal)", "example": "On va manger maintenant ?", "exampleEn": "Are we going to eat now?" },
    { "id": "fr-0103", "front": "moi", "back": "me", "example": "C'est pour moi ?", "exampleEn": "Is this for me?" },
    { "id": "fr-0104", "front": "toi", "back": "you (stressed)", "example": "Et toi, comment vas-tu ?", "exampleEn": "And you, how are you?" },
    { "id": "fr-0105", "front": "être", "back": "to be", "example": "Je veux être heureux.", "exampleEn": "I want to be happy." },
    { "id": "fr-0106", "front": "avoir", "back": "to have", "example": "J'aimerais avoir un chien.", "exampleEn": "I'd love to have a dog." },
    { "id": "fr-0107", "front": "faire", "back": "to do / to make", "example": "Que veux-tu faire ce soir ?", "exampleEn": "What do you want to do tonight?" },
    { "id": "fr-0108", "front": "aller", "back": "to go", "example": "Je dois aller au travail.", "exampleEn": "I have to go to work." },
    { "id": "fr-0109", "front": "venir", "back": "to come", "example": "Tu peux venir avec moi.", "exampleEn": "You can come with me." },
    { "id": "fr-0110", "front": "voir", "back": "to see", "example": "J'aimerais voir ce film.", "exampleEn": "I'd love to see that film." },
    { "id": "fr-0111", "front": "savoir", "back": "to know (a fact)", "example": "Je veux savoir la vérité.", "exampleEn": "I want to know the truth." },
    { "id": "fr-0112", "front": "pouvoir", "back": "to be able to / can", "example": "Tu peux m'aider ?", "exampleEn": "Can you help me?" },
    { "id": "fr-0113", "front": "vouloir", "back": "to want", "example": "Je veux un verre d'eau.", "exampleEn": "I want a glass of water." },
    { "id": "fr-0114", "front": "devoir", "back": "to have to / must", "example": "Je dois partir tôt.", "exampleEn": "I have to leave early." },
    { "id": "fr-0115", "front": "prendre", "back": "to take", "example": "Je vais prendre le train.", "exampleEn": "I'm going to take the train." },
    { "id": "fr-0116", "front": "parler", "back": "to speak", "example": "Tu peux parler plus lentement ?", "exampleEn": "Can you speak more slowly?" },
    { "id": "fr-0117", "front": "manger", "back": "to eat", "example": "On va manger au restaurant.", "exampleEn": "We're going to eat at a restaurant." },
    { "id": "fr-0118", "front": "boire", "back": "to drink", "example": "Je voudrais boire un café.", "exampleEn": "I'd like to drink a coffee." },
    { "id": "fr-0119", "front": "dormir", "back": "to sleep", "example": "J'ai besoin de dormir.", "exampleEn": "I need to sleep." },
    { "id": "fr-0120", "front": "aimer", "back": "to like / to love", "example": "J'aime beaucoup ce livre.", "exampleEn": "I really like this book." },
    { "id": "fr-0121", "front": "donner", "back": "to give", "example": "Peux-tu me donner ce stylo ?", "exampleEn": "Can you give me that pen?" },
    { "id": "fr-0122", "front": "trouver", "back": "to find", "example": "Je ne trouve pas mes clés.", "exampleEn": "I can't find my keys." },
    { "id": "fr-0123", "front": "dire", "back": "to say / to tell", "example": "Que veux-tu dire ?", "exampleEn": "What do you mean?" },
    { "id": "fr-0124", "front": "comprendre", "back": "to understand", "example": "Je ne comprends pas la question.", "exampleEn": "I don't understand the question." },
    { "id": "fr-0125", "front": "acheter", "back": "to buy", "example": "Je dois acheter du pain.", "exampleEn": "I need to buy some bread." },
    { "id": "fr-0126", "front": "travailler", "back": "to work", "example": "Je travaille dans un bureau.", "exampleEn": "I work in an office." },
    { "id": "fr-0127", "front": "habiter", "back": "to live (reside)", "example": "J'habite à Lyon.", "exampleEn": "I live in Lyon." },
    { "id": "fr-0128", "front": "écouter", "back": "to listen", "example": "J'aime écouter de la musique.", "exampleEn": "I love listening to music." },
    { "id": "fr-0129", "front": "regarder", "back": "to watch / to look", "example": "On regarde un film ce soir.", "exampleEn": "We're watching a movie tonight." },
    { "id": "fr-0130", "front": "lire", "back": "to read", "example": "J'aime lire avant de dormir.", "exampleEn": "I love reading before going to sleep." },
    { "id": "fr-0131", "front": "écrire", "back": "to write", "example": "Je dois écrire une lettre.", "exampleEn": "I need to write a letter." },
    { "id": "fr-0132", "front": "attendre", "back": "to wait", "example": "Attends-moi devant la porte.", "exampleEn": "Wait for me in front of the door." },
    { "id": "fr-0133", "front": "ouvrir", "back": "to open", "example": "Peux-tu ouvrir la fenêtre ?", "exampleEn": "Can you open the window?" },
    { "id": "fr-0134", "front": "fermer", "back": "to close", "example": "N'oublie pas de fermer la porte.", "exampleEn": "Don't forget to close the door." },
    { "id": "fr-0135", "front": "le père", "back": "the father", "example": "Mon père est médecin.", "exampleEn": "My father is a doctor." },
    { "id": "fr-0136", "front": "la mère", "back": "the mother", "example": "Ma mère cuisine très bien.", "exampleEn": "My mother cooks very well." },
    { "id": "fr-0137", "front": "le fils", "back": "the son", "example": "Leur fils a cinq ans.", "exampleEn": "Their son is five years old." },
    { "id": "fr-0138", "front": "la fille", "back": "the daughter / girl", "example": "Sa fille étudie à Paris.", "exampleEn": "His daughter studies in Paris." },
    { "id": "fr-0139", "front": "le frère", "back": "the brother", "example": "Mon frère habite à Nice.", "exampleEn": "My brother lives in Nice." },
    { "id": "fr-0140", "front": "la sœur", "back": "the sister", "example": "Ma sœur est plus jeune que moi.", "exampleEn": "My sister is younger than me." },
    { "id": "fr-0141", "front": "les parents", "back": "the parents", "example": "Mes parents sont en voyage.", "exampleEn": "My parents are traveling." },
    { "id": "fr-0142", "front": "l'enfant", "back": "the child", "example": "L'enfant joue dans le jardin.", "exampleEn": "The child is playing in the garden." },
    { "id": "fr-0143", "front": "le mari", "back": "the husband", "example": "Son mari travaille à l'hôpital.", "exampleEn": "Her husband works at the hospital." },
    { "id": "fr-0144", "front": "la femme", "back": "the wife / woman", "example": "Sa femme est avocate.", "exampleEn": "His wife is a lawyer." },
    { "id": "fr-0145", "front": "l'ami", "back": "the friend (m.)", "example": "C'est un ami d'enfance.", "exampleEn": "He's a childhood friend." },
    { "id": "fr-0146", "front": "l'amie", "back": "the friend (f.)", "example": "Mon amie arrive ce soir.", "exampleEn": "My friend is arriving tonight." },
    { "id": "fr-0147", "front": "l'homme", "back": "the man", "example": "Cet homme est très grand.", "exampleEn": "That man is very tall." },
    { "id": "fr-0148", "front": "le bébé", "back": "the baby", "example": "Le bébé dort dans son lit.", "exampleEn": "The baby is sleeping in his bed." },
    { "id": "fr-0149", "front": "le pain", "back": "the bread", "example": "J'achète du pain tous les matins.", "exampleEn": "I buy bread every morning." },
    { "id": "fr-0150", "front": "l'eau", "back": "the water", "example": "Je voudrais un verre d'eau.", "exampleEn": "I'd like a glass of water." },
    { "id": "fr-0151", "front": "le café", "back": "the coffee", "example": "Je bois un café le matin.", "exampleEn": "I drink a coffee in the morning." },
    { "id": "fr-0152", "front": "le thé", "back": "the tea", "example": "Tu préfères le thé ou le café ?", "exampleEn": "Do you prefer tea or coffee?" },
    { "id": "fr-0153", "front": "le lait", "back": "the milk", "example": "Il y a du lait dans le frigo.", "exampleEn": "There's milk in the fridge." },
    { "id": "fr-0154", "front": "le vin", "back": "the wine", "example": "Un verre de vin rouge, s'il vous plaît.", "exampleEn": "A glass of red wine, please." },
    { "id": "fr-0155", "front": "le fromage", "back": "the cheese", "example": "Ce fromage vient de Normandie.", "exampleEn": "This cheese comes from Normandy." },
    { "id": "fr-0156", "front": "la viande", "back": "the meat", "example": "Je ne mange pas de viande.", "exampleEn": "I don't eat meat." },
    { "id": "fr-0157", "front": "le poisson", "back": "the fish", "example": "Le poisson est très frais ici.", "exampleEn": "The fish is very fresh here." },
    { "id": "fr-0158", "front": "le fruit", "back": "the fruit", "example": "Je mange un fruit chaque jour.", "exampleEn": "I eat a piece of fruit every day." },
    { "id": "fr-0159", "front": "le légume", "back": "the vegetable", "example": "Mange tes légumes, c'est bon pour toi.", "exampleEn": "Eat your vegetables, they're good for you." },
    { "id": "fr-0160", "front": "la pomme", "back": "the apple", "example": "Cette pomme est très sucrée.", "exampleEn": "This apple is very sweet." },
    { "id": "fr-0161", "front": "le repas", "back": "the meal", "example": "Le repas était délicieux.", "exampleEn": "The meal was delicious." },
    { "id": "fr-0162", "front": "le petit-déjeuner", "back": "breakfast", "example": "Je prends mon petit-déjeuner à huit heures.", "exampleEn": "I have breakfast at eight o'clock." },
    { "id": "fr-0163", "front": "le déjeuner", "back": "lunch", "example": "Le déjeuner est servi à midi.", "exampleEn": "Lunch is served at noon." },
    { "id": "fr-0164", "front": "le dîner", "back": "dinner", "example": "Le dîner est prêt.", "exampleEn": "Dinner is ready." },
    { "id": "fr-0165", "front": "la maison", "back": "the house", "example": "Leur maison est près de la mer.", "exampleEn": "Their house is near the sea." },
    { "id": "fr-0166", "front": "l'appartement", "back": "the apartment", "example": "Mon appartement est petit mais lumineux.", "exampleEn": "My apartment is small but bright." },
    { "id": "fr-0167", "front": "la chambre", "back": "the bedroom", "example": "Ma chambre est au premier étage.", "exampleEn": "My bedroom is on the first floor." },
    { "id": "fr-0168", "front": "la cuisine", "back": "the kitchen", "example": "La cuisine est très moderne.", "exampleEn": "The kitchen is very modern." },
    { "id": "fr-0169", "front": "la salle de bain", "back": "the bathroom", "example": "La salle de bain est au fond du couloir.", "exampleEn": "The bathroom is at the end of the hallway." },
    { "id": "fr-0170", "front": "la porte", "back": "the door", "example": "Ferme la porte, il fait froid.", "exampleEn": "Close the door, it's cold." },
    { "id": "fr-0171", "front": "la fenêtre", "back": "the window", "example": "Ouvre la fenêtre pour aérer.", "exampleEn": "Open the window to air the room out." },
    { "id": "fr-0172", "front": "la table", "back": "the table", "example": "Le repas est sur la table.", "exampleEn": "The food is on the table." },
    { "id": "fr-0173", "front": "la chaise", "back": "the chair", "example": "Prends une chaise et assieds-toi.", "exampleEn": "Grab a chair and sit down." },
    { "id": "fr-0174", "front": "le lit", "back": "the bed", "example": "Le lit est très confortable.", "exampleEn": "The bed is very comfortable." },
    { "id": "fr-0175", "front": "la tête", "back": "the head", "example": "J'ai mal à la tête.", "exampleEn": "I have a headache." },
    { "id": "fr-0176", "front": "la main", "back": "the hand", "example": "Donne-moi la main.", "exampleEn": "Give me your hand." },
    { "id": "fr-0177", "front": "le pied", "back": "the foot", "example": "J'ai mal au pied gauche.", "exampleEn": "My left foot hurts." },
    { "id": "fr-0178", "front": "l'œil", "back": "the eye", "example": "Il a quelque chose dans l'œil.", "exampleEn": "He has something in his eye." },
    { "id": "fr-0179", "front": "le bras", "back": "the arm", "example": "Elle a mal au bras.", "exampleEn": "Her arm hurts." },
    { "id": "fr-0180", "front": "la jambe", "back": "the leg", "example": "Il s'est blessé à la jambe.", "exampleEn": "He hurt his leg." },
    { "id": "fr-0181", "front": "le cœur", "back": "the heart", "example": "Mon cœur bat très vite.", "exampleEn": "My heart is beating very fast." },
    { "id": "fr-0182", "front": "la ville", "back": "the city / town", "example": "J'habite dans une grande ville.", "exampleEn": "I live in a big city." },
    { "id": "fr-0183", "front": "la rue", "back": "the street", "example": "La rue est très calme la nuit.", "exampleEn": "The street is very quiet at night." },
    { "id": "fr-0184", "front": "le magasin", "back": "the shop / store", "example": "Le magasin ferme à dix-neuf heures.", "exampleEn": "The store closes at seven in the evening." },
    { "id": "fr-0185", "front": "le marché", "back": "the market", "example": "Je vais au marché le samedi.", "exampleEn": "I go to the market on Saturdays." },
    { "id": "fr-0186", "front": "le restaurant", "back": "the restaurant", "example": "On dîne au restaurant ce soir.", "exampleEn": "We're having dinner at a restaurant tonight." },
    { "id": "fr-0187", "front": "l'école", "back": "the school", "example": "Les enfants vont à l'école à pied.", "exampleEn": "The children walk to school." },
    { "id": "fr-0188", "front": "l'hôpital", "back": "the hospital", "example": "L'hôpital est près d'ici.", "exampleEn": "The hospital is nearby." },
    { "id": "fr-0189", "front": "la gare", "back": "the train station", "example": "La gare est à dix minutes.", "exampleEn": "The train station is ten minutes away." },
    { "id": "fr-0190", "front": "l'aéroport", "back": "the airport", "example": "Nous partons à l'aéroport tôt.", "exampleEn": "We're leaving for the airport early." },
    { "id": "fr-0191", "front": "la banque", "back": "the bank", "example": "La banque ouvre à neuf heures.", "exampleEn": "The bank opens at nine o'clock." },
    { "id": "fr-0192", "front": "le travail", "back": "the work / job", "example": "J'aime beaucoup mon travail.", "exampleEn": "I really love my job." },
    { "id": "fr-0193", "front": "le bureau", "back": "the office / desk", "example": "Je suis au bureau jusqu'à dix-huit heures.", "exampleEn": "I'm at the office until six in the evening." },
    { "id": "fr-0194", "front": "l'argent", "back": "the money", "example": "Je n'ai pas assez d'argent.", "exampleEn": "I don't have enough money." },
    { "id": "fr-0195", "front": "l'arbre", "back": "the tree", "example": "L'arbre devant la maison est très vieux.", "exampleEn": "The tree in front of the house is very old." },
    { "id": "fr-0196", "front": "la fleur", "back": "the flower", "example": "Cette fleur sent très bon.", "exampleEn": "This flower smells wonderful." },
    { "id": "fr-0197", "front": "le soleil", "back": "the sun", "example": "Le soleil brille aujourd'hui.", "exampleEn": "The sun is shining today." },
    { "id": "fr-0198", "front": "la mer", "back": "the sea", "example": "La mer est calme ce matin.", "exampleEn": "The sea is calm this morning." },
    { "id": "fr-0199", "front": "la montagne", "back": "the mountain", "example": "On part à la montagne cet hiver.", "exampleEn": "We're heading to the mountains this winter." },
    { "id": "fr-0200", "front": "le ciel", "back": "the sky", "example": "Le ciel est bleu aujourd'hui.", "exampleEn": "The sky is blue today." },
    { "id": "fr-0201", "front": "le chien", "back": "the dog", "example": "Mon chien adore courir dans le parc.", "exampleEn": "My dog loves running in the park." },
    { "id": "fr-0202", "front": "le chat", "back": "the cat", "example": "Le chat dort sur le canapé.", "exampleEn": "The cat is sleeping on the sofa." },
    { "id": "fr-0203", "front": "la voiture", "back": "the car", "example": "Ma voiture est garée dehors.", "exampleEn": "My car is parked outside." },
    { "id": "fr-0204", "front": "le train", "back": "the train", "example": "Le train arrive dans cinq minutes.", "exampleEn": "The train arrives in five minutes." },
    { "id": "fr-0205", "front": "le bus", "back": "the bus", "example": "Je prends le bus pour aller au travail.", "exampleEn": "I take the bus to get to work." },
    { "id": "fr-0206", "front": "le vélo", "back": "the bicycle", "example": "Elle va à l'école à vélo.", "exampleEn": "She rides her bike to school." },
    { "id": "fr-0207", "front": "l'avion", "back": "the airplane", "example": "L'avion décolle à midi.", "exampleEn": "The plane takes off at noon." },
    { "id": "fr-0208", "front": "le livre", "back": "the book", "example": "Ce livre est passionnant.", "exampleEn": "This book is fascinating." },
    { "id": "fr-0209", "front": "le téléphone", "back": "the phone", "example": "Mon téléphone n'a plus de batterie.", "exampleEn": "My phone is out of battery." },
    { "id": "fr-0210", "front": "l'ordinateur", "back": "the computer", "example": "Je travaille sur mon ordinateur.", "exampleEn": "I work on my computer." },
    { "id": "fr-0211", "front": "grand", "back": "big / tall", "example": "Il habite dans une grande maison.", "exampleEn": "He lives in a big house." },
    { "id": "fr-0212", "front": "petit", "back": "small / little", "example": "C'est un petit village tranquille.", "exampleEn": "It's a quiet little village." },
    { "id": "fr-0213", "front": "bon", "back": "good", "example": "Ce gâteau est très bon.", "exampleEn": "This cake is very good." },
    { "id": "fr-0214", "front": "mauvais", "back": "bad", "example": "Il fait mauvais temps aujourd'hui.", "exampleEn": "The weather is bad today." },
    { "id": "fr-0215", "front": "beau", "back": "beautiful / handsome", "example": "Quel beau paysage !", "exampleEn": "What a beautiful landscape!" },
    { "id": "fr-0216", "front": "joli", "back": "pretty", "example": "Elle porte une jolie robe.", "exampleEn": "She's wearing a pretty dress." },
    { "id": "fr-0217", "front": "nouveau", "back": "new", "example": "J'ai acheté un nouveau manteau.", "exampleEn": "I bought a new coat." },
    { "id": "fr-0218", "front": "vieux", "back": "old", "example": "C'est un vieux livre de mon grand-père.", "exampleEn": "It's an old book from my grandfather." },
    { "id": "fr-0219", "front": "jeune", "back": "young", "example": "Elle est encore très jeune.", "exampleEn": "She is still very young." },
    { "id": "fr-0220", "front": "chaud", "back": "hot / warm", "example": "Le café est encore chaud.", "exampleEn": "The coffee is still hot." },
    { "id": "fr-0221", "front": "froid", "back": "cold", "example": "L'eau est trop froide pour nager.", "exampleEn": "The water is too cold for swimming." },
    { "id": "fr-0222", "front": "facile", "back": "easy", "example": "Cet exercice est très facile.", "exampleEn": "This exercise is very easy." },
    { "id": "fr-0223", "front": "difficile", "back": "difficult", "example": "Le français n'est pas si difficile.", "exampleEn": "French isn't that difficult." },
    { "id": "fr-0224", "front": "content", "back": "happy / glad", "example": "Je suis content de te voir.", "exampleEn": "I'm happy to see you." },
    { "id": "fr-0225", "front": "fatigué", "back": "tired", "example": "Je suis très fatigué ce soir.", "exampleEn": "I'm very tired this evening." },
    { "id": "fr-0226", "front": "cher", "back": "expensive / dear", "example": "Ce restaurant est trop cher.", "exampleEn": "This restaurant is too expensive." },
    { "id": "fr-0227", "front": "rouge", "back": "red", "example": "J'aime ta veste rouge.", "exampleEn": "I love your red jacket." },
    { "id": "fr-0228", "front": "bleu", "back": "blue", "example": "Le ciel est bleu aujourd'hui.", "exampleEn": "The sky is blue today." },
    { "id": "fr-0229", "front": "vert", "back": "green", "example": "Les feuilles sont vertes au printemps.", "exampleEn": "The leaves are green in spring." },
    { "id": "fr-0230", "front": "jaune", "back": "yellow", "example": "Le soleil est jaune et brillant.", "exampleEn": "The sun is yellow and bright." },
    { "id": "fr-0231", "front": "noir", "back": "black", "example": "Il porte un costume noir.", "exampleEn": "He's wearing a black suit." },
    { "id": "fr-0232", "front": "blanc", "back": "white", "example": "La neige est toute blanche.", "exampleEn": "The snow is all white." },
    { "id": "fr-0233", "front": "à droite", "back": "to/on the right", "example": "Tournez à droite après la banque.", "exampleEn": "Turn right after the bank." },
    { "id": "fr-0234", "front": "à gauche", "back": "to/on the left", "example": "La pharmacie est à gauche.", "exampleEn": "The pharmacy is on the left." },
    { "id": "fr-0235", "front": "tout droit", "back": "straight ahead", "example": "Continuez tout droit jusqu'au feu.", "exampleEn": "Continue straight ahead to the traffic light." },
    { "id": "fr-0236", "front": "ici", "back": "here", "example": "Viens ici, s'il te plaît.", "exampleEn": "Come here, please." },
    { "id": "fr-0237", "front": "là", "back": "there", "example": "Pose le sac là, sur la chaise.", "exampleEn": "Put the bag there, on the chair." },
    { "id": "fr-0238", "front": "près de", "back": "near / close to", "example": "J'habite près de la gare.", "exampleEn": "I live near the train station." },
    { "id": "fr-0239", "front": "loin de", "back": "far from", "example": "L'aéroport est loin du centre-ville.", "exampleEn": "The airport is far from the city center." },
    { "id": "fr-0240", "front": "le temps", "back": "the weather / time", "example": "Quel temps fait-il aujourd'hui ?", "exampleEn": "What's the weather like today?" },
    { "id": "fr-0241", "front": "la pluie", "back": "the rain", "example": "La pluie n'a pas arrêté de la journée.", "exampleEn": "It hasn't stopped raining all day." },
    { "id": "fr-0242", "front": "la neige", "back": "the snow", "example": "La neige recouvre les montagnes.", "exampleEn": "Snow covers the mountains." },
    { "id": "fr-0243", "front": "le vent", "back": "the wind", "example": "Le vent souffle très fort ce soir.", "exampleEn": "The wind is blowing very hard tonight." },
    { "id": "fr-0244", "front": "il fait beau", "back": "the weather is nice", "example": "Aujourd'hui, il fait beau et chaud.", "exampleEn": "Today the weather is nice and warm." },
    { "id": "fr-0245", "front": "il pleut", "back": "it's raining", "example": "Prends un parapluie, il pleut.", "exampleEn": "Take an umbrella, it's raining." },
    { "id": "fr-0246", "front": "beaucoup", "back": "a lot / much", "example": "Merci beaucoup pour ton aide.", "exampleEn": "Thank you very much for your help." },
    { "id": "fr-0247", "front": "un peu", "back": "a little", "example": "Je parle un peu français.", "exampleEn": "I speak a little French." },
    { "id": "fr-0248", "front": "très", "back": "very", "example": "Ce film est très intéressant.", "exampleEn": "This film is very interesting." },
    { "id": "fr-0249", "front": "toujours", "back": "always", "example": "Elle est toujours en retard.", "exampleEn": "She is always late." },
    { "id": "fr-0250", "front": "jamais", "back": "never", "example": "Je ne bois jamais de café le soir.", "exampleEn": "I never drink coffee in the evening." },
    { "id": "fr-0251", "front": "la boulangerie", "back": "bakery", "example": "J'achète ma baguette à la boulangerie du coin.", "exampleEn": "I buy my baguette at the corner bakery." },
    { "id": "fr-0252", "front": "le voyage", "back": "trip, journey", "example": "Mon voyage en France était magnifique.", "exampleEn": "My trip to France was magnificent." },
    { "id": "fr-0253", "front": "le salaire", "back": "salary; wage", "example": "Son salaire a augmenté cette année.", "exampleEn": "His salary increased this year." },
    { "id": "fr-0254", "front": "le salon", "back": "living room", "example": "Nous regardons la télé dans le salon.", "exampleEn": "We watch TV in the living room." },
    { "id": "fr-0255", "front": "le corps", "back": "the body", "example": "Le sport est bon pour le corps.", "exampleEn": "Sports are good for the body." },
    { "id": "fr-0256", "front": "la boucherie", "back": "butcher's shop", "example": "Le boucher de la boucherie coupe le steak.", "exampleEn": "The butcher at the butcher's shop cuts the steak." },
    { "id": "fr-0257", "front": "le billet", "back": "ticket", "example": "J'ai acheté un billet de train pour Lyon.", "exampleEn": "I bought a train ticket to Lyon." },
    { "id": "fr-0258", "front": "l'entreprise", "back": "company; business", "example": "Il dirige une petite entreprise.", "exampleEn": "He runs a small company." },
    { "id": "fr-0259", "front": "la salle à manger", "back": "dining room", "example": "La famille mange dans la salle à manger.", "exampleEn": "The family eats in the dining room." },
    { "id": "fr-0260", "front": "le dos", "back": "the back", "example": "J'ai mal au dos aujourd'hui.", "exampleEn": "My back hurts today." },
    { "id": "fr-0261", "front": "l'épicerie", "back": "grocery store", "example": "Je vais à l'épicerie acheter des tomates.", "exampleEn": "I'm going to the grocery store to buy tomatoes." },
    { "id": "fr-0262", "front": "le passeport", "back": "passport", "example": "N'oublie pas ton passeport avant de partir.", "exampleEn": "Don't forget your passport before leaving." },
    { "id": "fr-0263", "front": "le collègue", "back": "colleague; coworker", "example": "Ma collègue m'aide avec le projet.", "exampleEn": "My colleague helps me with the project." },
    { "id": "fr-0264", "front": "le couloir", "back": "hallway, corridor", "example": "Les chaussures sont dans le couloir.", "exampleEn": "The shoes are in the hallway." },
    { "id": "fr-0265", "front": "le ventre", "back": "the stomach / belly", "example": "Il a mal au ventre après le repas.", "exampleEn": "He has a stomachache after the meal." },
    { "id": "fr-0266", "front": "la carte", "back": "menu", "example": "Pouvez-vous m'apporter la carte, s'il vous plaît ?", "exampleEn": "Can you bring me the menu, please?" },
    { "id": "fr-0267", "front": "la valise", "back": "suitcase", "example": "Ma valise est trop lourde.", "exampleEn": "My suitcase is too heavy." },
    { "id": "fr-0268", "front": "la réunion", "back": "meeting", "example": "Nous avons une réunion à neuf heures.", "exampleEn": "We have a meeting at nine o'clock." },
    { "id": "fr-0269", "front": "le grenier", "back": "attic", "example": "Il range ses vieux jouets au grenier.", "exampleEn": "He stores his old toys in the attic." },
    { "id": "fr-0270", "front": "le nez", "back": "the nose", "example": "Elle a le nez rouge à cause du froid.", "exampleEn": "Her nose is red because of the cold." },
    { "id": "fr-0271", "front": "l'addition", "back": "the bill / check", "example": "L'addition, s'il vous plaît, nous partons.", "exampleEn": "The bill, please, we are leaving." },
    { "id": "fr-0272", "front": "le bagage", "back": "luggage, baggage", "example": "Tu as combien de bagages ?", "exampleEn": "How many pieces of luggage do you have?" },
    { "id": "fr-0273", "front": "le client", "back": "client; customer", "example": "Le client attend depuis une heure.", "exampleEn": "The client has been waiting for an hour." },
    { "id": "fr-0274", "front": "la cave", "back": "cellar, basement", "example": "Le vin est gardé dans la cave.", "exampleEn": "The wine is kept in the cellar." },
    { "id": "fr-0275", "front": "la bouche", "back": "the mouth", "example": "Ouvre la bouche, s'il te plaît.", "exampleEn": "Open your mouth, please." },
    { "id": "fr-0276", "front": "le serveur", "back": "waiter", "example": "Le serveur apporte nos plats rapidement.", "exampleEn": "The waiter brings our dishes quickly." },
    { "id": "fr-0277", "front": "le vol", "back": "flight", "example": "Notre vol part à midi.", "exampleEn": "Our flight leaves at noon." },
    { "id": "fr-0278", "front": "la facture", "back": "invoice; bill", "example": "Envoie la facture par email.", "exampleEn": "Send the invoice by email." },
    { "id": "fr-0279", "front": "le jardin", "back": "garden, yard", "example": "Les enfants jouent dans le jardin.", "exampleEn": "The children play in the garden." },
    { "id": "fr-0280", "front": "l'oreille", "back": "the ear", "example": "J'ai mal à l'oreille depuis hier.", "exampleEn": "My ear has been hurting since yesterday." },
    { "id": "fr-0281", "front": "la serveuse", "back": "waitress", "example": "La serveuse nous recommande le plat du jour.", "exampleEn": "The waitress recommends the daily special to us." },
    { "id": "fr-0282", "front": "l'hôtel", "back": "hotel", "example": "Nous restons dans un hôtel près de la mer.", "exampleEn": "We are staying in a hotel near the sea." },
    { "id": "fr-0283", "front": "le contrat", "back": "contract", "example": "Tu dois signer le contrat aujourd'hui.", "exampleEn": "You must sign the contract today." },
    { "id": "fr-0284", "front": "le balcon", "back": "balcony", "example": "Elle prend son café sur le balcon.", "exampleEn": "She has her coffee on the balcony." },
    { "id": "fr-0285", "front": "le genou", "back": "the knee", "example": "Il s'est blessé le genou en courant.", "exampleEn": "He hurt his knee while running." },
    { "id": "fr-0286", "front": "le plat du jour", "back": "daily special", "example": "Le plat du jour est une sole meunière.", "exampleEn": "The daily special is sole meunière." },
    { "id": "fr-0287", "front": "la chambre d'hôtel", "back": "hotel room", "example": "La chambre d'hôtel a une belle vue.", "exampleEn": "The hotel room has a beautiful view." },
    { "id": "fr-0288", "front": "le patron", "back": "boss; employer", "example": "Mon patron est très exigeant.", "exampleEn": "My boss is very demanding." },
    { "id": "fr-0289", "front": "l'escalier", "back": "staircase, stairs", "example": "Il monte l'escalier pour aller se coucher.", "exampleEn": "He goes up the stairs to go to bed." },
    { "id": "fr-0290", "front": "l'épaule", "back": "the shoulder", "example": "Elle porte son sac sur l'épaule gauche.", "exampleEn": "She carries her bag on her left shoulder." },
    { "id": "fr-0291", "front": "l'entrée", "back": "starter / appetizer", "example": "Je prends une soupe comme entrée.", "exampleEn": "I'll have a soup as a starter." },
    { "id": "fr-0292", "front": "la réservation", "back": "reservation, booking", "example": "J'ai une réservation pour deux nuits.", "exampleEn": "I have a reservation for two nights." },
    { "id": "fr-0293", "front": "l'employé", "back": "employee", "example": "L'employé arrive toujours à l'heure.", "exampleEn": "The employee always arrives on time." },
    { "id": "fr-0294", "front": "le canapé", "back": "sofa, couch", "example": "Mon père s'endort toujours sur le canapé.", "exampleEn": "My father always falls asleep on the sofa." },
    { "id": "fr-0295", "front": "la gorge", "back": "the throat", "example": "J'ai mal à la gorge ce matin.", "exampleEn": "I have a sore throat this morning." },
    { "id": "fr-0296", "front": "le plat principal", "back": "main course", "example": "Pour le plat principal, je veux le poulet rôti.", "exampleEn": "For the main course, I want the roast chicken." },
    { "id": "fr-0297", "front": "le quai", "back": "platform, quay", "example": "Le train part du quai numéro cinq.", "exampleEn": "The train leaves from platform five." },
    { "id": "fr-0298", "front": "le chiffre d'affaires", "back": "revenue; turnover", "example": "Le chiffre d'affaires a doublé en un an.", "exampleEn": "Revenue doubled in one year." },
    { "id": "fr-0299", "front": "l'armoire", "back": "wardrobe, closet", "example": "Mes robes sont dans l'armoire.", "exampleEn": "My dresses are in the wardrobe." },
    { "id": "fr-0300", "front": "le pouce", "back": "the thumb", "example": "Il s'est coupé le pouce avec un couteau.", "exampleEn": "He cut his thumb with a knife." },
    { "id": "fr-0301", "front": "le dessert", "back": "dessert", "example": "Nous partageons un dessert au chocolat.", "exampleEn": "We share a chocolate dessert." },
    { "id": "fr-0302", "front": "le métro", "back": "subway, metro", "example": "Je prends le métro pour aller au travail.", "exampleEn": "I take the metro to go to work." },
    { "id": "fr-0303", "front": "le bénéfice", "back": "profit", "example": "L'entreprise a fait un gros bénéfice.", "exampleEn": "The company made a big profit." },
    { "id": "fr-0304", "front": "le miroir", "back": "mirror", "example": "Elle se regarde dans le miroir avant de sortir.", "exampleEn": "She looks at herself in the mirror before going out." },
    { "id": "fr-0305", "front": "la dent", "back": "the tooth", "example": "J'ai très mal aux dents depuis ce soir.", "exampleEn": "My teeth have been hurting badly since this evening." },
    { "id": "fr-0306", "front": "la recette", "back": "recipe", "example": "Ma grand-mère m'a donné sa recette de tarte.", "exampleEn": "My grandmother gave me her tart recipe." },
    { "id": "fr-0307", "front": "le taxi", "back": "taxi, cab", "example": "Appelons un taxi pour aller à l'aéroport.", "exampleEn": "Let's call a taxi to go to the airport." },
    { "id": "fr-0308", "front": "la perte", "back": "loss", "example": "Ils ont subi une perte importante.", "exampleEn": "They suffered a significant loss." },
    { "id": "fr-0309", "front": "le tapis", "back": "rug, carpet", "example": "Le chat dort sur le tapis.", "exampleEn": "The cat sleeps on the rug." },
    { "id": "fr-0310", "front": "la peau", "back": "the skin", "example": "Sa peau est très sensible au soleil.", "exampleEn": "His skin is very sensitive to the sun." },
    { "id": "fr-0311", "front": "les ingrédients", "back": "ingredients", "example": "Vérifie les ingrédients avant de commencer.", "exampleEn": "Check the ingredients before you start." },
    { "id": "fr-0312", "front": "le bateau", "back": "boat, ship", "example": "Nous traversons la rivière en bateau.", "exampleEn": "We cross the river by boat." },
    { "id": "fr-0313", "front": "le budget", "back": "budget", "example": "On dépasse le budget ce mois-ci.", "exampleEn": "We are going over budget this month." },
    { "id": "fr-0314", "front": "le rideau", "back": "curtain", "example": "Ferme le rideau, il y a trop de soleil.", "exampleEn": "Close the curtain, there is too much sun." },
    { "id": "fr-0315", "front": "le sang", "back": "blood", "example": "Il y a du sang sur sa main.", "exampleEn": "There is blood on his hand." },
    { "id": "fr-0316", "front": "la farine", "back": "flour", "example": "J'ai besoin d'un kilo de farine pour ce gâteau.", "exampleEn": "I need a kilo of flour for this cake." },
    { "id": "fr-0317", "front": "le ferry", "back": "ferry", "example": "Le ferry part toutes les heures.", "exampleEn": "The ferry leaves every hour." },
    { "id": "fr-0318", "front": "investir", "back": "to invest", "example": "Il veut investir dans l'immobilier.", "exampleEn": "He wants to invest in real estate." },
    { "id": "fr-0319", "front": "la lampe", "back": "lamp, light", "example": "J'allume la lampe pour lire.", "exampleEn": "I turn on the lamp to read." },
    { "id": "fr-0320", "front": "le poumon", "back": "the lung", "example": "Fumer est mauvais pour les poumons.", "exampleEn": "Smoking is bad for the lungs." },
    { "id": "fr-0321", "front": "le sucre", "back": "sugar", "example": "Tu mets trop de sucre dans ton café.", "exampleEn": "You put too much sugar in your coffee." },
    { "id": "fr-0322", "front": "la moto", "back": "motorcycle", "example": "Il voyage à travers l'Europe en moto.", "exampleEn": "He travels across Europe by motorcycle." },
    { "id": "fr-0323", "front": "emprunter", "back": "to borrow", "example": "Elle a emprunté de l'argent à la banque.", "exampleEn": "She borrowed money from the bank." },
    { "id": "fr-0324", "front": "le grand-père", "back": "grandfather", "example": "Mon grand-père me raconte des histoires.", "exampleEn": "My grandfather tells me stories." },
    { "id": "fr-0325", "front": "la santé", "back": "health", "example": "La santé est la chose la plus importante.", "exampleEn": "Health is the most important thing." },
    { "id": "fr-0326", "front": "le sel", "back": "salt", "example": "Ajoute une pincée de sel à la soupe.", "exampleEn": "Add a pinch of salt to the soup." },
    { "id": "fr-0327", "front": "le camion", "back": "truck, lorry", "example": "Un grand camion bloque la route.", "exampleEn": "A large truck is blocking the road." },
    { "id": "fr-0328", "front": "économiser", "back": "to save (money)", "example": "Je dois économiser pour les vacances.", "exampleEn": "I need to save money for the holidays." },
    { "id": "fr-0329", "front": "la grand-mère", "back": "grandmother", "example": "La grand-mère prépare un gâteau pour nous.", "exampleEn": "The grandmother is making a cake for us." },
    { "id": "fr-0330", "front": "la maladie", "back": "illness / disease", "example": "Cette maladie est très contagieuse.", "exampleEn": "This illness is very contagious." },
    { "id": "fr-0331", "front": "le poivre", "back": "pepper", "example": "Ce plat manque de poivre.", "exampleEn": "This dish lacks pepper." },
    { "id": "fr-0332", "front": "la station de métro", "back": "metro station", "example": "La station de métro est au coin de la rue.", "exampleEn": "The metro station is at the corner of the street." },
    { "id": "fr-0333", "front": "dépenser", "back": "to spend (money)", "example": "Il dépense trop en vêtements.", "exampleEn": "He spends too much on clothes." },
    { "id": "fr-0334", "front": "l'oncle", "back": "uncle", "example": "Mon oncle habite à Lyon.", "exampleEn": "My uncle lives in Lyon." },
    { "id": "fr-0335", "front": "la douleur", "back": "pain", "example": "La douleur dans ma jambe est forte.", "exampleEn": "The pain in my leg is intense." },
    { "id": "fr-0336", "front": "l'huile d'olive", "back": "olive oil", "example": "Fais revenir l'ail dans l'huile d'olive.", "exampleEn": "Sauté the garlic in olive oil." },
    { "id": "fr-0337", "front": "l'arrêt de bus", "back": "bus stop", "example": "Attends-moi à l'arrêt de bus.", "exampleEn": "Wait for me at the bus stop." },
    { "id": "fr-0338", "front": "le compte bancaire", "back": "bank account", "example": "Vérifie ton compte bancaire en ligne.", "exampleEn": "Check your bank account online." },
    { "id": "fr-0339", "front": "la tante", "back": "aunt", "example": "Ma tante nous invite à dîner dimanche.", "exampleEn": "My aunt is inviting us to dinner on Sunday." },
    { "id": "fr-0340", "front": "la fièvre", "back": "fever", "example": "L'enfant a de la fièvre depuis la nuit.", "exampleEn": "The child has had a fever since the night." },
    { "id": "fr-0341", "front": "le beurre", "back": "butter", "example": "Je fais fondre le beurre dans la poêle.", "exampleEn": "I melt the butter in the frying pan." },
    { "id": "fr-0342", "front": "le plan", "back": "map, plan (city)", "example": "Je consulte le plan du métro.", "exampleEn": "I'm checking the metro map." },
    { "id": "fr-0343", "front": "la carte bancaire", "back": "bank card; debit card", "example": "Je paie avec ma carte bancaire.", "exampleEn": "I'm paying with my bank card." },
    { "id": "fr-0344", "front": "le cousin", "back": "cousin (male)", "example": "Mon cousin joue au football avec moi.", "exampleEn": "My cousin plays football with me." },
    { "id": "fr-0345", "front": "le médicament", "back": "medicine / medication", "example": "Prends ce médicament deux fois par jour.", "exampleEn": "Take this medication twice a day." },
    { "id": "fr-0346", "front": "l'œuf", "back": "egg", "example": "Elle casse un œuf dans le bol.", "exampleEn": "She cracks an egg into the bowl." },
    { "id": "fr-0347", "front": "la direction", "back": "direction", "example": "Quelle direction prend-on pour le musée ?", "exampleEn": "Which direction do we take for the museum?" },
    { "id": "fr-0348", "front": "le virement", "back": "bank transfer", "example": "Fais un virement de cent euros.", "exampleEn": "Make a bank transfer of one hundred euros." },
    { "id": "fr-0349", "front": "la cousine", "back": "cousin (female)", "example": "Ma cousine arrive demain de Paris.", "exampleEn": "My cousin is arriving from Paris tomorrow." },
    { "id": "fr-0350", "front": "le médecin", "back": "doctor", "example": "Je vais voir le médecin demain matin.", "exampleEn": "I'm going to see the doctor tomorrow morning." },
    { "id": "fr-0351", "front": "la tomate", "back": "tomato", "example": "Cette salade a une belle tomate rouge.", "exampleEn": "This salad has a beautiful red tomato." },
    { "id": "fr-0352", "front": "le carrefour", "back": "intersection, crossroads", "example": "Tourne à gauche au carrefour.", "exampleEn": "Turn left at the intersection." },
    { "id": "fr-0353", "front": "la dette", "back": "debt", "example": "Il a remboursé toutes ses dettes.", "exampleEn": "He repaid all his debts." },
    { "id": "fr-0354", "front": "les grands-parents", "back": "grandparents", "example": "Nous rendons visite à nos grands-parents le week-end.", "exampleEn": "We visit our grandparents on the weekend." },
    { "id": "fr-0355", "front": "l'infirmière", "back": "the nurse", "example": "L'infirmière m'a fait une piqûre.", "exampleEn": "The nurse gave me an injection." },
    { "id": "fr-0356", "front": "l'oignon", "back": "onion", "example": "Je coupe l'oignon et je pleure.", "exampleEn": "I cut the onion and I cry." },
    { "id": "fr-0357", "front": "le feu rouge", "back": "traffic light (red)", "example": "Arrête-toi au feu rouge.", "exampleEn": "Stop at the red traffic light." },
    { "id": "fr-0358", "front": "le prêt", "back": "loan", "example": "Elle a obtenu un prêt pour sa maison.", "exampleEn": "She got a loan for her house." },
    { "id": "fr-0359", "front": "la famille", "back": "family", "example": "Toute la famille se réunit à Noël.", "exampleEn": "The whole family gathers at Christmas." },
    { "id": "fr-0360", "front": "la blessure", "back": "wound / injury", "example": "Sa blessure n'est pas grave heureusement.", "exampleEn": "His injury is not serious, fortunately." },
    { "id": "fr-0361", "front": "l'ail", "back": "garlic", "example": "L'ail donne beaucoup de goût à la sauce.", "exampleEn": "Garlic gives a lot of flavor to the sauce." },
    { "id": "fr-0362", "front": "le rond-point", "back": "roundabout", "example": "Prends la deuxième sortie au rond-point.", "exampleEn": "Take the second exit at the roundabout." },
    { "id": "fr-0363", "front": "les impôts", "back": "taxes", "example": "Il faut payer les impôts en avril.", "exampleEn": "You have to pay taxes in April." },
    { "id": "fr-0364", "front": "le neveu", "back": "nephew", "example": "Mon neveu a deux ans.", "exampleEn": "My nephew is two years old." },
    { "id": "fr-0365", "front": "se sentir bien", "back": "to feel well", "example": "Je me sens bien après une bonne nuit.", "exampleEn": "I feel well after a good night's sleep." },
    { "id": "fr-0366", "front": "la carotte", "back": "carrot", "example": "Je râpe une carotte pour la salade.", "exampleEn": "I grate a carrot for the salad." },
    { "id": "fr-0367", "front": "l'avenue", "back": "avenue", "example": "L'hôtel est sur cette avenue principale.", "exampleEn": "The hotel is on this main avenue." },
    { "id": "fr-0368", "front": "le cours", "back": "class; lesson", "example": "Le cours de maths commence à huit heures.", "exampleEn": "The math class starts at eight o'clock." },
    { "id": "fr-0369", "front": "la nièce", "back": "niece", "example": "J'achète un cadeau pour ma nièce.", "exampleEn": "I am buying a gift for my niece." },
    { "id": "fr-0370", "front": "être malade", "back": "to be sick", "example": "Elle est malade et reste au lit.", "exampleEn": "She is sick and stays in bed." },
    { "id": "fr-0371", "front": "la pomme de terre", "back": "potato", "example": "Ces pommes de terre sont parfaites pour la purée.", "exampleEn": "These potatoes are perfect for mashed potatoes." },
    { "id": "fr-0372", "front": "le boulevard", "back": "boulevard", "example": "Marche tout droit sur le boulevard.", "exampleEn": "Walk straight ahead on the boulevard." },
    { "id": "fr-0373", "front": "le professeur", "back": "teacher; professor", "example": "Le professeur explique la leçon clairement.", "exampleEn": "The teacher explains the lesson clearly." },
    { "id": "fr-0374", "front": "se lever", "back": "to get up", "example": "Je me lève à sept heures chaque matin.", "exampleEn": "I get up at seven o'clock every morning." },
    { "id": "fr-0375", "front": "guérir", "back": "to heal / to recover", "example": "Il a guéri rapidement grâce au repos.", "exampleEn": "He recovered quickly thanks to rest." },
    { "id": "fr-0376", "front": "le poulet", "back": "chicken", "example": "Nous mangeons du poulet rôti le dimanche.", "exampleEn": "We eat roast chicken on Sundays." },
    { "id": "fr-0377", "front": "la ruelle", "back": "alley, narrow street", "example": "Il y a un café dans cette petite ruelle.", "exampleEn": "There is a café in this little alley." },
    { "id": "fr-0378", "front": "l'élève", "back": "pupil; student", "example": "Chaque élève doit rendre ses devoirs.", "exampleEn": "Every pupil must hand in their homework." },
    { "id": "fr-0379", "front": "se coucher", "back": "to go to bed", "example": "Elle se couche tôt le soir.", "exampleEn": "She goes to bed early in the evening." },
    { "id": "fr-0380", "front": "la joie", "back": "joy", "example": "La joie se lisait sur son visage.", "exampleEn": "Joy could be read on her face." },
    { "id": "fr-0381", "front": "le bœuf", "back": "beef", "example": "Ce ragoût de bœuf mijote depuis deux heures.", "exampleEn": "This beef stew has been simmering for two hours." },
    { "id": "fr-0382", "front": "le pont", "back": "bridge", "example": "Traverse le pont pour arriver au centre-ville.", "exampleEn": "Cross the bridge to reach the city center." },
    { "id": "fr-0383", "front": "les devoirs", "back": "homework", "example": "J'ai fini mes devoirs avant le dîner.", "exampleEn": "I finished my homework before dinner." },
    { "id": "fr-0384", "front": "se laver", "back": "to wash oneself", "example": "Il se lave les mains avant de manger.", "exampleEn": "He washes his hands before eating." },
    { "id": "fr-0385", "front": "la tristesse", "back": "sadness", "example": "Il ressentait une grande tristesse ce soir.", "exampleEn": "He felt a great sadness this evening." },
    { "id": "fr-0386", "front": "l'agneau", "back": "lamb", "example": "Le gigot d'agneau est le plat de Pâques.", "exampleEn": "Leg of lamb is the Easter dish." },
    { "id": "fr-0387", "front": "le tunnel", "back": "tunnel", "example": "La voiture entre dans le tunnel.", "exampleEn": "The car enters the tunnel." },
    { "id": "fr-0388", "front": "la note", "back": "grade; mark", "example": "Il a eu une bonne note en histoire.", "exampleEn": "He got a good grade in history." },
    { "id": "fr-0389", "front": "se brosser les dents", "back": "to brush one's teeth", "example": "Elle se brosse les dents deux fois par jour.", "exampleEn": "She brushes her teeth twice a day." },
    { "id": "fr-0390", "front": "la peur", "back": "fear", "example": "Elle a peur du noir depuis l'enfance.", "exampleEn": "She has been afraid of the dark since childhood." },
    { "id": "fr-0391", "front": "les fruits de mer", "back": "seafood", "example": "Ce restaurant propose d'excellents fruits de mer.", "exampleEn": "This restaurant offers excellent seafood." },
    { "id": "fr-0392", "front": "la place", "back": "square, plaza", "example": "On se retrouve sur la place centrale.", "exampleEn": "We meet at the central square." },
    { "id": "fr-0393", "front": "l'examen", "back": "exam; test", "example": "Elle révise pour son examen de demain.", "exampleEn": "She is studying for her exam tomorrow." },
    { "id": "fr-0394", "front": "se coiffer", "back": "to do one's hair", "example": "Il se coiffe rapidement avant de partir.", "exampleEn": "He quickly does his hair before leaving." },
    { "id": "fr-0395", "front": "la colère", "back": "anger", "example": "Sa colère est difficile à contrôler.", "exampleEn": "His anger is difficult to control." },
    { "id": "fr-0396", "front": "la crevette", "back": "shrimp / prawn", "example": "Je commande des crevettes grillées en entrée.", "exampleEn": "I order grilled shrimp as a starter." },
    { "id": "fr-0397", "front": "le centre-ville", "back": "city center, downtown", "example": "Le musée est au centre-ville.", "exampleEn": "The museum is in the city center." },
    { "id": "fr-0398", "front": "réviser", "back": "to revise; to study", "example": "Tu dois réviser tes notes ce soir.", "exampleEn": "You must review your notes tonight." },
    { "id": "fr-0399", "front": "s'habiller", "back": "to get dressed", "example": "Les enfants s'habillent seuls maintenant.", "exampleEn": "The children get dressed by themselves now." },
    { "id": "fr-0400", "front": "la surprise", "back": "surprise", "example": "Sa surprise était visible quand il est arrivé.", "exampleEn": "Her surprise was visible when he arrived." },
    { "id": "fr-0401", "front": "le saumon", "back": "salmon", "example": "Le saumon fumé est délicieux sur des toasts.", "exampleEn": "Smoked salmon is delicious on toast." },
    { "id": "fr-0402", "front": "le quartier", "back": "neighborhood, district", "example": "J'habite dans un quartier calme.", "exampleEn": "I live in a quiet neighborhood." },
    { "id": "fr-0403", "front": "la classe", "back": "classroom; class (group)", "example": "Il y a trente élèves dans ma classe.", "exampleEn": "There are thirty students in my class." },
    { "id": "fr-0404", "front": "se doucher", "back": "to take a shower", "example": "Je me douche chaque matin avant le travail.", "exampleEn": "I take a shower every morning before work." },
    { "id": "fr-0405", "front": "heureux / heureuse", "back": "happy", "example": "Nous sommes heureux d'être ensemble.", "exampleEn": "We are happy to be together." },
    { "id": "fr-0406", "front": "la salade", "back": "salad / lettuce", "example": "Il mange une salade verte avec sa viande.", "exampleEn": "He eats a green salad with his meat." },
    { "id": "fr-0407", "front": "la banlieue", "back": "suburb", "example": "Ils habitent en banlieue de Paris.", "exampleEn": "They live in the suburbs of Paris." },
    { "id": "fr-0408", "front": "le cahier", "back": "notebook; exercise book", "example": "Écris la réponse dans ton cahier.", "exampleEn": "Write the answer in your notebook." },
    { "id": "fr-0409", "front": "préparer le repas", "back": "to prepare the meal", "example": "Ma mère prépare le repas à midi.", "exampleEn": "My mother prepares the meal at noon." },
    { "id": "fr-0410", "front": "triste", "back": "sad", "example": "Elle est triste parce que son ami est parti.", "exampleEn": "She is sad because her friend left." },
    { "id": "fr-0411", "front": "la soupe", "back": "soup", "example": "Elle prépare une soupe de légumes pour ce soir.", "exampleEn": "She is making a vegetable soup for tonight." },
    { "id": "fr-0412", "front": "le musée", "back": "museum", "example": "Le musée ouvre à neuf heures.", "exampleEn": "The museum opens at nine o'clock." },
    { "id": "fr-0413", "front": "le stylo", "back": "pen", "example": "Mon stylo ne marche plus.", "exampleEn": "My pen no longer works." },
    { "id": "fr-0414", "front": "faire la vaisselle", "back": "to do the dishes", "example": "C'est mon tour de faire la vaisselle.", "exampleEn": "It is my turn to do the dishes." },
    { "id": "fr-0415", "front": "inquiet / inquiète", "back": "worried", "example": "Je suis inquiet pour les résultats.", "exampleEn": "I am worried about the results." },
    { "id": "fr-0416", "front": "le gâteau", "back": "cake", "example": "On a mangé un gâteau pour son anniversaire.", "exampleEn": "We ate a cake for his birthday." },
    { "id": "fr-0417", "front": "la cathédrale", "back": "cathedral", "example": "La cathédrale est au cœur de la vieille ville.", "exampleEn": "The cathedral is at the heart of the old town." },
    { "id": "fr-0418", "front": "la craie", "back": "chalk", "example": "Le professeur écrit au tableau avec de la craie.", "exampleEn": "The teacher writes on the board with chalk." },
    { "id": "fr-0419", "front": "faire le ménage", "back": "to clean the house", "example": "Elle fait le ménage tous les samedis.", "exampleEn": "She cleans the house every Saturday." },
    { "id": "fr-0420", "front": "stressé(e)", "back": "stressed", "example": "Elle est très stressée avant l'examen.", "exampleEn": "She is very stressed before the exam." },
    { "id": "fr-0421", "front": "la tarte", "back": "tart / pie", "example": "La tarte aux pommes sent très bon.", "exampleEn": "The apple tart smells very good." },
    { "id": "fr-0422", "front": "l'église", "back": "church", "example": "Il y a une vieille église dans ce village.", "exampleEn": "There is an old church in this village." },
    { "id": "fr-0423", "front": "le diplôme", "back": "diploma; degree", "example": "Elle a obtenu son diplôme en juin.", "exampleEn": "She received her diploma in June." },
    { "id": "fr-0424", "front": "faire les courses", "back": "to go grocery shopping", "example": "Je fais les courses au supermarché le vendredi.", "exampleEn": "I go grocery shopping at the supermarket on Fridays." },
    { "id": "fr-0425", "front": "calme", "back": "calm", "example": "Reste calme, tout va bien se passer.", "exampleEn": "Stay calm, everything will be fine." },
    { "id": "fr-0426", "front": "la crème", "back": "cream", "example": "J'ajoute un peu de crème à la sauce.", "exampleEn": "I add a little cream to the sauce." },
    { "id": "fr-0427", "front": "la mairie", "back": "town hall, city hall", "example": "La mairie est fermée le week-end.", "exampleEn": "The town hall is closed on weekends." },
    { "id": "fr-0428", "front": "la bourse", "back": "scholarship; stock exchange", "example": "Il a reçu une bourse pour ses études.", "exampleEn": "He received a scholarship for his studies." },
    { "id": "fr-0429", "front": "la chemise", "back": "shirt (button-up)", "example": "Il porte une chemise blanche pour le travail.", "exampleEn": "He wears a white shirt for work." },
    { "id": "fr-0430", "front": "amoureux / amoureuse", "back": "in love", "example": "Il est amoureux depuis le premier regard.", "exampleEn": "He has been in love since first sight." },
    { "id": "fr-0431", "front": "le yaourt", "back": "yogurt", "example": "Je mange un yaourt nature chaque matin.", "exampleEn": "I eat a plain yogurt every morning." },
    { "id": "fr-0432", "front": "la poste", "back": "post office", "example": "Je vais à la poste envoyer un colis.", "exampleEn": "I'm going to the post office to send a package." },
    { "id": "fr-0433", "front": "la matière", "back": "school subject", "example": "Ma matière préférée est la biologie.", "exampleEn": "My favorite subject is biology." },
    { "id": "fr-0434", "front": "le pantalon", "back": "trousers, pants", "example": "Ce pantalon est trop grand pour moi.", "exampleEn": "These trousers are too big for me." },
    { "id": "fr-0435", "front": "fier / fière", "back": "proud", "example": "Je suis fière de mon travail cette semaine.", "exampleEn": "I am proud of my work this week." },
    { "id": "fr-0436", "front": "la baguette", "back": "baguette / French bread", "example": "Je coupe la baguette en tranches pour le dîner.", "exampleEn": "I slice the baguette for dinner." },
    { "id": "fr-0437", "front": "la pharmacie", "back": "pharmacy, chemist", "example": "La pharmacie est en face de la boulangerie.", "exampleEn": "The pharmacy is across from the bakery." },
    { "id": "fr-0438", "front": "l'université", "back": "university", "example": "Elle est entrée à l'université à dix-huit ans.", "exampleEn": "She entered university at eighteen." },
    { "id": "fr-0439", "front": "la jupe", "back": "skirt", "example": "Elle porte une jupe bleue aujourd'hui.", "exampleEn": "She is wearing a blue skirt today." },
    { "id": "fr-0440", "front": "gêné(e)", "back": "embarrassed", "example": "Il était gêné devant tout le monde.", "exampleEn": "He was embarrassed in front of everyone." },
    { "id": "fr-0441", "front": "le croissant", "back": "croissant", "example": "Elle prend un café et un croissant au bar.", "exampleEn": "She has a coffee and a croissant at the café." },
    { "id": "fr-0442", "front": "le supermarché", "back": "supermarket", "example": "Le supermarché est ouvert jusqu'à vingt heures.", "exampleEn": "The supermarket is open until eight o'clock." },
    { "id": "fr-0443", "front": "le logiciel", "back": "software", "example": "Ce logiciel est très utile au travail.", "exampleEn": "This software is very useful at work." },
    { "id": "fr-0444", "front": "la robe", "back": "dress", "example": "J'achète une robe pour la fête.", "exampleEn": "I am buying a dress for the party." },
    { "id": "fr-0445", "front": "avoir honte", "back": "to be ashamed", "example": "Elle a honte de son erreur.", "exampleEn": "She is ashamed of her mistake." },
    { "id": "fr-0446", "front": "la confiture", "back": "jam", "example": "Je mets de la confiture de fraise sur ma tartine.", "exampleEn": "I spread strawberry jam on my toast." },
    { "id": "fr-0447", "front": "le parc", "back": "park", "example": "Les enfants jouent dans le parc.", "exampleEn": "The children are playing in the park." },
    { "id": "fr-0448", "front": "l'application", "back": "app; application", "example": "J'ai téléchargé une nouvelle application.", "exampleEn": "I downloaded a new app." },
    { "id": "fr-0449", "front": "le manteau", "back": "coat, overcoat", "example": "Prends ton manteau, il fait froid.", "exampleEn": "Take your coat, it is cold." },
    { "id": "fr-0450", "front": "s'ennuyer", "back": "to be bored", "example": "Il s'ennuie quand il est seul à la maison.", "exampleEn": "He gets bored when he is alone at home." },
    { "id": "fr-0451", "front": "le miel", "back": "honey", "example": "Il met du miel dans son thé chaud.", "exampleEn": "He puts honey in his hot tea." },
    { "id": "fr-0452", "front": "le jardin public", "back": "public garden", "example": "On se promène dans le jardin public.", "exampleEn": "We walk in the public garden." },
    { "id": "fr-0453", "front": "le mot de passe", "back": "password", "example": "N'oublie pas ton mot de passe.", "exampleEn": "Don't forget your password." },
    { "id": "fr-0454", "front": "la veste", "back": "jacket, blazer", "example": "Il met sa veste avant de sortir.", "exampleEn": "He puts on his jacket before going out." },
    { "id": "fr-0455", "front": "l'orage", "back": "the thunderstorm", "example": "Un gros orage arrive ce soir.", "exampleEn": "A big thunderstorm is coming this evening." },
    { "id": "fr-0456", "front": "le jus d'orange", "back": "orange juice", "example": "Je bois un grand verre de jus d'orange.", "exampleEn": "I drink a large glass of orange juice." },
    { "id": "fr-0457", "front": "la piscine", "back": "swimming pool", "example": "La piscine municipale est gratuite le mardi.", "exampleEn": "The municipal swimming pool is free on Tuesdays." },
    { "id": "fr-0458", "front": "le fichier", "back": "file", "example": "Enregistre le fichier avant de fermer.", "exampleEn": "Save the file before closing." },
    { "id": "fr-0459", "front": "le pull", "back": "sweater, jumper", "example": "Ce pull en laine est très chaud.", "exampleEn": "This wool sweater is very warm." },
    { "id": "fr-0460", "front": "le nuage", "back": "the cloud", "example": "Le ciel est couvert de nuages gris.", "exampleEn": "The sky is covered with grey clouds." },
    { "id": "fr-0461", "front": "la bière", "back": "beer", "example": "Il commande une bière bien fraîche.", "exampleEn": "He orders a very cold beer." },
    { "id": "fr-0462", "front": "le stade", "back": "stadium", "example": "Le match se joue au stade ce soir.", "exampleEn": "The match is played at the stadium tonight." },
    { "id": "fr-0463", "front": "télécharger", "back": "to download", "example": "Il télécharge le document depuis le site.", "exampleEn": "He downloads the document from the website." },
    { "id": "fr-0464", "front": "le t-shirt", "back": "T-shirt", "example": "J'aime ce t-shirt rouge.", "exampleEn": "I like this red T-shirt." },
    { "id": "fr-0465", "front": "le tonnerre", "back": "thunder", "example": "Le tonnerre m'a réveillé cette nuit.", "exampleEn": "The thunder woke me up last night." },
    { "id": "fr-0466", "front": "l'eau minérale", "back": "mineral water", "example": "Vous désirez de l'eau minérale ou du robinet ?", "exampleEn": "Would you like mineral water or tap water?" },
    { "id": "fr-0467", "front": "la frontière", "back": "border, frontier", "example": "On traverse la frontière en voiture.", "exampleEn": "We cross the border by car." },
    { "id": "fr-0468", "front": "le réseau", "back": "network", "example": "Le réseau est lent ce matin.", "exampleEn": "The network is slow this morning." },
    { "id": "fr-0469", "front": "les chaussures", "back": "shoes", "example": "Mes chaussures neuves me font mal.", "exampleEn": "My new shoes hurt." },
    { "id": "fr-0470", "front": "l'éclair", "back": "lightning", "example": "Un éclair a traversé le ciel sombre.", "exampleEn": "A bolt of lightning crossed the dark sky." },
    { "id": "fr-0471", "front": "la poêle", "back": "frying pan", "example": "Chauffe la poêle avant d'y mettre la viande.", "exampleEn": "Heat the frying pan before putting the meat in." },
    { "id": "fr-0472", "front": "la sortie", "back": "exit", "example": "La sortie de secours est là-bas.", "exampleEn": "The emergency exit is over there." },
    { "id": "fr-0473", "front": "internet", "back": "the internet", "example": "Je cherche l'information sur internet.", "exampleEn": "I'm looking for information on the internet." },
    { "id": "fr-0474", "front": "les chaussettes", "back": "socks", "example": "Il cherche ses chaussettes dans l'armoire.", "exampleEn": "He is looking for his socks in the wardrobe." },
    { "id": "fr-0475", "front": "la brume", "back": "mist / fog", "example": "La brume couvre la montagne ce matin.", "exampleEn": "The mist covers the mountain this morning." },
    { "id": "fr-0476", "front": "la casserole", "back": "saucepan / pot", "example": "Fais bouillir l'eau dans la casserole.", "exampleEn": "Boil the water in the saucepan." },
    { "id": "fr-0477", "front": "l'office de tourisme", "back": "tourist office", "example": "L'office de tourisme donne des cartes gratuites.", "exampleEn": "The tourist office gives out free maps." },
    { "id": "fr-0478", "front": "le courriel", "back": "email", "example": "J'ai reçu un courriel important ce matin.", "exampleEn": "I received an important email this morning." },
    { "id": "fr-0479", "front": "le chapeau", "back": "hat", "example": "Elle met un chapeau quand il fait soleil.", "exampleEn": "She wears a hat when it is sunny." },
    { "id": "fr-0480", "front": "la chaleur", "back": "heat / warmth", "example": "La chaleur de l'été est difficile à supporter.", "exampleEn": "The summer heat is hard to bear." },
    { "id": "fr-0481", "front": "le four", "back": "oven", "example": "Préchauffe le four à cent quatre-vingts degrés.", "exampleEn": "Preheat the oven to one hundred and eighty degrees." },
    { "id": "fr-0482", "front": "le guide", "back": "guide, guidebook", "example": "Notre guide connaît très bien la ville.", "exampleEn": "Our guide knows the city very well." },
    { "id": "fr-0483", "front": "l'écran", "back": "screen", "example": "Mon écran est trop petit pour ce travail.", "exampleEn": "My screen is too small for this work." },
    { "id": "fr-0484", "front": "l'écharpe", "back": "scarf", "example": "N'oublie pas ton écharpe, il fait froid.", "exampleEn": "Don't forget your scarf, it is cold." },
    { "id": "fr-0485", "front": "la tempête", "back": "the storm", "example": "La tempête a cassé plusieurs arbres.", "exampleEn": "The storm broke several trees." },
    { "id": "fr-0486", "front": "le couteau", "back": "knife", "example": "Ce couteau est très tranchant, sois prudent.", "exampleEn": "This knife is very sharp, be careful." },
    { "id": "fr-0487", "front": "la visite guidée", "back": "guided tour", "example": "La visite guidée dure deux heures.", "exampleEn": "The guided tour lasts two hours." },
    { "id": "fr-0488", "front": "le clavier", "back": "keyboard", "example": "Il tape vite sur son clavier.", "exampleEn": "He types quickly on his keyboard." },
    { "id": "fr-0489", "front": "les gants", "back": "gloves", "example": "Je mets mes gants pour sortir en hiver.", "exampleEn": "I put on my gloves to go out in winter." },
    { "id": "fr-0490", "front": "le gel", "back": "frost / freezing", "example": "Le gel a abîmé les fleurs du jardin.", "exampleEn": "The frost damaged the garden flowers." },
    { "id": "fr-0491", "front": "la fourchette", "back": "fork", "example": "La fourchette se pose à gauche de l'assiette.", "exampleEn": "The fork goes on the left side of the plate." },
    { "id": "fr-0492", "front": "le monument", "back": "monument, landmark", "example": "Ce monument est très célèbre.", "exampleEn": "This monument is very famous." },
    { "id": "fr-0493", "front": "la souris", "back": "mouse (computer)", "example": "La souris de mon ordinateur ne fonctionne plus.", "exampleEn": "My computer mouse no longer works." },
    { "id": "fr-0494", "front": "la ceinture", "back": "belt", "example": "Ce pantalon a besoin d'une ceinture.", "exampleEn": "These trousers need a belt." },
    { "id": "fr-0495", "front": "ensoleillé(e)", "back": "sunny", "example": "C'est une journée ensoleillée et chaude.", "exampleEn": "It is a sunny and warm day." },
    { "id": "fr-0496", "front": "la cuillère", "back": "spoon", "example": "Il prend une cuillère de soupe doucement.", "exampleEn": "He takes a spoonful of soup carefully." },
    { "id": "fr-0497", "front": "la tour", "back": "tower", "example": "On peut monter en haut de la tour.", "exampleEn": "You can go to the top of the tower." },
    { "id": "fr-0498", "front": "imprimer", "back": "to print", "example": "Peux-tu imprimer ce document pour moi ?", "exampleEn": "Can you print this document for me?" },
    { "id": "fr-0499", "front": "le sac à main", "back": "handbag, purse", "example": "Elle pose son sac à main sur la table.", "exampleEn": "She puts her handbag on the table." },
    { "id": "fr-0500", "front": "nuageux / nuageuse", "back": "cloudy", "example": "Le temps est nuageux mais sans pluie.", "exampleEn": "The weather is cloudy but without rain." }
  ]
};
if (typeof module !== "undefined" && module.exports) module.exports = deck;
if (typeof window !== "undefined") { var WL = (window.WL = window.WL || {}); (WL.__decks = WL.__decks || []).push(deck); }
