// Agora deck. Free.
var deck = {
  "id": "bundled:italian",
  "name": "Italian 500",
  "lang": "it",
  "cards": [
    { "id": "it-0001", "front": "ciao", "back": "hi / bye", "example": "Ciao, come stai?", "exampleEn": "Hi, how are you?" },
    { "id": "it-0002", "front": "buongiorno", "back": "good morning", "example": "Buongiorno, signora!", "exampleEn": "Good morning, ma'am!" },
    { "id": "it-0003", "front": "buonasera", "back": "good evening", "example": "Buonasera a tutti.", "exampleEn": "Good evening, everyone." },
    { "id": "it-0004", "front": "buonanotte", "back": "good night", "example": "Buonanotte, a domani.", "exampleEn": "Good night, see you tomorrow." },
    { "id": "it-0005", "front": "arrivederci", "back": "goodbye", "example": "Arrivederci, dottore.", "exampleEn": "Goodbye, doctor." },
    { "id": "it-0006", "front": "grazie", "back": "thank you", "example": "Grazie mille per l'aiuto.", "exampleEn": "Thank you so much for your help." },
    { "id": "it-0007", "front": "prego", "back": "you're welcome", "example": "Prego, si accomodi.", "exampleEn": "You're welcome, please have a seat." },
    { "id": "it-0008", "front": "per favore", "back": "please", "example": "Un caffè, per favore.", "exampleEn": "A coffee, please." },
    { "id": "it-0009", "front": "scusa", "back": "sorry / excuse me (informal)", "example": "Scusa, non ti ho sentito.", "exampleEn": "Sorry, I didn't hear you." },
    { "id": "it-0010", "front": "scusi", "back": "excuse me (formal)", "example": "Scusi, dov'è la stazione?", "exampleEn": "Excuse me, where is the station?" },
    { "id": "it-0011", "front": "sì", "back": "yes", "example": "Sì, sono d'accordo.", "exampleEn": "Yes, I agree." },
    { "id": "it-0012", "front": "no", "back": "no", "example": "No, non posso venire.", "exampleEn": "No, I can't come." },
    { "id": "it-0013", "front": "zero", "back": "zero", "example": "Ho zero euro in tasca.", "exampleEn": "I have zero euros in my pocket." },
    { "id": "it-0014", "front": "uno", "back": "one", "example": "Voglio solo un caffè.", "exampleEn": "I just want one coffee." },
    { "id": "it-0015", "front": "due", "back": "two", "example": "Ho due fratelli.", "exampleEn": "I have two brothers." },
    { "id": "it-0016", "front": "tre", "back": "three", "example": "Sono le tre del pomeriggio.", "exampleEn": "It's three in the afternoon." },
    { "id": "it-0017", "front": "quattro", "back": "four", "example": "Abbiamo quattro sedie.", "exampleEn": "We have four chairs." },
    { "id": "it-0018", "front": "cinque", "back": "five", "example": "Il treno parte alle cinque.", "exampleEn": "The train leaves at five." },
    { "id": "it-0019", "front": "sei", "back": "six", "example": "Ci sono sei uova nel frigo.", "exampleEn": "There are six eggs in the fridge." },
    { "id": "it-0020", "front": "sette", "back": "seven", "example": "La settimana ha sette giorni.", "exampleEn": "A week has seven days." },
    { "id": "it-0021", "front": "otto", "back": "eight", "example": "Lavoro otto ore al giorno.", "exampleEn": "I work eight hours a day." },
    { "id": "it-0022", "front": "nove", "back": "nine", "example": "Mio figlio ha nove anni.", "exampleEn": "My son is nine years old." },
    { "id": "it-0023", "front": "dieci", "back": "ten", "example": "Costa dieci euro.", "exampleEn": "It costs ten euros." },
    { "id": "it-0024", "front": "undici", "back": "eleven", "example": "Ci vediamo alle undici.", "exampleEn": "See you at eleven." },
    { "id": "it-0025", "front": "dodici", "back": "twelve", "example": "Un anno ha dodici mesi.", "exampleEn": "A year has twelve months." },
    { "id": "it-0026", "front": "tredici", "back": "thirteen", "example": "Ho tredici messaggi nuovi.", "exampleEn": "I have thirteen new messages." },
    { "id": "it-0027", "front": "quattordici", "back": "fourteen", "example": "La festa è il quattordici.", "exampleEn": "The party is on the fourteenth." },
    { "id": "it-0028", "front": "quindici", "back": "fifteen", "example": "Arrivo tra quindici minuti.", "exampleEn": "I'll be there in fifteen minutes." },
    { "id": "it-0029", "front": "sedici", "back": "sixteen", "example": "Mia sorella ha sedici anni.", "exampleEn": "My sister is sixteen years old." },
    { "id": "it-0030", "front": "diciassette", "back": "seventeen", "example": "Sono nato il diciassette marzo.", "exampleEn": "I was born on the seventeenth of March." },
    { "id": "it-0031", "front": "diciotto", "back": "eighteen", "example": "A diciotto anni sei maggiorenne.", "exampleEn": "At eighteen you're an adult." },
    { "id": "it-0032", "front": "diciannove", "back": "nineteen", "example": "Ho diciannove libri da leggere.", "exampleEn": "I have nineteen books to read." },
    { "id": "it-0033", "front": "venti", "back": "twenty", "example": "Ci sono venti studenti in classe.", "exampleEn": "There are twenty students in the class." },
    { "id": "it-0034", "front": "trenta", "back": "thirty", "example": "Mio padre ha trenta dipendenti.", "exampleEn": "My father has thirty employees." },
    { "id": "it-0035", "front": "quaranta", "back": "forty", "example": "La strada è lunga quaranta chilometri.", "exampleEn": "The road is forty kilometers long." },
    { "id": "it-0036", "front": "cinquanta", "back": "fifty", "example": "Ho cinquanta euro nel portafoglio.", "exampleEn": "I have fifty euros in my wallet." },
    { "id": "it-0037", "front": "sessanta", "back": "sixty", "example": "Un'ora ha sessanta minuti.", "exampleEn": "An hour has sixty minutes." },
    { "id": "it-0038", "front": "settanta", "back": "seventy", "example": "Mia nonna ha settanta anni.", "exampleEn": "My grandmother is seventy years old." },
    { "id": "it-0039", "front": "ottanta", "back": "eighty", "example": "Il film dura ottanta minuti.", "exampleEn": "The film is eighty minutes long." },
    { "id": "it-0040", "front": "novanta", "back": "ninety", "example": "Ho corso per novanta minuti.", "exampleEn": "I ran for ninety minutes." },
    { "id": "it-0041", "front": "cento", "back": "hundred", "example": "Questo libro ha cento pagine.", "exampleEn": "This book has a hundred pages." },
    { "id": "it-0042", "front": "mille", "back": "thousand", "example": "Ho speso mille euro.", "exampleEn": "I spent a thousand euros." },
    { "id": "it-0043", "front": "lunedì", "back": "Monday", "example": "Lunedì comincia la scuola.", "exampleEn": "School starts on Monday." },
    { "id": "it-0044", "front": "martedì", "back": "Tuesday", "example": "Martedì ho una riunione.", "exampleEn": "I have a meeting on Tuesday." },
    { "id": "it-0045", "front": "mercoledì", "back": "Wednesday", "example": "Mercoledì vado dal medico.", "exampleEn": "I'm going to the doctor on Wednesday." },
    { "id": "it-0046", "front": "giovedì", "back": "Thursday", "example": "Giovedì sera usciamo insieme.", "exampleEn": "Thursday evening we're going out together." },
    { "id": "it-0047", "front": "venerdì", "back": "Friday", "example": "Venerdì finisco di lavorare presto.", "exampleEn": "On Friday I finish work early." },
    { "id": "it-0048", "front": "sabato", "back": "Saturday", "example": "Il sabato dormo fino a tardi.", "exampleEn": "On Saturdays I sleep in." },
    { "id": "it-0049", "front": "domenica", "back": "Sunday", "example": "La domenica andiamo in chiesa.", "exampleEn": "On Sundays we go to church." },
    { "id": "it-0050", "front": "gennaio", "back": "January", "example": "A gennaio fa molto freddo.", "exampleEn": "In January it's very cold." },
    { "id": "it-0051", "front": "febbraio", "back": "February", "example": "Febbraio è il mese più corto.", "exampleEn": "February is the shortest month." },
    { "id": "it-0052", "front": "marzo", "back": "March", "example": "In marzo arriva la primavera.", "exampleEn": "Spring arrives in March." },
    { "id": "it-0053", "front": "aprile", "back": "April", "example": "Ad aprile piove spesso.", "exampleEn": "It often rains in April." },
    { "id": "it-0054", "front": "maggio", "back": "May", "example": "A maggio i fiori sbocciano.", "exampleEn": "In May the flowers bloom." },
    { "id": "it-0055", "front": "giugno", "back": "June", "example": "A giugno finisce la scuola.", "exampleEn": "School ends in June." },
    { "id": "it-0056", "front": "luglio", "back": "July", "example": "A luglio andiamo al mare.", "exampleEn": "In July we go to the seaside." },
    { "id": "it-0057", "front": "agosto", "back": "August", "example": "Ad agosto la città è vuota.", "exampleEn": "In August the city is empty." },
    { "id": "it-0058", "front": "settembre", "back": "September", "example": "A settembre ricomincia il lavoro.", "exampleEn": "Work starts up again in September." },
    { "id": "it-0059", "front": "ottobre", "back": "October", "example": "In ottobre cadono le foglie.", "exampleEn": "In October the leaves fall." },
    { "id": "it-0060", "front": "novembre", "back": "November", "example": "A novembre fa già freddo.", "exampleEn": "In November it's already cold." },
    { "id": "it-0061", "front": "dicembre", "back": "December", "example": "A dicembre festeggiamo il Natale.", "exampleEn": "In December we celebrate Christmas." },
    { "id": "it-0062", "front": "oggi", "back": "today", "example": "Oggi è una bella giornata.", "exampleEn": "Today is a beautiful day." },
    { "id": "it-0063", "front": "ieri", "back": "yesterday", "example": "Ieri sono andato al cinema.", "exampleEn": "Yesterday I went to the movies." },
    { "id": "it-0064", "front": "domani", "back": "tomorrow", "example": "Domani parto per Roma.", "exampleEn": "Tomorrow I'm leaving for Rome." },
    { "id": "it-0065", "front": "adesso", "back": "now", "example": "Adesso devo andare.", "exampleEn": "I have to go now." },
    { "id": "it-0066", "front": "sempre", "back": "always", "example": "Bevo sempre un caffè la mattina.", "exampleEn": "I always have a coffee in the morning." },
    { "id": "it-0067", "front": "mai", "back": "never", "example": "Non mangio mai la carne.", "exampleEn": "I never eat meat." },
    { "id": "it-0068", "front": "presto", "back": "early / soon", "example": "Mi alzo presto la mattina.", "exampleEn": "I get up early in the morning." },
    { "id": "it-0069", "front": "tardi", "back": "late", "example": "È tardi, andiamo a dormire.", "exampleEn": "It's late, let's go to sleep." },
    { "id": "it-0070", "front": "l'anno", "back": "the year (m)", "example": "L'anno prossimo cambio lavoro.", "exampleEn": "Next year I'm changing jobs." },
    { "id": "it-0071", "front": "il mese", "back": "the month (m)", "example": "Questo mese ho risparmiato poco.", "exampleEn": "This month I haven't saved much." },
    { "id": "it-0072", "front": "il giorno", "back": "the day (m)", "example": "Ogni giorno faccio una passeggiata.", "exampleEn": "Every day I go for a walk." },
    { "id": "it-0073", "front": "la notte", "back": "the night (f)", "example": "Stanotte ho dormito male.", "exampleEn": "Last night I slept badly." },
    { "id": "it-0074", "front": "l'ora", "back": "the hour (f)", "example": "Che ora è adesso?", "exampleEn": "What time is it now?" },
    { "id": "it-0075", "front": "chi", "back": "who", "example": "Chi è quella ragazza?", "exampleEn": "Who is that girl?" },
    { "id": "it-0076", "front": "che cosa", "back": "what", "example": "Che cosa vuoi mangiare?", "exampleEn": "What do you want to eat?" },
    { "id": "it-0077", "front": "dove", "back": "where", "example": "Dove abiti?", "exampleEn": "Where do you live?" },
    { "id": "it-0078", "front": "quando", "back": "when", "example": "Quando arriva il treno?", "exampleEn": "When does the train arrive?" },
    { "id": "it-0079", "front": "perché", "back": "why / because", "example": "Perché studi l'italiano?", "exampleEn": "Why are you studying Italian?" },
    { "id": "it-0080", "front": "come", "back": "how", "example": "Come ti chiami?", "exampleEn": "What's your name?" },
    { "id": "it-0081", "front": "quanto", "back": "how much", "example": "Quanto costa questo?", "exampleEn": "How much does this cost?" },
    { "id": "it-0082", "front": "quale", "back": "which", "example": "Quale vino preferisci?", "exampleEn": "Which wine do you prefer?" },
    { "id": "it-0083", "front": "io", "back": "I", "example": "Io vengo con te.", "exampleEn": "I'm coming with you." },
    { "id": "it-0084", "front": "tu", "back": "you (informal)", "example": "Tu cosa ne pensi?", "exampleEn": "What do you think about it?" },
    { "id": "it-0085", "front": "lui", "back": "he", "example": "Lui lavora in banca.", "exampleEn": "He works at a bank." },
    { "id": "it-0086", "front": "lei", "back": "she / you (formal)", "example": "Lei è molto gentile.", "exampleEn": "She is very kind." },
    { "id": "it-0087", "front": "noi", "back": "we", "example": "Noi andiamo al mare.", "exampleEn": "We're going to the seaside." },
    { "id": "it-0088", "front": "voi", "back": "you (plural)", "example": "Voi venite alla festa?", "exampleEn": "Are you coming to the party?" },
    { "id": "it-0089", "front": "loro", "back": "they", "example": "Loro abitano a Milano.", "exampleEn": "They live in Milan." },
    { "id": "it-0090", "front": "mi", "back": "me / to me", "example": "Mi piace la pizza.", "exampleEn": "I like pizza." },
    { "id": "it-0091", "front": "questo", "back": "this", "example": "Questo è il mio amico.", "exampleEn": "This is my friend." },
    { "id": "it-0092", "front": "quello", "back": "that", "example": "Quello è troppo caro.", "exampleEn": "That one is too expensive." },
    { "id": "it-0093", "front": "niente", "back": "nothing", "example": "Non ho capito niente.", "exampleEn": "I didn't understand anything." },
    { "id": "it-0094", "front": "essere", "back": "to be", "example": "Voglio essere felice.", "exampleEn": "I want to be happy." },
    { "id": "it-0095", "front": "avere", "back": "to have", "example": "Vorrei avere più tempo.", "exampleEn": "I'd like to have more time." },
    { "id": "it-0096", "front": "fare", "back": "to do / make", "example": "Cosa vuoi fare oggi?", "exampleEn": "What do you want to do today?" },
    { "id": "it-0097", "front": "andare", "back": "to go", "example": "Devo andare a casa.", "exampleEn": "I need to go home." },
    { "id": "it-0098", "front": "venire", "back": "to come", "example": "Puoi venire alle otto?", "exampleEn": "Can you come at eight?" },
    { "id": "it-0099", "front": "dire", "back": "to say", "example": "Devo dire una cosa.", "exampleEn": "I need to say something." },
    { "id": "it-0100", "front": "potere", "back": "to be able to", "example": "Non posso uscire stasera.", "exampleEn": "I can't go out tonight." },
    { "id": "it-0101", "front": "volere", "back": "to want", "example": "Voglio un gelato.", "exampleEn": "I want an ice cream." },
    { "id": "it-0102", "front": "dovere", "back": "to have to", "example": "Devo studiare per l'esame.", "exampleEn": "I have to study for the exam." },
    { "id": "it-0103", "front": "sapere", "back": "to know (a fact)", "example": "Non so dove sia.", "exampleEn": "I don't know where it is." },
    { "id": "it-0104", "front": "conoscere", "back": "to know (a person)", "example": "Vorrei conoscere i tuoi amici.", "exampleEn": "I'd like to meet your friends." },
    { "id": "it-0105", "front": "vedere", "back": "to see", "example": "Non riesco a vedere bene.", "exampleEn": "I can't see well." },
    { "id": "it-0106", "front": "sentire", "back": "to hear / feel", "example": "Non ti sento, parla più forte.", "exampleEn": "I can't hear you, speak louder." },
    { "id": "it-0107", "front": "parlare", "back": "to speak", "example": "Parli italiano molto bene.", "exampleEn": "You speak Italian very well." },
    { "id": "it-0108", "front": "mangiare", "back": "to eat", "example": "Stasera vorrei mangiare il pesce.", "exampleEn": "Tonight I'd like to eat fish." },
    { "id": "it-0109", "front": "bere", "back": "to drink", "example": "Vuoi bere qualcosa?", "exampleEn": "Would you like something to drink?" },
    { "id": "it-0110", "front": "dormire", "back": "to sleep", "example": "Voglio dormire fino a tardi.", "exampleEn": "I want to sleep in." },
    { "id": "it-0111", "front": "lavorare", "back": "to work", "example": "Devo lavorare fino a sera.", "exampleEn": "I have to work until evening." },
    { "id": "it-0112", "front": "studiare", "back": "to study", "example": "Mi piace studiare le lingue.", "exampleEn": "I enjoy studying languages." },
    { "id": "it-0113", "front": "leggere", "back": "to read", "example": "Adoro leggere prima di dormire.", "exampleEn": "I love reading before bed." },
    { "id": "it-0114", "front": "scrivere", "back": "to write", "example": "Devo scrivere una lettera.", "exampleEn": "I need to write a letter." },
    { "id": "it-0115", "front": "comprare", "back": "to buy", "example": "Voglio comprare un regalo.", "exampleEn": "I want to buy a gift." },
    { "id": "it-0116", "front": "pagare", "back": "to pay", "example": "Posso pagare con la carta?", "exampleEn": "Can I pay by card?" },
    { "id": "it-0117", "front": "aprire", "back": "to open", "example": "Puoi aprire la finestra?", "exampleEn": "Can you open the window?" },
    { "id": "it-0118", "front": "chiudere", "back": "to close", "example": "Chiudi la porta, per favore.", "exampleEn": "Close the door, please." },
    { "id": "it-0119", "front": "dare", "back": "to give", "example": "Mi puoi dare una mano?", "exampleEn": "Can you give me a hand?" },
    { "id": "it-0120", "front": "prendere", "back": "to take", "example": "Prendo il treno delle nove.", "exampleEn": "I'm taking the nine o'clock train." },
    { "id": "it-0121", "front": "trovare", "back": "to find", "example": "Non riesco a trovare le scarpe.", "exampleEn": "I can't find my shoes." },
    { "id": "it-0122", "front": "pensare", "back": "to think", "example": "Penso che tu abbia ragione.", "exampleEn": "I think you're right." },
    { "id": "it-0123", "front": "capire", "back": "to understand", "example": "Non riesco a capire il problema.", "exampleEn": "I can't understand the problem." },
    { "id": "it-0124", "front": "aspettare", "back": "to wait", "example": "Ti aspetto davanti al bar.", "exampleEn": "I'll wait for you in front of the bar." },
    { "id": "it-0125", "front": "chiamare", "back": "to call", "example": "Ti chiamo domani mattina.", "exampleEn": "I'll call you tomorrow morning." },
    { "id": "it-0126", "front": "partire", "back": "to leave / depart", "example": "Devo partire alle sei.", "exampleEn": "I have to leave at six." },
    { "id": "it-0127", "front": "arrivare", "back": "to arrive", "example": "Il treno deve arrivare alle dieci.", "exampleEn": "The train is due to arrive at ten." },
    { "id": "it-0128", "front": "la famiglia", "back": "the family (f)", "example": "La mia famiglia è numerosa.", "exampleEn": "My family is large." },
    { "id": "it-0129", "front": "la madre", "back": "the mother (f)", "example": "Mia madre cucina benissimo.", "exampleEn": "My mother cooks very well." },
    { "id": "it-0130", "front": "il padre", "back": "the father (m)", "example": "Mio padre lavora in ufficio.", "exampleEn": "My father works in an office." },
    { "id": "it-0131", "front": "il figlio", "back": "the son (m)", "example": "Suo figlio studia medicina.", "exampleEn": "His son is studying medicine." },
    { "id": "it-0132", "front": "la figlia", "back": "the daughter (f)", "example": "La loro figlia ha due anni.", "exampleEn": "Their daughter is two years old." },
    { "id": "it-0133", "front": "il fratello", "back": "the brother (m)", "example": "Mio fratello vive a Torino.", "exampleEn": "My brother lives in Turin." },
    { "id": "it-0134", "front": "la sorella", "back": "the sister (f)", "example": "Mia sorella è più giovane di me.", "exampleEn": "My sister is younger than me." },
    { "id": "it-0135", "front": "il nonno", "back": "the grandfather (m)", "example": "Il nonno racconta belle storie.", "exampleEn": "Grandpa tells great stories." },
    { "id": "it-0136", "front": "la nonna", "back": "the grandmother (f)", "example": "La nonna fa una torta buonissima.", "exampleEn": "Grandma makes a delicious cake." },
    { "id": "it-0137", "front": "l'amico", "back": "the friend (m)", "example": "Vado al cinema con un amico.", "exampleEn": "I'm going to the movies with a friend." },
    { "id": "it-0138", "front": "il cibo", "back": "the food (m)", "example": "Il cibo italiano è famoso nel mondo.", "exampleEn": "Italian food is famous around the world." },
    { "id": "it-0139", "front": "l'acqua", "back": "the water (f)", "example": "Vorrei un bicchiere d'acqua.", "exampleEn": "I'd like a glass of water." },
    { "id": "it-0140", "front": "il caffè", "back": "the coffee (m)", "example": "Bevo il caffè ogni mattina.", "exampleEn": "I drink coffee every morning." },
    { "id": "it-0141", "front": "il pane", "back": "the bread (m)", "example": "Compro il pane fresco ogni giorno.", "exampleEn": "I buy fresh bread every day." },
    { "id": "it-0142", "front": "la pasta", "back": "the pasta (f)", "example": "Stasera mangiamo la pasta.", "exampleEn": "Tonight we're having pasta." },
    { "id": "it-0143", "front": "la pizza", "back": "the pizza (f)", "example": "La pizza margherita è la mia preferita.", "exampleEn": "Margherita pizza is my favorite." },
    { "id": "it-0144", "front": "la carne", "back": "the meat (f)", "example": "Non mangio molta carne.", "exampleEn": "I don't eat much meat." },
    { "id": "it-0145", "front": "il pesce", "back": "the fish (m)", "example": "Il pesce è freschissimo qui.", "exampleEn": "The fish is very fresh here." },
    { "id": "it-0146", "front": "la frutta", "back": "the fruit (f)", "example": "Mangio la frutta ogni giorno.", "exampleEn": "I eat fruit every day." },
    { "id": "it-0147", "front": "la verdura", "back": "the vegetables (f)", "example": "Devo comprare la verdura.", "exampleEn": "I need to buy some vegetables." },
    { "id": "it-0148", "front": "lo zucchero", "back": "the sugar (m)", "example": "Vuoi lo zucchero nel caffè?", "exampleEn": "Do you want sugar in your coffee?" },
    { "id": "it-0149", "front": "la casa", "back": "the house (f)", "example": "La mia casa è vicino al parco.", "exampleEn": "My house is near the park." },
    { "id": "it-0150", "front": "la porta", "back": "the door (f)", "example": "Chiudi la porta, fa freddo.", "exampleEn": "Close the door, it's cold." },
    { "id": "it-0151", "front": "la finestra", "back": "the window (f)", "example": "Apri la finestra, per favore.", "exampleEn": "Open the window, please." },
    { "id": "it-0152", "front": "il tavolo", "back": "the table (m)", "example": "Metti i piatti sul tavolo.", "exampleEn": "Put the plates on the table." },
    { "id": "it-0153", "front": "la sedia", "back": "the chair (f)", "example": "Questa sedia è molto comoda.", "exampleEn": "This chair is very comfortable." },
    { "id": "it-0154", "front": "il letto", "back": "the bed (m)", "example": "Vado a letto presto stasera.", "exampleEn": "I'm going to bed early tonight." },
    { "id": "it-0155", "front": "la cucina", "back": "the kitchen (f)", "example": "La cucina è la stanza più grande.", "exampleEn": "The kitchen is the largest room." },
    { "id": "it-0156", "front": "il bagno", "back": "the bathroom (m)", "example": "Dov'è il bagno, per favore?", "exampleEn": "Where is the bathroom, please?" },
    { "id": "it-0157", "front": "il telefono", "back": "the telephone (m)", "example": "Il telefono sta squillando.", "exampleEn": "The phone is ringing." },
    { "id": "it-0158", "front": "la testa", "back": "the head (f)", "example": "Mi fa male la testa.", "exampleEn": "I have a headache." },
    { "id": "it-0159", "front": "la mano", "back": "the hand (f)", "example": "Dammi la mano per attraversare.", "exampleEn": "Give me your hand to cross." },
    { "id": "it-0160", "front": "l'occhio", "back": "the eye (m)", "example": "Ho qualcosa nell'occhio.", "exampleEn": "I have something in my eye." },
    { "id": "it-0161", "front": "la bocca", "back": "the mouth (f)", "example": "Apri la bocca, dice il dentista.", "exampleEn": "Open your mouth, says the dentist." },
    { "id": "it-0162", "front": "il naso", "back": "the nose (m)", "example": "Ho il naso chiuso oggi.", "exampleEn": "My nose is stuffy today." },
    { "id": "it-0163", "front": "il piede", "back": "the foot (m)", "example": "Mi fa male il piede destro.", "exampleEn": "My right foot hurts." },
    { "id": "it-0164", "front": "la gamba", "back": "the leg (f)", "example": "Si è rotta una gamba.", "exampleEn": "She broke her leg." },
    { "id": "it-0165", "front": "i capelli", "back": "the hair (m, pl)", "example": "Ha i capelli lunghi e neri.", "exampleEn": "She has long black hair." },
    { "id": "it-0166", "front": "la città", "back": "the city (f)", "example": "Roma è una città bellissima.", "exampleEn": "Rome is a beautiful city." },
    { "id": "it-0167", "front": "il paese", "back": "the village / country (m)", "example": "Vivo in un piccolo paese.", "exampleEn": "I live in a small town." },
    { "id": "it-0168", "front": "la strada", "back": "the street / road (f)", "example": "La strada è chiusa per lavori.", "exampleEn": "The road is closed for construction." },
    { "id": "it-0169", "front": "la scuola", "back": "the school (f)", "example": "I bambini vanno a scuola a piedi.", "exampleEn": "The children walk to school." },
    { "id": "it-0170", "front": "l'ospedale", "back": "the hospital (m)", "example": "L'ospedale è vicino alla stazione.", "exampleEn": "The hospital is near the station." },
    { "id": "it-0171", "front": "il negozio", "back": "the shop (m)", "example": "Il negozio apre alle nove.", "exampleEn": "The shop opens at nine." },
    { "id": "it-0172", "front": "il mercato", "back": "the market (m)", "example": "Vado al mercato il sabato.", "exampleEn": "I go to the market on Saturdays." },
    { "id": "it-0173", "front": "il ristorante", "back": "the restaurant (m)", "example": "Conosco un buon ristorante qui.", "exampleEn": "I know a good restaurant here." },
    { "id": "it-0174", "front": "la banca", "back": "the bank (f)", "example": "La banca chiude all'una.", "exampleEn": "The bank closes at one." },
    { "id": "it-0175", "front": "la stazione", "back": "the station (f)", "example": "Ci vediamo alla stazione.", "exampleEn": "We'll meet at the station." },
    { "id": "it-0176", "front": "il lavoro", "back": "the work / job (m)", "example": "Cerco un nuovo lavoro.", "exampleEn": "I'm looking for a new job." },
    { "id": "it-0177", "front": "il libro", "back": "the book (m)", "example": "Sto leggendo un bel libro.", "exampleEn": "I'm reading a good book." },
    { "id": "it-0178", "front": "i soldi", "back": "the money (m, pl)", "example": "Non ho soldi con me.", "exampleEn": "I don't have any money on me." },
    { "id": "it-0179", "front": "il problema", "back": "the problem (m)", "example": "Abbiamo un piccolo problema.", "exampleEn": "We have a small problem." },
    { "id": "it-0180", "front": "il tempo", "back": "the time / weather (m)", "example": "Non ho tempo oggi.", "exampleEn": "I don't have time today." },
    { "id": "it-0181", "front": "la cosa", "back": "the thing (f)", "example": "Devo dirti una cosa importante.", "exampleEn": "I need to tell you something important." },
    { "id": "it-0182", "front": "il regalo", "back": "the gift (m)", "example": "Ti ho comprato un regalo.", "exampleEn": "I bought you a gift." },
    { "id": "it-0183", "front": "il sole", "back": "the sun (m)", "example": "Oggi splende il sole.", "exampleEn": "The sun is shining today." },
    { "id": "it-0184", "front": "la luna", "back": "the moon (f)", "example": "Stanotte la luna è piena.", "exampleEn": "Tonight the moon is full." },
    { "id": "it-0185", "front": "il mare", "back": "the sea (m)", "example": "D'estate andiamo al mare.", "exampleEn": "In summer we go to the sea." },
    { "id": "it-0186", "front": "la montagna", "back": "the mountain (f)", "example": "In inverno andiamo in montagna.", "exampleEn": "In winter we go to the mountains." },
    { "id": "it-0187", "front": "il cane", "back": "the dog (m)", "example": "Il mio cane è molto affettuoso.", "exampleEn": "My dog is very affectionate." },
    { "id": "it-0188", "front": "il gatto", "back": "the cat (m)", "example": "Il gatto dorme sul divano.", "exampleEn": "The cat is sleeping on the sofa." },
    { "id": "it-0189", "front": "la macchina", "back": "the car (f)", "example": "La macchina è nel garage.", "exampleEn": "The car is in the garage." },
    { "id": "it-0190", "front": "l'autobus", "back": "the bus (m)", "example": "Prendo l'autobus per andare al lavoro.", "exampleEn": "I take the bus to work." },
    { "id": "it-0191", "front": "il treno", "back": "the train (m)", "example": "Il treno è in ritardo.", "exampleEn": "The train is late." },
    { "id": "it-0192", "front": "l'aereo", "back": "the airplane (m)", "example": "L'aereo parte tra due ore.", "exampleEn": "The plane leaves in two hours." },
    { "id": "it-0193", "front": "la bicicletta", "back": "the bicycle (f)", "example": "Vado a scuola in bicicletta.", "exampleEn": "I ride my bike to school." },
    { "id": "it-0194", "front": "la moto", "back": "the motorcycle (f)", "example": "Ha comprato una moto nuova.", "exampleEn": "He bought a new motorcycle." },
    { "id": "it-0195", "front": "rosso", "back": "red", "example": "Mi piace il vestito rosso.", "exampleEn": "I like the red dress." },
    { "id": "it-0196", "front": "blu", "back": "blue", "example": "Il cielo è blu oggi.", "exampleEn": "The sky is blue today." },
    { "id": "it-0197", "front": "verde", "back": "green", "example": "L'erba è verde e fresca.", "exampleEn": "The grass is green and fresh." },
    { "id": "it-0198", "front": "giallo", "back": "yellow", "example": "Il sole è giallo nel disegno.", "exampleEn": "The sun is yellow in the drawing." },
    { "id": "it-0199", "front": "nero", "back": "black", "example": "Porto sempre scarpe nere.", "exampleEn": "I always wear black shoes." },
    { "id": "it-0200", "front": "bianco", "back": "white", "example": "La neve è bianca.", "exampleEn": "Snow is white." },
    { "id": "it-0201", "front": "grigio", "back": "gray", "example": "Il cielo è grigio e nuvoloso.", "exampleEn": "The sky is grey and cloudy." },
    { "id": "it-0202", "front": "marrone", "back": "brown", "example": "Ha gli occhi marroni.", "exampleEn": "She has brown eyes." },
    { "id": "it-0203", "front": "rosa", "back": "pink", "example": "Le ha regalato dei fiori rosa.", "exampleEn": "He gave her pink flowers." },
    { "id": "it-0204", "front": "grande", "back": "big", "example": "Vivono in una casa grande.", "exampleEn": "They live in a big house." },
    { "id": "it-0205", "front": "piccolo", "back": "small", "example": "Ho un cane piccolo.", "exampleEn": "I have a small dog." },
    { "id": "it-0206", "front": "buono", "back": "good / tasty", "example": "Questo gelato è molto buono.", "exampleEn": "This ice cream is very good." },
    { "id": "it-0207", "front": "cattivo", "back": "bad", "example": "Ha un cattivo carattere.", "exampleEn": "He has a bad temper." },
    { "id": "it-0208", "front": "nuovo", "back": "new", "example": "Ho comprato un telefono nuovo.", "exampleEn": "I bought a new phone." },
    { "id": "it-0209", "front": "vecchio", "back": "old", "example": "Questo è un libro molto vecchio.", "exampleEn": "This is a very old book." },
    { "id": "it-0210", "front": "bello", "back": "beautiful", "example": "Che bella giornata!", "exampleEn": "What a beautiful day!" },
    { "id": "it-0211", "front": "brutto", "back": "ugly", "example": "Fa un tempo brutto oggi.", "exampleEn": "The weather is bad today." },
    { "id": "it-0212", "front": "alto", "back": "tall / high", "example": "Mio fratello è molto alto.", "exampleEn": "My brother is very tall." },
    { "id": "it-0213", "front": "lungo", "back": "long", "example": "È stata una giornata lunga.", "exampleEn": "It's been a long day." },
    { "id": "it-0214", "front": "caldo", "back": "hot / warm", "example": "Il caffè è ancora caldo.", "exampleEn": "The coffee is still hot." },
    { "id": "it-0215", "front": "freddo", "back": "cold", "example": "L'acqua è troppo fredda.", "exampleEn": "The water is too cold." },
    { "id": "it-0216", "front": "difficile", "back": "difficult", "example": "L'italiano non è difficile.", "exampleEn": "Italian isn't difficult." },
    { "id": "it-0217", "front": "felice", "back": "happy", "example": "Sono felice di vederti.", "exampleEn": "I'm happy to see you." },
    { "id": "it-0218", "front": "stanco", "back": "tired", "example": "Sono molto stanco stasera.", "exampleEn": "I'm very tired tonight." },
    { "id": "it-0219", "front": "importante", "back": "important", "example": "Ho una riunione importante.", "exampleEn": "I have an important meeting." },
    { "id": "it-0220", "front": "destra", "back": "right", "example": "Gira a destra al semaforo.", "exampleEn": "Turn right at the traffic light." },
    { "id": "it-0221", "front": "sinistra", "back": "left", "example": "Il bagno è sulla sinistra.", "exampleEn": "The bathroom is on the left." },
    { "id": "it-0222", "front": "dritto", "back": "straight ahead", "example": "Vai sempre dritto per due strade.", "exampleEn": "Go straight ahead for two blocks." },
    { "id": "it-0223", "front": "vicino", "back": "near", "example": "Il bar è vicino a casa mia.", "exampleEn": "The bar is close to my house." },
    { "id": "it-0224", "front": "lontano", "back": "far", "example": "La stazione è lontana da qui.", "exampleEn": "The station is far from here." },
    { "id": "it-0225", "front": "sotto", "back": "below / under", "example": "Il gatto è sotto il letto.", "exampleEn": "The cat is under the bed." },
    { "id": "it-0226", "front": "qui", "back": "here", "example": "Vieni qui un momento.", "exampleEn": "Come here for a moment." },
    { "id": "it-0227", "front": "il tempo atmosferico", "back": "the weather (m)", "example": "Com'è il tempo atmosferico oggi?", "exampleEn": "What's the weather like today?" },
    { "id": "it-0228", "front": "la pioggia", "back": "the rain (f)", "example": "La pioggia non smette mai.", "exampleEn": "The rain never stops." },
    { "id": "it-0229", "front": "la neve", "back": "the snow (f)", "example": "La neve copre le montagne.", "exampleEn": "Snow covers the mountains." },
    { "id": "it-0230", "front": "il vento", "back": "the wind (m)", "example": "Oggi c'è molto vento.", "exampleEn": "It's very windy today." },
    { "id": "it-0231", "front": "la nuvola", "back": "the cloud (f)", "example": "C'è una nuvola nera in cielo.", "exampleEn": "There's a dark cloud in the sky." },
    { "id": "it-0232", "front": "il caldo", "back": "the heat (m)", "example": "D'estate fa un gran caldo.", "exampleEn": "It gets very hot in summer." },
    { "id": "it-0233", "front": "il freddo", "back": "the cold (m)", "example": "In inverno sento molto il freddo.", "exampleEn": "In winter I feel the cold a lot." },
    { "id": "it-0234", "front": "il temporale", "back": "the storm (m)", "example": "Sta arrivando un temporale.", "exampleEn": "A storm is coming." },
    { "id": "it-0235", "front": "il cielo", "back": "the sky (m)", "example": "Il cielo è limpido stasera.", "exampleEn": "The sky is clear tonight." },
    { "id": "it-0236", "front": "e", "back": "and", "example": "Voglio il pane e il latte.", "exampleEn": "I want bread and milk." },
    { "id": "it-0237", "front": "o", "back": "or", "example": "Vuoi il tè o il caffè?", "exampleEn": "Do you want tea or coffee?" },
    { "id": "it-0238", "front": "ma", "back": "but", "example": "Vorrei venire, ma non posso.", "exampleEn": "I'd like to come, but I can't." },
    { "id": "it-0239", "front": "con", "back": "with", "example": "Vengo con te al cinema.", "exampleEn": "I'm coming to the movies with you." },
    { "id": "it-0240", "front": "senza", "back": "without", "example": "Bevo il caffè senza zucchero.", "exampleEn": "I drink coffee without sugar." },
    { "id": "it-0241", "front": "per", "back": "for / in order to", "example": "Questo regalo è per te.", "exampleEn": "This gift is for you." },
    { "id": "it-0242", "front": "in", "back": "in", "example": "Vivo in Italia da tre anni.", "exampleEn": "I've been living in Italy for three years." },
    { "id": "it-0243", "front": "a", "back": "to / at", "example": "Vado a Roma domani.", "exampleEn": "I'm going to Rome tomorrow." },
    { "id": "it-0244", "front": "di", "back": "of / from", "example": "È la macchina di mio padre.", "exampleEn": "It's my father's car." },
    { "id": "it-0245", "front": "da", "back": "from / by", "example": "Vengo da Napoli.", "exampleEn": "I'm from Naples." },
    { "id": "it-0246", "front": "su", "back": "on", "example": "Il giornale è su quel tavolo.", "exampleEn": "The newspaper is on that table." },
    { "id": "it-0247", "front": "molto", "back": "very / a lot", "example": "Sono molto contento.", "exampleEn": "I'm very happy." },
    { "id": "it-0248", "front": "troppo", "back": "too much", "example": "Hai mangiato troppo.", "exampleEn": "You've eaten too much." },
    { "id": "it-0249", "front": "più", "back": "more", "example": "Voglio sapere di più.", "exampleEn": "I want to know more." },
    { "id": "it-0250", "front": "bene", "back": "well", "example": "Sto molto bene, grazie.", "exampleEn": "I'm doing very well, thank you." },
    { "id": "it-0251", "front": "il menù", "back": "menu", "example": "Posso vedere il menù, per favore?", "exampleEn": "Can I see the menu, please?" },
    { "id": "it-0252", "front": "il cameriere", "back": "waiter", "example": "Il cameriere porta i piatti al tavolo.", "exampleEn": "The waiter brings the plates to the table." },
    { "id": "it-0253", "front": "il conto", "back": "bill, check", "example": "Vorrei il conto, grazie.", "exampleEn": "I would like the bill, thank you." },
    { "id": "it-0254", "front": "la ricetta", "back": "recipe", "example": "Mia nonna ha una ricetta segreta per il ragù.", "exampleEn": "My grandmother has a secret recipe for ragù." },
    { "id": "it-0255", "front": "il piatto", "back": "dish, plate", "example": "Questo piatto è molto saporito.", "exampleEn": "This dish is very flavorful." },
    { "id": "it-0256", "front": "la forchetta", "back": "fork", "example": "Ho bisogno di una forchetta pulita.", "exampleEn": "I need a clean fork." },
    { "id": "it-0257", "front": "il coltello", "back": "knife", "example": "Il coltello non taglia bene.", "exampleEn": "The knife does not cut well." },
    { "id": "it-0258", "front": "il cucchiaio", "back": "spoon", "example": "Usa il cucchiaio per la minestra.", "exampleEn": "Use the spoon for the soup." },
    { "id": "it-0259", "front": "il bicchiere", "back": "glass", "example": "Riempi il bicchiere di vino rosso.", "exampleEn": "Fill the glass with red wine." },
    { "id": "it-0260", "front": "il vino", "back": "wine", "example": "Prendiamo una bottiglia di vino bianco.", "exampleEn": "Let's get a bottle of white wine." },
    { "id": "it-0261", "front": "la birra", "back": "beer", "example": "Preferisco la birra alla spina.", "exampleEn": "I prefer draft beer." },
    { "id": "it-0262", "front": "il succo", "back": "juice", "example": "Ogni mattina bevo il succo d'arancia.", "exampleEn": "Every morning I drink orange juice." },
    { "id": "it-0263", "front": "il tè", "back": "tea", "example": "Vuoi il tè caldo o freddo?", "exampleEn": "Do you want hot or cold tea?" },
    { "id": "it-0264", "front": "il latte", "back": "milk", "example": "Metto sempre il latte nel caffè.", "exampleEn": "I always put milk in my coffee." },
    { "id": "it-0265", "front": "l'olio d'oliva", "back": "olive oil", "example": "L'olio d'oliva è essenziale nella cucina italiana.", "exampleEn": "Olive oil is essential in Italian cooking." },
    { "id": "it-0266", "front": "l'aglio", "back": "garlic", "example": "Soffriggi l'aglio nell'olio per un minuto.", "exampleEn": "Sauté the garlic in oil for one minute." },
    { "id": "it-0267", "front": "la cipolla", "back": "onion", "example": "La cipolla mi fa lacrimare gli occhi.", "exampleEn": "The onion makes my eyes water." },
    { "id": "it-0268", "front": "il pomodoro", "back": "tomato", "example": "Il sugo di pomodoro è pronto.", "exampleEn": "The tomato sauce is ready." },
    { "id": "it-0269", "front": "il formaggio", "back": "cheese", "example": "Metti il formaggio grattugiato sulla pasta.", "exampleEn": "Put the grated cheese on the pasta." },
    { "id": "it-0270", "front": "il sale", "back": "salt", "example": "Aggiungi un pizzico di sale alla minestra.", "exampleEn": "Add a pinch of salt to the soup." },
    { "id": "it-0271", "front": "il pepe", "back": "pepper", "example": "Mi piace molto il pepe nero sulla bistecca.", "exampleEn": "I really like black pepper on the steak." },
    { "id": "it-0272", "front": "il burro", "back": "butter", "example": "Sciogliere il burro in padella a fuoco basso.", "exampleEn": "Melt the butter in a pan over low heat." },
    { "id": "it-0273", "front": "la farina", "back": "flour", "example": "Mescola la farina con le uova per fare la pasta.", "exampleEn": "Mix the flour with the eggs to make the dough." },
    { "id": "it-0274", "front": "l'uovo", "back": "egg", "example": "Vuoi l'uovo strapazzato o fritto?", "exampleEn": "Do you want the egg scrambled or fried?" },
    { "id": "it-0275", "front": "il riso", "back": "rice", "example": "Il risotto è fatto con il riso Arborio.", "exampleEn": "Risotto is made with Arborio rice." },
    { "id": "it-0276", "front": "la bistecca", "back": "steak", "example": "Voglio la bistecca al sangue.", "exampleEn": "I want the steak rare." },
    { "id": "it-0277", "front": "il pollo", "back": "chicken", "example": "Il pollo arrosto è il piatto preferito di mio padre.", "exampleEn": "Roast chicken is my father's favorite dish." },
    { "id": "it-0278", "front": "il maiale", "back": "pork", "example": "La costoletta di maiale è molto tenera.", "exampleEn": "The pork chop is very tender." },
    { "id": "it-0279", "front": "il manzo", "back": "beef", "example": "Il ragù tradizionale si fa con il manzo.", "exampleEn": "Traditional ragù is made with beef." },
    { "id": "it-0280", "front": "il salmone", "back": "salmon", "example": "Ho ordinato il salmone alla griglia.", "exampleEn": "I ordered grilled salmon." },
    { "id": "it-0281", "front": "il tonno", "back": "tuna", "example": "Metto il tonno nell'insalata.", "exampleEn": "I put tuna in the salad." },
    { "id": "it-0282", "front": "i gamberi", "back": "shrimp, prawns", "example": "I gamberi all'aglio sono deliziosi.", "exampleEn": "Garlic shrimp are delicious." },
    { "id": "it-0283", "front": "la mela", "back": "apple", "example": "Mangio una mela ogni giorno.", "exampleEn": "I eat an apple every day." },
    { "id": "it-0284", "front": "la banana", "back": "banana", "example": "La banana è già matura.", "exampleEn": "The banana is already ripe." },
    { "id": "it-0285", "front": "l'arancia", "back": "orange", "example": "Spremo un'arancia fresca ogni mattina.", "exampleEn": "I squeeze a fresh orange every morning." },
    { "id": "it-0286", "front": "la fragola", "back": "strawberry", "example": "Le fragole con la panna sono buonissime.", "exampleEn": "Strawberries with cream are delicious." },
    { "id": "it-0287", "front": "l'uva", "back": "grapes", "example": "L'uva di settembre è dolcissima.", "exampleEn": "September grapes are very sweet." },
    { "id": "it-0288", "front": "la carota", "back": "carrot", "example": "Taglia la carota a rondelle sottili.", "exampleEn": "Slice the carrot into thin rounds." },
    { "id": "it-0289", "front": "la patata", "back": "potato", "example": "Preferisco le patate al forno.", "exampleEn": "I prefer baked potatoes." },
    { "id": "it-0290", "front": "la lattuga", "back": "lettuce", "example": "Lava bene la lattuga prima di usarla.", "exampleEn": "Wash the lettuce well before using it." },
    { "id": "it-0291", "front": "il peperone", "back": "bell pepper", "example": "Il peperone rosso è più dolce di quello verde.", "exampleEn": "The red bell pepper is sweeter than the green one." },
    { "id": "it-0292", "front": "la zucchina", "back": "zucchini", "example": "Le zucchine grigliate sono un contorno leggero.", "exampleEn": "Grilled zucchini is a light side dish." },
    { "id": "it-0293", "front": "il basilico", "back": "basil", "example": "Aggiungi il basilico fresco alla fine.", "exampleEn": "Add the fresh basil at the end." },
    { "id": "it-0294", "front": "il prezzemolo", "back": "parsley", "example": "Trita il prezzemolo e mettilo sul pesce.", "exampleEn": "Chop the parsley and put it on the fish." },
    { "id": "it-0295", "front": "la mozzarella", "back": "mozzarella", "example": "La caprese è mozzarella, pomodoro e basilico.", "exampleEn": "Caprese is mozzarella, tomato and basil." },
    { "id": "it-0296", "front": "il prosciutto", "back": "cured ham", "example": "Il prosciutto crudo di Parma è famoso nel mondo.", "exampleEn": "Parma cured ham is famous worldwide." },
    { "id": "it-0297", "front": "la salsiccia", "back": "sausage", "example": "Cuocio la salsiccia con i peperoni.", "exampleEn": "I cook the sausage with peppers." },
    { "id": "it-0298", "front": "il salame", "back": "salami", "example": "Metti il salame sul tagliere.", "exampleEn": "Put the salami on the cutting board." },
    { "id": "it-0299", "front": "la minestra", "back": "soup", "example": "La minestra di verdure scalda quando fa freddo.", "exampleEn": "Vegetable soup warms you up when it's cold." },
    { "id": "it-0300", "front": "il brodo", "back": "broth, stock", "example": "Faccio il risotto con il brodo di pollo.", "exampleEn": "I make risotto with chicken broth." },
    { "id": "it-0301", "front": "la salsa", "back": "sauce", "example": "Questa salsa piccante è troppo forte per me.", "exampleEn": "This hot sauce is too strong for me." },
    { "id": "it-0302", "front": "l'antipasto", "back": "starter, appetizer", "example": "Come antipasto prendo i crostini.", "exampleEn": "As a starter I'll have the crostini." },
    { "id": "it-0303", "front": "il primo", "back": "first course", "example": "Come primo ordino le tagliatelle al ragù.", "exampleEn": "As a first course I order tagliatelle with ragù." },
    { "id": "it-0304", "front": "il secondo", "back": "main course", "example": "Per secondo prendo la bistecca.", "exampleEn": "For the main course I'll have the steak." },
    { "id": "it-0305", "front": "il contorno", "back": "side dish", "example": "Come contorno voglio un'insalata mista.", "exampleEn": "As a side dish I want a mixed salad." },
    { "id": "it-0306", "front": "il dolce", "back": "dessert, sweet", "example": "Il dolce del giorno è il tiramisù.", "exampleEn": "The dessert of the day is tiramisu." },
    { "id": "it-0307", "front": "il gelato", "back": "ice cream", "example": "Dopo cena prendiamo un gelato.", "exampleEn": "After dinner let's get an ice cream." },
    { "id": "it-0308", "front": "la torta", "back": "cake, tart", "example": "La torta al cioccolato è quasi pronta.", "exampleEn": "The chocolate cake is almost ready." },
    { "id": "it-0309", "front": "la colazione", "back": "breakfast", "example": "Faccio sempre colazione con un cornetto e un caffè.", "exampleEn": "I always have breakfast with a croissant and a coffee." },
    { "id": "it-0310", "front": "il pranzo", "back": "lunch", "example": "A pranzo mangiamo alle tredici.", "exampleEn": "We eat lunch at one o'clock." },
    { "id": "it-0311", "front": "la cena", "back": "dinner", "example": "La cena è pronta, siediti a tavola.", "exampleEn": "Dinner is ready, sit down at the table." },
    { "id": "it-0312", "front": "l'aeroporto", "back": "airport", "example": "Il mio volo parte dall'aeroporto alle otto.", "exampleEn": "My flight leaves from the airport at eight." },
    { "id": "it-0313", "front": "il porto", "back": "port / harbor", "example": "La nave arriva al porto domani mattina.", "exampleEn": "The ship arrives at the port tomorrow morning." },
    { "id": "it-0314", "front": "la fermata", "back": "stop (bus/tram)", "example": "Aspetto l'autobus alla fermata.", "exampleEn": "I wait for the bus at the stop." },
    { "id": "it-0315", "front": "il binario", "back": "platform / track", "example": "Il treno per Roma parte dal binario tre.", "exampleEn": "The train to Rome leaves from platform three." },
    { "id": "it-0316", "front": "il biglietto", "back": "ticket", "example": "Compro il biglietto prima di salire sul treno.", "exampleEn": "I buy the ticket before getting on the train." },
    { "id": "it-0317", "front": "la coincidenza", "back": "connection / transfer", "example": "Ho perso la coincidenza per Milano.", "exampleEn": "I missed the connection to Milan." },
    { "id": "it-0318", "front": "il ritardo", "back": "delay", "example": "Il treno ha un ritardo di venti minuti.", "exampleEn": "The train has a twenty-minute delay." },
    { "id": "it-0319", "front": "il volo", "back": "flight", "example": "Il mio volo dura due ore.", "exampleEn": "My flight lasts two hours." },
    { "id": "it-0320", "front": "la valigia", "back": "suitcase", "example": "Ho dimenticato la valigia in hotel.", "exampleEn": "I forgot the suitcase at the hotel." },
    { "id": "it-0321", "front": "lo zaino", "back": "backpack", "example": "Metto la cartina nello zaino.", "exampleEn": "I put the map in the backpack." },
    { "id": "it-0322", "front": "il passaporto", "back": "passport", "example": "Devi mostrare il passaporto al controllo.", "exampleEn": "You must show your passport at the checkpoint." },
    { "id": "it-0323", "front": "il check-in", "back": "check-in", "example": "Il check-in apre due ore prima del volo.", "exampleEn": "Check-in opens two hours before the flight." },
    { "id": "it-0324", "front": "il bagaglio", "back": "luggage / baggage", "example": "Il bagaglio a mano è incluso nel prezzo.", "exampleEn": "The carry-on luggage is included in the price." },
    { "id": "it-0325", "front": "il taxi", "back": "taxi", "example": "Prendiamo un taxi per andare in centro.", "exampleEn": "We take a taxi to go to the city center." },
    { "id": "it-0326", "front": "la metropolitana", "back": "subway / metro", "example": "La metropolitana è più veloce del bus.", "exampleEn": "The subway is faster than the bus." },
    { "id": "it-0327", "front": "il tram", "back": "tram / streetcar", "example": "Prendo il tram ogni mattina per andare al lavoro.", "exampleEn": "I take the tram every morning to go to work." },
    { "id": "it-0328", "front": "il traghetto", "back": "ferry", "example": "Il traghetto per la Sardegna parte a mezzanotte.", "exampleEn": "The ferry to Sardinia departs at midnight." },
    { "id": "it-0329", "front": "l'autostrada", "back": "motorway / highway", "example": "Percorriamo l'autostrada fino a Napoli.", "exampleEn": "We travel the motorway all the way to Naples." },
    { "id": "it-0330", "front": "il semaforo", "back": "traffic light", "example": "Gira a sinistra al prossimo semaforo.", "exampleEn": "Turn left at the next traffic light." },
    { "id": "it-0331", "front": "il marciapiede", "back": "pavement / sidewalk", "example": "I bambini camminano sul marciapiede.", "exampleEn": "The children walk on the pavement." },
    { "id": "it-0332", "front": "l'incrocio", "back": "intersection / crossroads", "example": "Svolta a destra al prossimo incrocio.", "exampleEn": "Turn right at the next intersection." },
    { "id": "it-0333", "front": "il ponte", "back": "bridge", "example": "Attraversiamo il ponte sul fiume.", "exampleEn": "We cross the bridge over the river." },
    { "id": "it-0334", "front": "la piazza", "back": "square / plaza", "example": "Ci vediamo in piazza alle cinque.", "exampleEn": "We meet in the square at five." },
    { "id": "it-0335", "front": "il vicolo", "back": "alley / lane", "example": "C'è un piccolo caffè in fondo al vicolo.", "exampleEn": "There is a small café at the end of the alley." },
    { "id": "it-0336", "front": "il quartiere", "back": "neighborhood / district", "example": "Abito in un quartiere tranquillo.", "exampleEn": "I live in a quiet neighborhood." },
    { "id": "it-0337", "front": "il centro storico", "back": "old town / historic center", "example": "Il museo è nel centro storico della città.", "exampleEn": "The museum is in the old town of the city." },
    { "id": "it-0338", "front": "la periferia", "back": "outskirts / suburbs", "example": "La fabbrica si trova in periferia.", "exampleEn": "The factory is located on the outskirts." },
    { "id": "it-0339", "front": "l'hotel", "back": "hotel", "example": "Abbiamo prenotato un hotel vicino alla stazione.", "exampleEn": "We booked a hotel near the station." },
    { "id": "it-0340", "front": "l'ostello", "back": "hostel", "example": "L'ostello costa molto meno dell'hotel.", "exampleEn": "The hostel costs much less than the hotel." },
    { "id": "it-0341", "front": "la reception", "back": "reception / front desk", "example": "Lascia le chiavi alla reception quando esci.", "exampleEn": "Leave the keys at reception when you go out." },
    { "id": "it-0342", "front": "la prenotazione", "back": "reservation / booking", "example": "Ho una prenotazione per due notti.", "exampleEn": "I have a reservation for two nights." },
    { "id": "it-0343", "front": "la camera", "back": "room (hotel)", "example": "Vorrei una camera con vista sul mare.", "exampleEn": "I would like a room with a sea view." },
    { "id": "it-0344", "front": "il museo", "back": "museum", "example": "Il museo è chiuso il lunedì.", "exampleEn": "The museum is closed on Mondays." },
    { "id": "it-0345", "front": "la chiesa", "back": "church", "example": "La chiesa più antica è in centro.", "exampleEn": "The oldest church is in the center." },
    { "id": "it-0346", "front": "il castello", "back": "castle", "example": "Il castello si vede da tutta la città.", "exampleEn": "The castle can be seen from the whole city." },
    { "id": "it-0347", "front": "il palazzo", "back": "palace / large building", "example": "Quel palazzo antico è oggi un hotel.", "exampleEn": "That old palace is a hotel today." },
    { "id": "it-0348", "front": "il parco", "back": "park", "example": "Facciamo una passeggiata nel parco.", "exampleEn": "We take a walk in the park." },
    { "id": "it-0349", "front": "la fontana", "back": "fountain", "example": "La fontana si trova al centro della piazza.", "exampleEn": "The fountain is located in the center of the square." },
    { "id": "it-0350", "front": "il monumento", "back": "monument", "example": "Scattiamo una foto davanti al monumento.", "exampleEn": "We take a photo in front of the monument." },
    { "id": "it-0351", "front": "la galleria", "back": "art gallery / arcade", "example": "Visitiamo la galleria d'arte nel pomeriggio.", "exampleEn": "We visit the art gallery in the afternoon." },
    { "id": "it-0352", "front": "l'ufficio postale", "back": "post office", "example": "Devo andare all'ufficio postale a spedire un pacco.", "exampleEn": "I need to go to the post office to send a package." },
    { "id": "it-0353", "front": "la farmacia", "back": "pharmacy", "example": "C'è una farmacia aperta vicino all'hotel.", "exampleEn": "There is an open pharmacy near the hotel." },
    { "id": "it-0354", "front": "il supermercato", "back": "supermarket", "example": "Compriamo l'acqua al supermercato.", "exampleEn": "We buy water at the supermarket." },
    { "id": "it-0355", "front": "la cartoleria", "back": "stationery shop", "example": "Compro una cartolina alla cartoleria.", "exampleEn": "I buy a postcard at the stationery shop." },
    { "id": "it-0356", "front": "il distributore di benzina", "back": "petrol station / gas station", "example": "Il distributore di benzina è sull'autostrada.", "exampleEn": "The petrol station is on the motorway." },
    { "id": "it-0357", "front": "il parcheggio", "back": "parking lot / car park", "example": "Ho lasciato la macchina nel parcheggio.", "exampleEn": "I left the car in the car park." },
    { "id": "it-0358", "front": "la mappa", "back": "map", "example": "Guardo la mappa per trovare la strada.", "exampleEn": "I look at the map to find the way." },
    { "id": "it-0359", "front": "l'indicazione", "back": "direction / sign", "example": "Segui le indicazioni per il centro.", "exampleEn": "Follow the signs for the city center." },
    { "id": "it-0360", "front": "il percorso", "back": "route / path", "example": "Qual è il percorso più breve?", "exampleEn": "What is the shortest route?" },
    { "id": "it-0361", "front": "girare", "back": "to turn", "example": "Devi girare a destra dopo il ponte.", "exampleEn": "You have to turn right after the bridge." },
    { "id": "it-0362", "front": "attraversare", "back": "to cross", "example": "Attraversiamo la strada sulle strisce pedonali.", "exampleEn": "We cross the street at the crosswalk." },
    { "id": "it-0363", "front": "continuare dritto", "back": "to go straight", "example": "Continua dritto fino alla piazza.", "exampleEn": "Go straight to the square." },
    { "id": "it-0364", "front": "salire", "back": "to get on / to go up", "example": "Saliamo sul treno al binario due.", "exampleEn": "We get on the train at platform two." },
    { "id": "it-0365", "front": "scendere", "back": "to get off / to go down", "example": "Scendo all'ultima fermata.", "exampleEn": "I get off at the last stop." },
    { "id": "it-0366", "front": "prenotare", "back": "to book / to reserve", "example": "Voglio prenotare un volo per Parigi.", "exampleEn": "I want to book a flight to Paris." },
    { "id": "it-0367", "front": "noleggiare", "back": "to rent / to hire", "example": "Noleggiamo una macchina per il weekend.", "exampleEn": "We rent a car for the weekend." },
    { "id": "it-0368", "front": "viaggiare", "back": "to travel", "example": "Mi piace viaggiare in treno.", "exampleEn": "I like to travel by train." },
    { "id": "it-0369", "front": "perdersi", "back": "to get lost", "example": "Mi sono perso nel centro storico.", "exampleEn": "I got lost in the old town." },
    { "id": "it-0370", "front": "in orario", "back": "on time", "example": "Il treno è arrivato esattamente in orario.", "exampleEn": "The train arrived exactly on time." },
    { "id": "it-0371", "front": "il cambio", "back": "currency exchange", "example": "Faccio il cambio all'ufficio in stazione.", "exampleEn": "I do the currency exchange at the office in the station." },
    { "id": "it-0372", "front": "il turista", "back": "tourist", "example": "Molti turisti visitano Roma ogni anno.", "exampleEn": "Many tourists visit Rome every year." },
    { "id": "it-0373", "front": "l'ufficio", "back": "office", "example": "Lavoro in un ufficio nel centro della città.", "exampleEn": "I work in an office in the city center." },
    { "id": "it-0374", "front": "il collega", "back": "colleague, coworker", "example": "Il mio collega è molto bravo nel suo lavoro.", "exampleEn": "My colleague is very good at his job." },
    { "id": "it-0375", "front": "il capo", "back": "boss, head", "example": "Il capo ha convocato una riunione per domani.", "exampleEn": "The boss has called a meeting for tomorrow." },
    { "id": "it-0376", "front": "la riunione", "back": "meeting", "example": "Abbiamo una riunione importante alle dieci.", "exampleEn": "We have an important meeting at ten." },
    { "id": "it-0377", "front": "l'azienda", "back": "company, firm", "example": "Quest'azienda produce software per le banche.", "exampleEn": "This company makes software for banks." },
    { "id": "it-0378", "front": "il contratto", "back": "contract", "example": "Ho firmato il contratto di lavoro oggi.", "exampleEn": "I signed the work contract today." },
    { "id": "it-0379", "front": "lo stipendio", "back": "salary, wage", "example": "Lo stipendio viene pagato alla fine del mese.", "exampleEn": "The salary is paid at the end of the month." },
    { "id": "it-0380", "front": "la fattura", "back": "invoice", "example": "Devo inviare la fattura al cliente entro oggi.", "exampleEn": "I need to send the invoice to the client by today." },
    { "id": "it-0381", "front": "il budget", "back": "budget", "example": "Il budget per il progetto è limitato.", "exampleEn": "The budget for the project is limited." },
    { "id": "it-0382", "front": "il profitto", "back": "profit", "example": "L'azienda ha realizzato un buon profitto quest'anno.", "exampleEn": "The company made a good profit this year." },
    { "id": "it-0383", "front": "la perdita", "back": "loss", "example": "Abbiamo subito una perdita a causa della crisi.", "exampleEn": "We suffered a loss because of the crisis." },
    { "id": "it-0384", "front": "il prestito", "back": "loan", "example": "Ho chiesto un prestito in banca per comprare casa.", "exampleEn": "I asked for a loan at the bank to buy a house." },
    { "id": "it-0385", "front": "l'interesse", "back": "interest (financial)", "example": "Il tasso di interesse è aumentato quest'anno.", "exampleEn": "The interest rate has increased this year." },
    { "id": "it-0386", "front": "l'investimento", "back": "investment", "example": "Questo investimento potrebbe portare buoni risultati.", "exampleEn": "This investment could bring good results." },
    { "id": "it-0387", "front": "il cliente", "back": "client, customer", "example": "Il cliente vuole una risposta entro domani.", "exampleEn": "The client wants an answer by tomorrow." },
    { "id": "it-0388", "front": "il fornitore", "back": "supplier, vendor", "example": "Il fornitore ha ritardato la consegna dei materiali.", "exampleEn": "The supplier delayed the delivery of materials." },
    { "id": "it-0389", "front": "la consegna", "back": "delivery", "example": "La consegna è prevista per venerdì mattina.", "exampleEn": "The delivery is expected on Friday morning." },
    { "id": "it-0390", "front": "il progetto", "back": "project", "example": "Stiamo lavorando a un nuovo progetto insieme.", "exampleEn": "We are working on a new project together." },
    { "id": "it-0391", "front": "la scadenza", "back": "deadline", "example": "La scadenza per questo lavoro è lunedì.", "exampleEn": "The deadline for this work is Monday." },
    { "id": "it-0392", "front": "il colloquio", "back": "job interview", "example": "Ho un colloquio di lavoro domani mattina.", "exampleEn": "I have a job interview tomorrow morning." },
    { "id": "it-0393", "front": "assumere", "back": "to hire", "example": "L'azienda vuole assumere tre nuovi dipendenti.", "exampleEn": "The company wants to hire three new employees." },
    { "id": "it-0394", "front": "il dipendente", "back": "employee", "example": "Ogni dipendente ha ricevuto un bonus a Natale.", "exampleEn": "Every employee received a bonus at Christmas." },
    { "id": "it-0395", "front": "licenziare", "back": "to fire, to dismiss", "example": "Il capo ha dovuto licenziare due persone.", "exampleEn": "The boss had to fire two people." },
    { "id": "it-0396", "front": "il curriculum", "back": "résumé, CV", "example": "Ho aggiornato il curriculum prima del colloquio.", "exampleEn": "I updated my résumé before the interview." },
    { "id": "it-0397", "front": "la classe", "back": "class, classroom", "example": "La classe inizia alle nove di mattina.", "exampleEn": "The class starts at nine in the morning." },
    { "id": "it-0398", "front": "il professore / la professoressa", "back": "professor, teacher", "example": "La professoressa spiega la grammatica molto chiaramente.", "exampleEn": "The teacher explains grammar very clearly." },
    { "id": "it-0399", "front": "l'alunno / l'alunna", "back": "pupil, student", "example": "Ogni alunno deve fare i compiti ogni sera.", "exampleEn": "Every pupil must do homework every evening." },
    { "id": "it-0400", "front": "il compito", "back": "homework, assignment", "example": "Ho dimenticato di fare il compito di matematica.", "exampleEn": "I forgot to do my math homework." },
    { "id": "it-0401", "front": "l'esame", "back": "exam, test", "example": "Devo studiare molto per l'esame di storia.", "exampleEn": "I need to study a lot for the history exam." },
    { "id": "it-0402", "front": "il voto", "back": "grade, mark", "example": "Ho preso un bel voto in matematica.", "exampleEn": "I got a good grade in math." },
    { "id": "it-0403", "front": "la laurea", "back": "university degree", "example": "Ha preso la laurea in economia lo scorso anno.", "exampleEn": "He got his degree in economics last year." },
    { "id": "it-0404", "front": "la materia", "back": "subject, course", "example": "La mia materia preferita è l'informatica.", "exampleEn": "My favorite subject is computer science." },
    { "id": "it-0405", "front": "la lezione", "back": "lesson, lecture", "example": "La lezione di inglese dura un'ora.", "exampleEn": "The English lesson lasts one hour." },
    { "id": "it-0406", "front": "la biblioteca", "back": "library", "example": "Vado in biblioteca a studiare nel pomeriggio.", "exampleEn": "I go to the library to study in the afternoon." },
    { "id": "it-0407", "front": "la penna", "back": "pen", "example": "Puoi prestarmi una penna per firmare?", "exampleEn": "Can you lend me a pen to sign?" },
    { "id": "it-0408", "front": "il foglio", "back": "sheet of paper", "example": "Scrivi la risposta su un foglio separato.", "exampleEn": "Write the answer on a separate sheet of paper." },
    { "id": "it-0409", "front": "il computer", "back": "computer", "example": "Il mio computer è lento stamattina.", "exampleEn": "My computer is slow this morning." },
    { "id": "it-0410", "front": "il portatile", "back": "laptop", "example": "Porto il portatile in riunione ogni giorno.", "exampleEn": "I bring the laptop to the meeting every day." },
    { "id": "it-0411", "front": "lo schermo", "back": "screen, monitor", "example": "Lo schermo del telefono si è rotto ieri.", "exampleEn": "The phone screen broke yesterday." },
    { "id": "it-0412", "front": "la tastiera", "back": "keyboard", "example": "Ho comprato una nuova tastiera wireless.", "exampleEn": "I bought a new wireless keyboard." },
    { "id": "it-0413", "front": "il mouse", "back": "mouse (computer)", "example": "Il mouse non funziona bene, devo cambiarlo.", "exampleEn": "The mouse doesn't work well, I need to replace it." },
    { "id": "it-0414", "front": "la stampante", "back": "printer", "example": "La stampante ha finito la carta.", "exampleEn": "The printer has run out of paper." },
    { "id": "it-0415", "front": "il file", "back": "file (digital)", "example": "Puoi mandare il file via email?", "exampleEn": "Can you send the file by email?" },
    { "id": "it-0416", "front": "la cartella", "back": "folder, briefcase", "example": "Ho salvato tutti i documenti in una cartella.", "exampleEn": "I saved all the documents in a folder." },
    { "id": "it-0417", "front": "il sito web", "back": "website", "example": "Ho trovato le informazioni sul loro sito web.", "exampleEn": "I found the information on their website." },
    { "id": "it-0418", "front": "l'applicazione", "back": "app, application", "example": "C'è un'applicazione utile per gestire le spese.", "exampleEn": "There is a useful app for managing expenses." },
    { "id": "it-0419", "front": "la password", "back": "password", "example": "Non ricordo la password del mio account.", "exampleEn": "I don't remember the password to my account." },
    { "id": "it-0420", "front": "il software", "back": "software", "example": "Dobbiamo aggiornare il software del sistema.", "exampleEn": "We need to update the system software." },
    { "id": "it-0421", "front": "il wi-fi", "back": "wi-fi, wireless internet", "example": "C'è il wi-fi gratuito in questo bar.", "exampleEn": "There is free wi-fi in this café." },
    { "id": "it-0422", "front": "la connessione", "back": "connection", "example": "La connessione a internet è lenta oggi.", "exampleEn": "The internet connection is slow today." },
    { "id": "it-0423", "front": "l'email", "back": "email", "example": "Ti mando i dettagli per email.", "exampleEn": "I'll send you the details by email." },
    { "id": "it-0424", "front": "il messaggio", "back": "message", "example": "Ho ricevuto un messaggio dal mio capo.", "exampleEn": "I received a message from my boss." },
    { "id": "it-0425", "front": "la pubblicità", "back": "advertisement", "example": "La pubblicità online è molto efficace oggi.", "exampleEn": "Online advertising is very effective today." },
    { "id": "it-0426", "front": "la spesa", "back": "expense, spending", "example": "Dobbiamo ridurre le spese dell'ufficio.", "exampleEn": "We need to reduce office expenses." },
    { "id": "it-0427", "front": "la ricevuta", "back": "receipt", "example": "Tieni la ricevuta per il rimborso spese.", "exampleEn": "Keep the receipt for expense reimbursement." },
    { "id": "it-0428", "front": "la firma", "back": "signature", "example": "Manca solo la tua firma sul documento.", "exampleEn": "Only your signature is missing on the document." },
    { "id": "it-0429", "front": "l'impresa", "back": "business, enterprise", "example": "Ha avviato una piccola impresa artigianale.", "exampleEn": "He started a small craft business." },
    { "id": "it-0430", "front": "guadagnare", "back": "to earn", "example": "Vuole guadagnare di più cambiando lavoro.", "exampleEn": "She wants to earn more by changing jobs." },
    { "id": "it-0431", "front": "il marito", "back": "husband", "example": "Mio marito cucina ogni sera.", "exampleEn": "My husband cooks every evening." },
    { "id": "it-0432", "front": "la moglie", "back": "wife", "example": "Mia moglie lavora in centro.", "exampleEn": "My wife works downtown." },
    { "id": "it-0433", "front": "lo zio", "back": "uncle", "example": "Mio zio abita a Milano.", "exampleEn": "My uncle lives in Milan." },
    { "id": "it-0434", "front": "la zia", "back": "aunt", "example": "La zia porta i dolci a Natale.", "exampleEn": "The aunt brings sweets at Christmas." },
    { "id": "it-0435", "front": "il cugino", "back": "cousin (male)", "example": "Mio cugino ha quindici anni.", "exampleEn": "My cousin is fifteen years old." },
    { "id": "it-0436", "front": "il nipote", "back": "nephew / grandson", "example": "Il nipote gioca in giardino.", "exampleEn": "The grandson plays in the garden." },
    { "id": "it-0437", "front": "i genitori", "back": "parents", "example": "I miei genitori abitano in campagna.", "exampleEn": "My parents live in the countryside." },
    { "id": "it-0438", "front": "il maglione", "back": "sweater / jumper", "example": "Metto il maglione perché fa freddo.", "exampleEn": "I put on a sweater because it's cold." },
    { "id": "it-0439", "front": "la camicia", "back": "shirt", "example": "Quella camicia bianca è molto elegante.", "exampleEn": "That white shirt is very elegant." },
    { "id": "it-0440", "front": "i pantaloni", "back": "trousers / pants", "example": "Ho comprato nuovi pantaloni al mercato.", "exampleEn": "I bought new trousers at the market." },
    { "id": "it-0441", "front": "la gonna", "back": "skirt", "example": "Lei porta una gonna lunga.", "exampleEn": "She is wearing a long skirt." },
    { "id": "it-0442", "front": "le scarpe", "back": "shoes", "example": "Queste scarpe sono comode e belle.", "exampleEn": "These shoes are comfortable and nice." },
    { "id": "it-0443", "front": "gli stivali", "back": "boots", "example": "Indosso gli stivali quando piove.", "exampleEn": "I wear boots when it rains." },
    { "id": "it-0444", "front": "il cappotto", "back": "coat / overcoat", "example": "Il cappotto grigio è mio.", "exampleEn": "The grey coat is mine." },
    { "id": "it-0445", "front": "il vestito", "back": "dress / suit / outfit", "example": "Ha messo un vestito rosso alla festa.", "exampleEn": "She wore a red dress to the party." },
    { "id": "it-0446", "front": "la giacca", "back": "jacket", "example": "Hai preso la tua giacca?", "exampleEn": "Did you take your jacket?" },
    { "id": "it-0447", "front": "la cintura", "back": "belt", "example": "Ho bisogno di una cintura nuova.", "exampleEn": "I need a new belt." },
    { "id": "it-0448", "front": "i guanti", "back": "gloves", "example": "Non trovo i guanti questo inverno.", "exampleEn": "I can't find my gloves this winter." },
    { "id": "it-0449", "front": "la sciarpa", "back": "scarf", "example": "La sciarpa mi tiene caldo.", "exampleEn": "The scarf keeps me warm." },
    { "id": "it-0450", "front": "il cappello", "back": "hat", "example": "Porta sempre un cappello in estate.", "exampleEn": "He always wears a hat in summer." },
    { "id": "it-0451", "front": "la borsa", "back": "bag / handbag", "example": "Ho messo il portafoglio nella borsa.", "exampleEn": "I put the wallet in the bag." },
    { "id": "it-0452", "front": "il portafoglio", "back": "wallet", "example": "Il mio portafoglio è vuoto oggi.", "exampleEn": "My wallet is empty today." },
    { "id": "it-0453", "front": "il prezzo", "back": "price", "example": "Qual è il prezzo di questa giacca?", "exampleEn": "What is the price of this jacket?" },
    { "id": "it-0454", "front": "la taglia", "back": "size (clothing)", "example": "Che taglia porta?", "exampleEn": "What size do you wear?" },
    { "id": "it-0455", "front": "il camerino", "back": "fitting room", "example": "Posso usare il camerino per provare?", "exampleEn": "Can I use the fitting room to try it on?" },
    { "id": "it-0456", "front": "lo scontrino", "back": "receipt", "example": "Tenga lo scontrino per il cambio.", "exampleEn": "Keep the receipt for an exchange." },
    { "id": "it-0457", "front": "la cassa", "back": "checkout / cash desk", "example": "Paga alla cassa in fondo al negozio.", "exampleEn": "Pay at the checkout at the back of the shop." },
    { "id": "it-0458", "front": "la carta di credito", "back": "credit card", "example": "Posso pagare con la carta di credito?", "exampleEn": "Can I pay with a credit card?" },
    { "id": "it-0459", "front": "lo sconto", "back": "discount", "example": "C'è uno sconto del venti per cento.", "exampleEn": "There is a twenty percent discount." },
    { "id": "it-0460", "front": "il saldo", "back": "sale / clearance", "example": "Ho trovato questo vestito nei saldi.", "exampleEn": "I found this dress in the sales." },
    { "id": "it-0461", "front": "il soggiorno", "back": "living room", "example": "La famiglia si riunisce nel soggiorno.", "exampleEn": "The family gathers in the living room." },
    { "id": "it-0462", "front": "la camera da letto", "back": "bedroom", "example": "La camera da letto ha una grande finestra.", "exampleEn": "The bedroom has a large window." },
    { "id": "it-0463", "front": "il divano", "back": "sofa / couch", "example": "Mi siedo sul divano dopo cena.", "exampleEn": "I sit on the sofa after dinner." },
    { "id": "it-0464", "front": "l'armadio", "back": "wardrobe / closet", "example": "I vestiti sono nell'armadio.", "exampleEn": "The clothes are in the wardrobe." },
    { "id": "it-0465", "front": "la lampada", "back": "lamp", "example": "Accendi la lampada, per favore.", "exampleEn": "Turn on the lamp, please." },
    { "id": "it-0466", "front": "il frigorifero", "back": "refrigerator / fridge", "example": "Metti il latte nel frigorifero.", "exampleEn": "Put the milk in the fridge." },
    { "id": "it-0467", "front": "la lavatrice", "back": "washing machine", "example": "La lavatrice è in bagno.", "exampleEn": "The washing machine is in the bathroom." },
    { "id": "it-0468", "front": "il forno", "back": "oven", "example": "Ho messo la pizza nel forno.", "exampleEn": "I put the pizza in the oven." },
    { "id": "it-0469", "front": "il tetto", "back": "roof", "example": "Il tetto della casa è vecchio.", "exampleEn": "The roof of the house is old." },
    { "id": "it-0470", "front": "il muro", "back": "wall", "example": "Attacchiamo un quadro al muro.", "exampleEn": "We hang a picture on the wall." },
    { "id": "it-0471", "front": "il pavimento", "back": "floor", "example": "Il pavimento è di legno.", "exampleEn": "The floor is made of wood." },
    { "id": "it-0472", "front": "le scale", "back": "stairs", "example": "Salgo le scale ogni mattina.", "exampleEn": "I climb the stairs every morning." },
    { "id": "it-0473", "front": "il giardino", "back": "garden / yard", "example": "I bambini giocano in giardino.", "exampleEn": "The children play in the garden." },
    { "id": "it-0474", "front": "il balcone", "back": "balcony", "example": "Coltiviamo i fiori sul balcone.", "exampleEn": "We grow flowers on the balcony." },
    { "id": "it-0475", "front": "la sveglia", "back": "alarm clock", "example": "La sveglia suona alle sette.", "exampleEn": "The alarm clock rings at seven." },
    { "id": "it-0476", "front": "alzarsi", "back": "to get up", "example": "Mi alzo tardi il sabato.", "exampleEn": "I get up late on Saturdays." },
    { "id": "it-0477", "front": "lavarsi", "back": "to wash oneself", "example": "Mi lavo la faccia ogni mattina.", "exampleEn": "I wash my face every morning." },
    { "id": "it-0478", "front": "vestirsi", "back": "to get dressed", "example": "I bambini si vestono da soli.", "exampleEn": "The children get dressed by themselves." },
    { "id": "it-0479", "front": "fare colazione", "back": "to have breakfast", "example": "Faccio colazione con il caffè.", "exampleEn": "I have breakfast with coffee." },
    { "id": "it-0480", "front": "prepararsi", "back": "to get ready", "example": "Mi preparo in trenta minuti.", "exampleEn": "I get ready in thirty minutes." },
    { "id": "it-0481", "front": "andare a letto", "back": "to go to bed", "example": "Vado a letto alle undici di sera.", "exampleEn": "I go to bed at eleven at night." },
    { "id": "it-0482", "front": "fare la doccia", "back": "to take a shower", "example": "Faccio la doccia ogni mattina.", "exampleEn": "I take a shower every morning." },
    { "id": "it-0483", "front": "cucinare", "back": "to cook", "example": "Mia madre cucina benissimo.", "exampleEn": "My mother cooks very well." },
    { "id": "it-0484", "front": "apparecchiare la tavola", "back": "to set the table", "example": "Puoi apparecchiare la tavola, per favore?", "exampleEn": "Can you set the table, please?" },
    { "id": "it-0485", "front": "fare la spesa", "back": "to do the grocery shopping", "example": "Faccio la spesa al supermercato.", "exampleEn": "I do the grocery shopping at the supermarket." },
    { "id": "it-0486", "front": "pulire", "back": "to clean", "example": "Pulisco la casa ogni fine settimana.", "exampleEn": "I clean the house every weekend." },
    { "id": "it-0487", "front": "riposarsi", "back": "to rest", "example": "Mi riposo un po' dopo pranzo.", "exampleEn": "I rest a little after lunch." },
    { "id": "it-0488", "front": "il corpo", "back": "the body", "example": "Il corpo umano è molto complesso.", "exampleEn": "The human body is very complex." },
    { "id": "it-0489", "front": "la schiena", "back": "the back", "example": "Ho un dolore alla schiena oggi.", "exampleEn": "I have back pain today." },
    { "id": "it-0490", "front": "il petto", "back": "the chest", "example": "Sento un peso sul petto.", "exampleEn": "I feel a weight on my chest." },
    { "id": "it-0491", "front": "la spalla", "back": "the shoulder", "example": "Mi fa male la spalla destra.", "exampleEn": "My right shoulder hurts." },
    { "id": "it-0492", "front": "il ginocchio", "back": "the knee", "example": "Si è fatto male al ginocchio.", "exampleEn": "He hurt his knee." },
    { "id": "it-0493", "front": "il dito", "back": "the finger", "example": "Mi sono tagliato un dito.", "exampleEn": "I cut my finger." },
    { "id": "it-0494", "front": "la pelle", "back": "the skin", "example": "Ha la pelle molto sensibile.", "exampleEn": "She has very sensitive skin." },
    { "id": "it-0495", "front": "il cuore", "back": "the heart", "example": "Il cuore batte velocemente.", "exampleEn": "The heart beats fast." },
    { "id": "it-0496", "front": "il polmone", "back": "the lung", "example": "Fumare fa male ai polmoni.", "exampleEn": "Smoking is bad for the lungs." },
    { "id": "it-0497", "front": "lo stomaco", "back": "the stomach", "example": "Ho mal di stomaco dopo aver mangiato.", "exampleEn": "I have a stomachache after eating." },
    { "id": "it-0498", "front": "il braccio", "back": "the arm", "example": "Si è rotto il braccio cadendo.", "exampleEn": "He broke his arm falling." },
    { "id": "it-0499", "front": "l'orecchio", "back": "the ear", "example": "Non sento bene dall'orecchio sinistro.", "exampleEn": "I don't hear well from my left ear." },
    { "id": "it-0500", "front": "la gola", "back": "the throat", "example": "Ho mal di gola da due giorni.", "exampleEn": "I've had a sore throat for two days." }
  ]
};
if (typeof module !== "undefined" && module.exports) module.exports = deck;
if (typeof window !== "undefined") { var WL = (window.WL = window.WL || {}); (WL.__decks = WL.__decks || []).push(deck); }
