// Agora deck. Free.
var deck = {
  "id": "bundled:portuguese",
  "name": "Portuguese 500",
  "lang": "pt",
  "cards": [
    { "id": "pt-0001", "front": "oi", "back": "hi", "example": "Oi, tudo bem?", "exampleEn": "Hi, how are you?" },
    { "id": "pt-0002", "front": "olá", "back": "hello", "example": "Olá, como você está?", "exampleEn": "Hello, how are you?" },
    { "id": "pt-0003", "front": "tchau", "back": "bye", "example": "Tchau, até logo!", "exampleEn": "Bye, see you soon!" },
    { "id": "pt-0004", "front": "bom dia", "back": "good morning", "example": "Bom dia, dormiu bem?", "exampleEn": "Good morning, did you sleep well?" },
    { "id": "pt-0005", "front": "boa tarde", "back": "good afternoon", "example": "Boa tarde, posso ajudar?", "exampleEn": "Good afternoon, can I help you?" },
    { "id": "pt-0006", "front": "boa noite", "back": "good evening / good night", "example": "Boa noite, durma bem.", "exampleEn": "Good night, sleep well." },
    { "id": "pt-0007", "front": "por favor", "back": "please", "example": "Um café, por favor.", "exampleEn": "A coffee, please." },
    { "id": "pt-0008", "front": "obrigado", "back": "thank you (male speaker)", "example": "Obrigado pela ajuda!", "exampleEn": "Thank you for the help!" },
    { "id": "pt-0009", "front": "obrigada", "back": "thank you (female speaker)", "example": "Obrigada pelo presente.", "exampleEn": "Thank you for the gift." },
    { "id": "pt-0010", "front": "de nada", "back": "you're welcome", "example": "De nada, foi um prazer.", "exampleEn": "You're welcome, it was a pleasure." },
    { "id": "pt-0011", "front": "com licença", "back": "excuse me", "example": "Com licença, posso passar?", "exampleEn": "Excuse me, may I get through?" },
    { "id": "pt-0012", "front": "desculpa", "back": "sorry", "example": "Desculpa pelo atraso.", "exampleEn": "Sorry for the delay." },
    { "id": "pt-0013", "front": "sim", "back": "yes", "example": "Sim, eu concordo.", "exampleEn": "Yes, I agree." },
    { "id": "pt-0014", "front": "não", "back": "no / not", "example": "Não, obrigado.", "exampleEn": "No, thank you." },
    { "id": "pt-0015", "front": "talvez", "back": "maybe", "example": "Talvez eu vá amanhã.", "exampleEn": "Maybe I'll go tomorrow." },
    { "id": "pt-0016", "front": "tudo bem", "back": "all good / okay", "example": "Tudo bem, não se preocupe.", "exampleEn": "It's okay, don't worry." },
    { "id": "pt-0017", "front": "até logo", "back": "see you later", "example": "Até logo, pessoal!", "exampleEn": "See you later, everyone!" },
    { "id": "pt-0018", "front": "até amanhã", "back": "see you tomorrow", "example": "Até amanhã na escola.", "exampleEn": "See you tomorrow at school." },
    { "id": "pt-0019", "front": "prazer", "back": "nice to meet you", "example": "Prazer em conhecer você.", "exampleEn": "Nice to meet you." },
    { "id": "pt-0020", "front": "bem-vindo", "back": "welcome", "example": "Bem-vindo ao Brasil!", "exampleEn": "Welcome to Brazil!" },
    { "id": "pt-0021", "front": "zero", "back": "zero", "example": "O placar está zero a zero.", "exampleEn": "The score is zero to zero." },
    { "id": "pt-0022", "front": "um", "back": "one", "example": "Eu quero um café.", "exampleEn": "I want a coffee." },
    { "id": "pt-0023", "front": "dois", "back": "two", "example": "Tenho dois irmãos.", "exampleEn": "I have two brothers." },
    { "id": "pt-0024", "front": "três", "back": "three", "example": "São três horas.", "exampleEn": "It's three o'clock." },
    { "id": "pt-0025", "front": "quatro", "back": "four", "example": "A mesa tem quatro cadeiras.", "exampleEn": "The table has four chairs." },
    { "id": "pt-0026", "front": "cinco", "back": "five", "example": "Comprei cinco maçãs.", "exampleEn": "I bought five apples." },
    { "id": "pt-0027", "front": "seis", "back": "six", "example": "Acordo às seis da manhã.", "exampleEn": "I wake up at six in the morning." },
    { "id": "pt-0028", "front": "sete", "back": "seven", "example": "A semana tem sete dias.", "exampleEn": "The week has seven days." },
    { "id": "pt-0029", "front": "oito", "back": "eight", "example": "Ela tem oito anos.", "exampleEn": "She is eight years old." },
    { "id": "pt-0030", "front": "nove", "back": "nine", "example": "Faltam nove minutos.", "exampleEn": "There are nine minutes left." },
    { "id": "pt-0031", "front": "dez", "back": "ten", "example": "Custou dez reais.", "exampleEn": "It cost ten reais." },
    { "id": "pt-0032", "front": "onze", "back": "eleven", "example": "O ônibus chega às onze.", "exampleEn": "The bus arrives at eleven." },
    { "id": "pt-0033", "front": "doze", "back": "twelve", "example": "Comprei doze ovos.", "exampleEn": "I bought a dozen eggs." },
    { "id": "pt-0034", "front": "treze", "back": "thirteen", "example": "Ele tem treze anos.", "exampleEn": "He is thirteen years old." },
    { "id": "pt-0035", "front": "quatorze", "back": "fourteen", "example": "São quatorze quilômetros.", "exampleEn": "It's fourteen kilometers." },
    { "id": "pt-0036", "front": "quinze", "back": "fifteen", "example": "Espere quinze minutos.", "exampleEn": "Wait fifteen minutes." },
    { "id": "pt-0037", "front": "dezesseis", "back": "sixteen", "example": "Ela faz dezesseis anos hoje.", "exampleEn": "She turns sixteen today." },
    { "id": "pt-0038", "front": "dezessete", "back": "seventeen", "example": "Tem dezessete pessoas aqui.", "exampleEn": "There are seventeen people here." },
    { "id": "pt-0039", "front": "dezoito", "back": "eighteen", "example": "Aos dezoito anos ele votou.", "exampleEn": "At eighteen he voted." },
    { "id": "pt-0040", "front": "dezenove", "back": "nineteen", "example": "O quarto fica no andar dezenove.", "exampleEn": "The room is on the nineteenth floor." },
    { "id": "pt-0041", "front": "vinte", "back": "twenty", "example": "Tenho vinte reais na carteira.", "exampleEn": "I have twenty reais in my wallet." },
    { "id": "pt-0042", "front": "trinta", "back": "thirty", "example": "A aula dura trinta minutos.", "exampleEn": "The class lasts thirty minutes." },
    { "id": "pt-0043", "front": "quarenta", "back": "forty", "example": "Ele tem quarenta anos.", "exampleEn": "He is forty years old." },
    { "id": "pt-0044", "front": "cinquenta", "back": "fifty", "example": "O ingresso custa cinquenta reais.", "exampleEn": "The ticket costs fifty reais." },
    { "id": "pt-0045", "front": "sessenta", "back": "sixty", "example": "Uma hora tem sessenta minutos.", "exampleEn": "An hour has sixty minutes." },
    { "id": "pt-0046", "front": "setenta", "back": "seventy", "example": "A vovó tem setenta anos.", "exampleEn": "Grandma is seventy years old." },
    { "id": "pt-0047", "front": "oitenta", "back": "eighty", "example": "O carro ia a oitenta por hora.", "exampleEn": "The car was going eighty kilometers per hour." },
    { "id": "pt-0048", "front": "noventa", "back": "ninety", "example": "Faltam noventa dias para as férias.", "exampleEn": "There are ninety days until vacation." },
    { "id": "pt-0049", "front": "cem", "back": "one hundred", "example": "Ganhei cem reais.", "exampleEn": "I earned a hundred reais." },
    { "id": "pt-0050", "front": "mil", "back": "one thousand", "example": "A passagem custa mil reais.", "exampleEn": "The ticket costs a thousand reais." },
    { "id": "pt-0051", "front": "segunda-feira", "back": "Monday", "example": "Trabalho na segunda-feira.", "exampleEn": "I work on Monday." },
    { "id": "pt-0052", "front": "terça-feira", "back": "Tuesday", "example": "Tenho aula na terça-feira.", "exampleEn": "I have class on Tuesday." },
    { "id": "pt-0053", "front": "quarta-feira", "back": "Wednesday", "example": "Vamos sair na quarta-feira.", "exampleEn": "We're going out on Wednesday." },
    { "id": "pt-0054", "front": "quinta-feira", "back": "Thursday", "example": "A reunião é na quinta-feira.", "exampleEn": "The meeting is on Thursday." },
    { "id": "pt-0055", "front": "sexta-feira", "back": "Friday", "example": "Adoro a sexta-feira.", "exampleEn": "I love Friday." },
    { "id": "pt-0056", "front": "sábado", "back": "Saturday", "example": "No sábado eu descanso.", "exampleEn": "On Saturday I rest." },
    { "id": "pt-0057", "front": "domingo", "back": "Sunday", "example": "Almoçamos juntos no domingo.", "exampleEn": "We have lunch together on Sunday." },
    { "id": "pt-0058", "front": "janeiro", "back": "January", "example": "Meu aniversário é em janeiro.", "exampleEn": "My birthday is in January." },
    { "id": "pt-0059", "front": "fevereiro", "back": "February", "example": "O Carnaval é em fevereiro.", "exampleEn": "Carnival is in February." },
    { "id": "pt-0060", "front": "março", "back": "March", "example": "As aulas começam em março.", "exampleEn": "Classes start in March." },
    { "id": "pt-0061", "front": "abril", "back": "April", "example": "Chove muito em abril.", "exampleEn": "It rains a lot in April." },
    { "id": "pt-0062", "front": "maio", "back": "May", "example": "Viajamos em maio.", "exampleEn": "We travel in May." },
    { "id": "pt-0063", "front": "junho", "back": "June", "example": "A festa junina é em junho.", "exampleEn": "The June festival is in June." },
    { "id": "pt-0064", "front": "julho", "back": "July", "example": "Faz frio em julho aqui.", "exampleEn": "It's cold in July here." },
    { "id": "pt-0065", "front": "agosto", "back": "August", "example": "As férias terminam em agosto.", "exampleEn": "Vacation ends in August." },
    { "id": "pt-0066", "front": "setembro", "back": "September", "example": "A primavera começa em setembro.", "exampleEn": "Spring begins in September." },
    { "id": "pt-0067", "front": "outubro", "back": "October", "example": "O evento é em outubro.", "exampleEn": "The event is in October." },
    { "id": "pt-0068", "front": "novembro", "back": "November", "example": "Visito a família em novembro.", "exampleEn": "I visit family in November." },
    { "id": "pt-0069", "front": "dezembro", "back": "December", "example": "O Natal é em dezembro.", "exampleEn": "Christmas is in December." },
    { "id": "pt-0070", "front": "hoje", "back": "today", "example": "Hoje está muito quente.", "exampleEn": "It's very hot today." },
    { "id": "pt-0071", "front": "amanhã", "back": "tomorrow", "example": "Amanhã eu viajo.", "exampleEn": "Tomorrow I'm traveling." },
    { "id": "pt-0072", "front": "ontem", "back": "yesterday", "example": "Ontem eu fui ao cinema.", "exampleEn": "Yesterday I went to the movies." },
    { "id": "pt-0073", "front": "agora", "back": "now", "example": "Preciso sair agora.", "exampleEn": "I need to leave now." },
    { "id": "pt-0074", "front": "depois", "back": "later / after", "example": "A gente conversa depois.", "exampleEn": "We'll talk later." },
    { "id": "pt-0075", "front": "antes", "back": "before", "example": "Cheguei antes de você.", "exampleEn": "I arrived before you." },
    { "id": "pt-0076", "front": "sempre", "back": "always", "example": "Eu sempre tomo café.", "exampleEn": "I always drink coffee." },
    { "id": "pt-0077", "front": "nunca", "back": "never", "example": "Nunca fui ao Japão.", "exampleEn": "I've never been to Japan." },
    { "id": "pt-0078", "front": "às vezes", "back": "sometimes", "example": "Às vezes eu corro de manhã.", "exampleEn": "Sometimes I run in the morning." },
    { "id": "pt-0079", "front": "cedo", "back": "early", "example": "Acordei muito cedo hoje.", "exampleEn": "I woke up very early today." },
    { "id": "pt-0080", "front": "tarde", "back": "late", "example": "Ele chegou tarde na festa.", "exampleEn": "He arrived late to the party." },
    { "id": "pt-0081", "front": "a hora", "back": "the hour / time", "example": "Que horas são agora?", "exampleEn": "What time is it now?" },
    { "id": "pt-0082", "front": "o dia", "back": "the day", "example": "Tenha um bom dia!", "exampleEn": "Have a good day!" },
    { "id": "pt-0083", "front": "a semana", "back": "the week", "example": "A semana passou rápido.", "exampleEn": "The week went by fast." },
    { "id": "pt-0084", "front": "o mês", "back": "the month", "example": "Esse mês foi difícil.", "exampleEn": "This month was difficult." },
    { "id": "pt-0085", "front": "o ano", "back": "the year", "example": "Feliz ano novo!", "exampleEn": "Happy New Year!" },
    { "id": "pt-0086", "front": "o minuto", "back": "the minute", "example": "Espere um minuto, por favor.", "exampleEn": "Wait a minute, please." },
    { "id": "pt-0087", "front": "a manhã", "back": "the morning", "example": "Estudo de manhã.", "exampleEn": "I study in the morning." },
    { "id": "pt-0088", "front": "a noite", "back": "the night", "example": "A noite está fria.", "exampleEn": "The night is cold." },
    { "id": "pt-0089", "front": "quem", "back": "who", "example": "Quem é aquele homem?", "exampleEn": "Who is that man?" },
    { "id": "pt-0090", "front": "o que", "back": "what", "example": "O que você quer comer?", "exampleEn": "What do you want to eat?" },
    { "id": "pt-0091", "front": "onde", "back": "where", "example": "Onde fica o banheiro?", "exampleEn": "Where is the bathroom?" },
    { "id": "pt-0092", "front": "quando", "back": "when", "example": "Quando você chega?", "exampleEn": "When do you arrive?" },
    { "id": "pt-0093", "front": "por que", "back": "why", "example": "Por que você está triste?", "exampleEn": "Why are you sad?" },
    { "id": "pt-0094", "front": "como", "back": "how", "example": "Como você está?", "exampleEn": "How are you?" },
    { "id": "pt-0095", "front": "quanto", "back": "how much", "example": "Quanto custa isso?", "exampleEn": "How much does this cost?" },
    { "id": "pt-0096", "front": "qual", "back": "which", "example": "Qual é o seu nome?", "exampleEn": "What is your name?" },
    { "id": "pt-0097", "front": "eu", "back": "I", "example": "Eu gosto de música.", "exampleEn": "I like music." },
    { "id": "pt-0098", "front": "você", "back": "you", "example": "Você fala inglês?", "exampleEn": "Do you speak English?" },
    { "id": "pt-0099", "front": "ele", "back": "he", "example": "Ele é meu amigo.", "exampleEn": "He is my friend." },
    { "id": "pt-0100", "front": "ela", "back": "she", "example": "Ela trabalha no banco.", "exampleEn": "She works at the bank." },
    { "id": "pt-0101", "front": "nós", "back": "we", "example": "Nós vamos à praia.", "exampleEn": "We're going to the beach." },
    { "id": "pt-0102", "front": "eles", "back": "they (masc.)", "example": "Eles jogam futebol.", "exampleEn": "They play soccer." },
    { "id": "pt-0103", "front": "elas", "back": "they (fem.)", "example": "Elas estudam juntas.", "exampleEn": "They study together." },
    { "id": "pt-0104", "front": "meu", "back": "my (masc.)", "example": "Esse é o meu carro.", "exampleEn": "This is my car." },
    { "id": "pt-0105", "front": "minha", "back": "my (fem.)", "example": "Essa é a minha casa.", "exampleEn": "This is my house." },
    { "id": "pt-0106", "front": "seu", "back": "your (masc.)", "example": "Qual é o seu nome?", "exampleEn": "What is your name?" },
    { "id": "pt-0107", "front": "isso", "back": "this / that", "example": "Isso é muito bom.", "exampleEn": "This is very good." },
    { "id": "pt-0108", "front": "este", "back": "this (masc.)", "example": "Este livro é meu.", "exampleEn": "This book is mine." },
    { "id": "pt-0109", "front": "aquele", "back": "that (over there)", "example": "Aquele prédio é alto.", "exampleEn": "That building is tall." },
    { "id": "pt-0110", "front": "ser", "back": "to be (permanent)", "example": "Eu sou brasileiro.", "exampleEn": "I am Brazilian." },
    { "id": "pt-0111", "front": "estar", "back": "to be (temporary)", "example": "Eu estou cansado hoje.", "exampleEn": "I am tired today." },
    { "id": "pt-0112", "front": "ter", "back": "to have", "example": "Eu tenho dois gatos.", "exampleEn": "I have two cats." },
    { "id": "pt-0113", "front": "fazer", "back": "to do / to make", "example": "O que você vai fazer?", "exampleEn": "What are you going to do?" },
    { "id": "pt-0114", "front": "ir", "back": "to go", "example": "Eu vou ao mercado.", "exampleEn": "I'm going to the market." },
    { "id": "pt-0115", "front": "vir", "back": "to come", "example": "Você vem à festa?", "exampleEn": "Are you coming to the party?" },
    { "id": "pt-0116", "front": "querer", "back": "to want", "example": "Eu quero um suco.", "exampleEn": "I want a juice." },
    { "id": "pt-0117", "front": "poder", "back": "can / to be able to", "example": "Você pode me ajudar?", "exampleEn": "Can you help me?" },
    { "id": "pt-0118", "front": "saber", "back": "to know (facts)", "example": "Eu não sei a resposta.", "exampleEn": "I don't know the answer." },
    { "id": "pt-0119", "front": "conhecer", "back": "to know (people/places)", "example": "Quero conhecer o Rio.", "exampleEn": "I want to visit Rio." },
    { "id": "pt-0120", "front": "ver", "back": "to see", "example": "Eu vejo um pássaro.", "exampleEn": "I see a bird." },
    { "id": "pt-0121", "front": "ouvir", "back": "to hear / to listen", "example": "Eu gosto de ouvir música.", "exampleEn": "I like to listen to music." },
    { "id": "pt-0122", "front": "falar", "back": "to speak / to talk", "example": "Eu falo português.", "exampleEn": "I speak Portuguese." },
    { "id": "pt-0123", "front": "dizer", "back": "to say / to tell", "example": "O que você quer dizer?", "exampleEn": "What do you mean?" },
    { "id": "pt-0124", "front": "comer", "back": "to eat", "example": "Eu gosto de comer pizza.", "exampleEn": "I like to eat pizza." },
    { "id": "pt-0125", "front": "beber", "back": "to drink", "example": "Eu vou beber água.", "exampleEn": "I'm going to drink water." },
    { "id": "pt-0126", "front": "dormir", "back": "to sleep", "example": "Eu durmo oito horas.", "exampleEn": "I sleep eight hours." },
    { "id": "pt-0127", "front": "acordar", "back": "to wake up", "example": "Eu acordo às sete.", "exampleEn": "I wake up at seven." },
    { "id": "pt-0128", "front": "trabalhar", "back": "to work", "example": "Eu trabalho de casa.", "exampleEn": "I work from home." },
    { "id": "pt-0129", "front": "estudar", "back": "to study", "example": "Eu estudo português.", "exampleEn": "I study Portuguese." },
    { "id": "pt-0130", "front": "gostar", "back": "to like", "example": "Eu gosto de você.", "exampleEn": "I like you." },
    { "id": "pt-0131", "front": "precisar", "back": "to need", "example": "Eu preciso de ajuda.", "exampleEn": "I need help." },
    { "id": "pt-0132", "front": "comprar", "back": "to buy", "example": "Eu vou comprar pão.", "exampleEn": "I'm going to buy bread." },
    { "id": "pt-0133", "front": "pagar", "back": "to pay", "example": "Eu vou pagar a conta.", "exampleEn": "I'm going to pay the bill." },
    { "id": "pt-0134", "front": "andar", "back": "to walk", "example": "Gosto de andar no parque.", "exampleEn": "I like walking in the park." },
    { "id": "pt-0135", "front": "morar", "back": "to live (reside)", "example": "Eu moro em São Paulo.", "exampleEn": "I live in São Paulo." },
    { "id": "pt-0136", "front": "escrever", "back": "to write", "example": "Eu vou escrever uma carta.", "exampleEn": "I'm going to write a letter." },
    { "id": "pt-0137", "front": "ler", "back": "to read", "example": "Eu gosto de ler livros.", "exampleEn": "I like to read books." },
    { "id": "pt-0138", "front": "abrir", "back": "to open", "example": "Pode abrir a janela?", "exampleEn": "Can you open the window?" },
    { "id": "pt-0139", "front": "fechar", "back": "to close", "example": "Feche a porta, por favor.", "exampleEn": "Close the door, please." },
    { "id": "pt-0140", "front": "ajudar", "back": "to help", "example": "Posso ajudar você?", "exampleEn": "Can I help you?" },
    { "id": "pt-0141", "front": "a água", "back": "the water", "example": "Eu bebo muita água.", "exampleEn": "I drink a lot of water." },
    { "id": "pt-0142", "front": "o café", "back": "the coffee", "example": "O café está quente.", "exampleEn": "The coffee is hot." },
    { "id": "pt-0143", "front": "o pão", "back": "the bread", "example": "Comprei pão fresco.", "exampleEn": "I bought fresh bread." },
    { "id": "pt-0144", "front": "o leite", "back": "the milk", "example": "O leite está na geladeira.", "exampleEn": "The milk is in the fridge." },
    { "id": "pt-0145", "front": "o arroz", "back": "the rice", "example": "Gosto de arroz com feijão.", "exampleEn": "I like rice and beans." },
    { "id": "pt-0146", "front": "a carne", "back": "the meat", "example": "A carne está saborosa.", "exampleEn": "The meat is flavorful." },
    { "id": "pt-0147", "front": "a fruta", "back": "the fruit", "example": "Eu como fruta toda manhã.", "exampleEn": "I eat fruit every morning." },
    { "id": "pt-0148", "front": "o ovo", "back": "the egg", "example": "Comi um ovo no café.", "exampleEn": "I had an egg at breakfast." },
    { "id": "pt-0149", "front": "o suco", "back": "the juice", "example": "Quero um suco de laranja.", "exampleEn": "I want an orange juice." },
    { "id": "pt-0150", "front": "a comida", "back": "the food", "example": "A comida está deliciosa.", "exampleEn": "The food is delicious." },
    { "id": "pt-0151", "front": "o açúcar", "back": "the sugar", "example": "Não uso açúcar no café.", "exampleEn": "I don't use sugar in my coffee." },
    { "id": "pt-0152", "front": "o sal", "back": "the salt", "example": "Falta um pouco de sal.", "exampleEn": "It needs a little more salt." },
    { "id": "pt-0153", "front": "a família", "back": "the family", "example": "Amo a minha família.", "exampleEn": "I love my family." },
    { "id": "pt-0154", "front": "a mãe", "back": "the mother", "example": "Minha mãe cozinha bem.", "exampleEn": "My mother cooks well." },
    { "id": "pt-0155", "front": "o pai", "back": "the father", "example": "Meu pai trabalha muito.", "exampleEn": "My father works a lot." },
    { "id": "pt-0156", "front": "o filho", "back": "the son", "example": "O filho deles é alto.", "exampleEn": "Their son is tall." },
    { "id": "pt-0157", "front": "a filha", "back": "the daughter", "example": "A filha dela tem cinco anos.", "exampleEn": "Her daughter is five years old." },
    { "id": "pt-0158", "front": "o irmão", "back": "the brother", "example": "Meu irmão mora longe.", "exampleEn": "My brother lives far away." },
    { "id": "pt-0159", "front": "a irmã", "back": "the sister", "example": "Minha irmã é médica.", "exampleEn": "My sister is a doctor." },
    { "id": "pt-0160", "front": "o amigo", "back": "the friend (male)", "example": "Ele é meu melhor amigo.", "exampleEn": "He is my best friend." },
    { "id": "pt-0161", "front": "a amiga", "back": "the friend (female)", "example": "Ela é minha amiga de escola.", "exampleEn": "She is my friend from school." },
    { "id": "pt-0162", "front": "o homem", "back": "the man", "example": "O homem está esperando.", "exampleEn": "The man is waiting." },
    { "id": "pt-0163", "front": "a mulher", "back": "the woman", "example": "A mulher é professora.", "exampleEn": "The woman is a teacher." },
    { "id": "pt-0164", "front": "a criança", "back": "the child", "example": "A criança está brincando.", "exampleEn": "The child is playing." },
    { "id": "pt-0165", "front": "a casa", "back": "the house / home", "example": "Vou para casa agora.", "exampleEn": "I'm going home now." },
    { "id": "pt-0166", "front": "a porta", "back": "the door", "example": "Feche a porta, por favor.", "exampleEn": "Close the door, please." },
    { "id": "pt-0167", "front": "a janela", "back": "the window", "example": "Abra a janela.", "exampleEn": "Open the window." },
    { "id": "pt-0168", "front": "a mesa", "back": "the table", "example": "A comida está na mesa.", "exampleEn": "The food is on the table." },
    { "id": "pt-0169", "front": "a cadeira", "back": "the chair", "example": "Sente-se na cadeira.", "exampleEn": "Sit down in the chair." },
    { "id": "pt-0170", "front": "a cama", "back": "the bed", "example": "A cama é confortável.", "exampleEn": "The bed is comfortable." },
    { "id": "pt-0171", "front": "o banheiro", "back": "the bathroom", "example": "Onde fica o banheiro?", "exampleEn": "Where is the bathroom?" },
    { "id": "pt-0172", "front": "a cozinha", "back": "the kitchen", "example": "Ela está na cozinha.", "exampleEn": "She is in the kitchen." },
    { "id": "pt-0173", "front": "o quarto", "back": "the bedroom", "example": "Meu quarto é pequeno.", "exampleEn": "My room is small." },
    { "id": "pt-0174", "front": "a chave", "back": "the key", "example": "Perdi a chave de casa.", "exampleEn": "I lost my house key." },
    { "id": "pt-0175", "front": "a cabeça", "back": "the head", "example": "Minha cabeça dói.", "exampleEn": "My head hurts." },
    { "id": "pt-0176", "front": "a mão", "back": "the hand", "example": "Lave a mão antes de comer.", "exampleEn": "Wash your hands before eating." },
    { "id": "pt-0177", "front": "o olho", "back": "the eye", "example": "Ela tem olho castanho.", "exampleEn": "She has brown eyes." },
    { "id": "pt-0178", "front": "o pé", "back": "the foot", "example": "Meu pé está doendo.", "exampleEn": "My foot is hurting." },
    { "id": "pt-0179", "front": "a boca", "back": "the mouth", "example": "Abra a boca, por favor.", "exampleEn": "Open your mouth, please." },
    { "id": "pt-0180", "front": "o braço", "back": "the arm", "example": "Ele quebrou o braço.", "exampleEn": "He broke his arm." },
    { "id": "pt-0181", "front": "o coração", "back": "the heart", "example": "Meu coração bate forte.", "exampleEn": "My heart beats fast." },
    { "id": "pt-0182", "front": "a cidade", "back": "the city", "example": "Esta cidade é grande.", "exampleEn": "This city is big." },
    { "id": "pt-0183", "front": "a rua", "back": "the street", "example": "A rua está movimentada.", "exampleEn": "The street is busy." },
    { "id": "pt-0184", "front": "a loja", "back": "the store", "example": "A loja abre às nove.", "exampleEn": "The store opens at nine." },
    { "id": "pt-0185", "front": "o mercado", "back": "the market", "example": "Vou ao mercado comprar frutas.", "exampleEn": "I'm going to the market to buy fruit." },
    { "id": "pt-0186", "front": "a escola", "back": "the school", "example": "As crianças vão à escola.", "exampleEn": "The children go to school." },
    { "id": "pt-0187", "front": "o trabalho", "back": "the work / job", "example": "Gosto do meu trabalho.", "exampleEn": "I like my job." },
    { "id": "pt-0188", "front": "o hospital", "back": "the hospital", "example": "Ela está no hospital.", "exampleEn": "She is in the hospital." },
    { "id": "pt-0189", "front": "o restaurante", "back": "the restaurant", "example": "O restaurante é ótimo.", "exampleEn": "The restaurant is great." },
    { "id": "pt-0190", "front": "o banco", "back": "the bank", "example": "Preciso ir ao banco.", "exampleEn": "I need to go to the bank." },
    { "id": "pt-0191", "front": "a praia", "back": "the beach", "example": "Adoro ir à praia.", "exampleEn": "I love going to the beach." },
    { "id": "pt-0192", "front": "o parque", "back": "the park", "example": "As crianças brincam no parque.", "exampleEn": "The children play in the park." },
    { "id": "pt-0193", "front": "o dinheiro", "back": "the money", "example": "Não tenho dinheiro hoje.", "exampleEn": "I don't have any money today." },
    { "id": "pt-0194", "front": "o telefone", "back": "the telephone", "example": "O telefone está tocando.", "exampleEn": "The phone is ringing." },
    { "id": "pt-0195", "front": "o celular", "back": "the cell phone", "example": "Meu celular descarregou.", "exampleEn": "My phone died." },
    { "id": "pt-0196", "front": "o computador", "back": "the computer", "example": "Trabalho no computador.", "exampleEn": "I work on the computer." },
    { "id": "pt-0197", "front": "o livro", "back": "the book", "example": "Este livro é interessante.", "exampleEn": "This book is interesting." },
    { "id": "pt-0198", "front": "o carro", "back": "the car", "example": "Meu carro é vermelho.", "exampleEn": "My car is red." },
    { "id": "pt-0199", "front": "o ônibus", "back": "the bus", "example": "Vou pegar o ônibus.", "exampleEn": "I'm going to take the bus." },
    { "id": "pt-0200", "front": "o trem", "back": "the train", "example": "O trem está atrasado.", "exampleEn": "The train is late." },
    { "id": "pt-0201", "front": "o avião", "back": "the airplane", "example": "O avião vai decolar.", "exampleEn": "The plane is about to take off." },
    { "id": "pt-0202", "front": "a bicicleta", "back": "the bicycle", "example": "Ando de bicicleta no parque.", "exampleEn": "I ride my bike in the park." },
    { "id": "pt-0203", "front": "a árvore", "back": "the tree", "example": "A árvore é muito alta.", "exampleEn": "The tree is very tall." },
    { "id": "pt-0204", "front": "a flor", "back": "the flower", "example": "Ela me deu uma flor.", "exampleEn": "She gave me a flower." },
    { "id": "pt-0205", "front": "o sol", "back": "the sun", "example": "O sol está forte hoje.", "exampleEn": "The sun is strong today." },
    { "id": "pt-0206", "front": "a lua", "back": "the moon", "example": "A lua está linda esta noite.", "exampleEn": "The moon is beautiful tonight." },
    { "id": "pt-0207", "front": "o céu", "back": "the sky", "example": "O céu está azul.", "exampleEn": "The sky is blue." },
    { "id": "pt-0208", "front": "o mar", "back": "the sea", "example": "O mar está calmo.", "exampleEn": "The sea is calm." },
    { "id": "pt-0209", "front": "o cachorro", "back": "the dog", "example": "Meu cachorro é muito amigável.", "exampleEn": "My dog is very friendly." },
    { "id": "pt-0210", "front": "o gato", "back": "the cat", "example": "O gato está dormindo.", "exampleEn": "The cat is sleeping." },
    { "id": "pt-0211", "front": "o pássaro", "back": "the bird", "example": "O pássaro está cantando.", "exampleEn": "The bird is singing." },
    { "id": "pt-0212", "front": "a chuva", "back": "the rain", "example": "A chuva começou cedo.", "exampleEn": "The rain started early." },
    { "id": "pt-0213", "front": "o vento", "back": "the wind", "example": "O vento está forte.", "exampleEn": "The wind is strong." },
    { "id": "pt-0214", "front": "o frio", "back": "the cold", "example": "Estou com frio.", "exampleEn": "I'm cold." },
    { "id": "pt-0215", "front": "o calor", "back": "the heat", "example": "Está fazendo muito calor.", "exampleEn": "It's very hot." },
    { "id": "pt-0216", "front": "o tempo", "back": "the weather / time", "example": "Como está o tempo hoje?", "exampleEn": "What's the weather like today?" },
    { "id": "pt-0217", "front": "grande", "back": "big / large", "example": "A casa é muito grande.", "exampleEn": "The house is very big." },
    { "id": "pt-0218", "front": "pequeno", "back": "small", "example": "O gato é pequeno.", "exampleEn": "The cat is small." },
    { "id": "pt-0219", "front": "bom", "back": "good", "example": "Este filme é bom.", "exampleEn": "This movie is good." },
    { "id": "pt-0220", "front": "ruim", "back": "bad", "example": "O dia foi ruim.", "exampleEn": "The day was bad." },
    { "id": "pt-0221", "front": "bonito", "back": "beautiful / handsome", "example": "Que dia bonito!", "exampleEn": "What a beautiful day!" },
    { "id": "pt-0222", "front": "feio", "back": "ugly", "example": "O prédio é feio.", "exampleEn": "The building is ugly." },
    { "id": "pt-0223", "front": "novo", "back": "new", "example": "Comprei um carro novo.", "exampleEn": "I bought a new car." },
    { "id": "pt-0224", "front": "velho", "back": "old", "example": "Este livro é muito velho.", "exampleEn": "This book is very old." },
    { "id": "pt-0225", "front": "quente", "back": "hot", "example": "O café está quente.", "exampleEn": "The coffee is hot." },
    { "id": "pt-0226", "front": "feliz", "back": "happy", "example": "Estou muito feliz hoje.", "exampleEn": "I'm very happy today." },
    { "id": "pt-0227", "front": "triste", "back": "sad", "example": "Ela ficou triste com a notícia.", "exampleEn": "She was sad about the news." },
    { "id": "pt-0228", "front": "fácil", "back": "easy", "example": "A prova foi fácil.", "exampleEn": "The test was easy." },
    { "id": "pt-0229", "front": "difícil", "back": "difficult", "example": "O exercício é difícil.", "exampleEn": "The exercise is difficult." },
    { "id": "pt-0230", "front": "caro", "back": "expensive", "example": "Este restaurante é caro.", "exampleEn": "This restaurant is expensive." },
    { "id": "pt-0231", "front": "barato", "back": "cheap", "example": "Achei um celular barato.", "exampleEn": "I found a cheap phone." },
    { "id": "pt-0232", "front": "rápido", "back": "fast / quick", "example": "O trem é muito rápido.", "exampleEn": "The train is very fast." },
    { "id": "pt-0233", "front": "branco", "back": "white", "example": "Ela usa um vestido branco.", "exampleEn": "She's wearing a white dress." },
    { "id": "pt-0234", "front": "preto", "back": "black", "example": "Meu gato é preto.", "exampleEn": "My cat is black." },
    { "id": "pt-0235", "front": "vermelho", "back": "red", "example": "O carro é vermelho.", "exampleEn": "The car is red." },
    { "id": "pt-0236", "front": "azul", "back": "blue", "example": "O céu está azul.", "exampleEn": "The sky is blue." },
    { "id": "pt-0237", "front": "verde", "back": "green", "example": "A folha é verde.", "exampleEn": "The leaf is green." },
    { "id": "pt-0238", "front": "amarelo", "back": "yellow", "example": "O sol é amarelo.", "exampleEn": "The sun is yellow." },
    { "id": "pt-0239", "front": "a cor", "back": "the color", "example": "Qual é a sua cor favorita?", "exampleEn": "What is your favorite color?" },
    { "id": "pt-0240", "front": "aqui", "back": "here", "example": "Venha aqui, por favor.", "exampleEn": "Come here, please." },
    { "id": "pt-0241", "front": "ali", "back": "there", "example": "O carro está ali.", "exampleEn": "The car is over there." },
    { "id": "pt-0242", "front": "perto", "back": "near / close", "example": "A loja fica perto daqui.", "exampleEn": "The store is nearby." },
    { "id": "pt-0243", "front": "longe", "back": "far", "example": "A praia fica longe.", "exampleEn": "The beach is far away." },
    { "id": "pt-0244", "front": "à direita", "back": "to the right", "example": "Vire à direita na esquina.", "exampleEn": "Turn right at the corner." },
    { "id": "pt-0245", "front": "à esquerda", "back": "to the left", "example": "A padaria fica à esquerda.", "exampleEn": "The bakery is on the left." },
    { "id": "pt-0246", "front": "em cima", "back": "on top / above", "example": "O livro está em cima da mesa.", "exampleEn": "The book is on top of the table." },
    { "id": "pt-0247", "front": "embaixo", "back": "under / below", "example": "O gato está embaixo da cama.", "exampleEn": "The cat is under the bed." },
    { "id": "pt-0248", "front": "muito", "back": "very / a lot", "example": "Eu gosto muito de você.", "exampleEn": "I like you a lot." },
    { "id": "pt-0249", "front": "pouco", "back": "little / few", "example": "Falo um pouco de português.", "exampleEn": "I speak a little Portuguese." },
    { "id": "pt-0250", "front": "também", "back": "also / too", "example": "Eu também quero ir.", "exampleEn": "I want to go too." },
    { "id": "pt-0251", "front": "o cardápio", "back": "menu", "example": "Você pode me trazer o cardápio, por favor?", "exampleEn": "Can you bring me the menu, please?" },
    { "id": "pt-0252", "front": "o aeroporto", "back": "airport", "example": "O aeroporto fica longe do centro.", "exampleEn": "The airport is far from the city center." },
    { "id": "pt-0253", "front": "o emprego", "back": "job, employment", "example": "Ela encontrou um emprego novo esta semana.", "exampleEn": "She found a new job this week." },
    { "id": "pt-0254", "front": "o apartamento", "back": "apartment", "example": "Eu moro em um apartamento pequeno.", "exampleEn": "I live in a small apartment." },
    { "id": "pt-0255", "front": "o nariz", "back": "the nose", "example": "Meu nariz está entupido hoje.", "exampleEn": "My nose is stuffy today." },
    { "id": "pt-0256", "front": "o garçom", "back": "waiter", "example": "O garçom trouxe a conta rapidamente.", "exampleEn": "The waiter brought the bill quickly." },
    { "id": "pt-0257", "front": "a estação", "back": "station", "example": "A estação de trem é muito movimentada.", "exampleEn": "The train station is very busy." },
    { "id": "pt-0258", "front": "o salário", "back": "salary, wage", "example": "Meu salário aumentou este ano.", "exampleEn": "My salary increased this year." },
    { "id": "pt-0259", "front": "o sofá", "back": "sofa, couch", "example": "O gato dorme no sofá.", "exampleEn": "The cat sleeps on the sofa." },
    { "id": "pt-0260", "front": "o ouvido", "back": "the ear", "example": "Ela tem dor no ouvido direito.", "exampleEn": "She has pain in her right ear." },
    { "id": "pt-0261", "front": "a conta", "back": "the bill, the check", "example": "Pode trazer a conta, por favor?", "exampleEn": "Can you bring the bill, please?" },
    { "id": "pt-0262", "front": "o metrô", "back": "subway / metro", "example": "Eu pego o metrô todo dia.", "exampleEn": "I take the subway every day." },
    { "id": "pt-0263", "front": "o chefe", "back": "boss, manager", "example": "O chefe chegou cedo hoje.", "exampleEn": "The boss arrived early today." },
    { "id": "pt-0264", "front": "a geladeira", "back": "refrigerator", "example": "O leite está na geladeira.", "exampleEn": "The milk is in the refrigerator." },
    { "id": "pt-0265", "front": "o joelho", "back": "the knee", "example": "Eu machuquei o joelho correndo.", "exampleEn": "I hurt my knee while running." },
    { "id": "pt-0266", "front": "a reserva", "back": "reservation", "example": "Fiz uma reserva para as oito.", "exampleEn": "I made a reservation for eight o'clock." },
    { "id": "pt-0267", "front": "o táxi", "back": "taxi", "example": "Vamos chamar um táxi agora.", "exampleEn": "Let's call a taxi now." },
    { "id": "pt-0268", "front": "a empresa", "back": "company, firm", "example": "Ele trabalha em uma empresa grande.", "exampleEn": "He works at a large company." },
    { "id": "pt-0269", "front": "o fogão", "back": "stove, cooker", "example": "Ela cozinha no fogão todos os dias.", "exampleEn": "She cooks on the stove every day." },
    { "id": "pt-0270", "front": "o ombro", "back": "the shoulder", "example": "Ele sentiu dor no ombro esquerdo.", "exampleEn": "He felt pain in his left shoulder." },
    { "id": "pt-0271", "front": "o prato", "back": "dish, plate", "example": "O prato do dia é frango grelhado.", "exampleEn": "The dish of the day is grilled chicken." },
    { "id": "pt-0272", "front": "o passaporte", "back": "passport", "example": "Não esqueça o seu passaporte.", "exampleEn": "Don't forget your passport." },
    { "id": "pt-0273", "front": "o contrato", "back": "contract", "example": "Ela assinou o contrato ontem.", "exampleEn": "She signed the contract yesterday." },
    { "id": "pt-0274", "front": "o armário", "back": "wardrobe, cabinet", "example": "As roupas estão no armário.", "exampleEn": "The clothes are in the wardrobe." },
    { "id": "pt-0275", "front": "o pescoço", "back": "the neck", "example": "Meu pescoço está rígido hoje.", "exampleEn": "My neck is stiff today." },
    { "id": "pt-0276", "front": "a sobremesa", "back": "dessert", "example": "Você quer sobremesa depois do almoço?", "exampleEn": "Do you want dessert after lunch?" },
    { "id": "pt-0277", "front": "a mala", "back": "suitcase", "example": "A mala está muito pesada.", "exampleEn": "The suitcase is very heavy." },
    { "id": "pt-0278", "front": "a reunião", "back": "meeting", "example": "A reunião começa às nove da manhã.", "exampleEn": "The meeting starts at nine in the morning." },
    { "id": "pt-0279", "front": "o espelho", "back": "mirror", "example": "Eu me olho no espelho de manhã.", "exampleEn": "I look at myself in the mirror in the morning." },
    { "id": "pt-0280", "front": "o estômago", "back": "the stomach", "example": "Meu estômago está doendo muito.", "exampleEn": "My stomach hurts a lot." },
    { "id": "pt-0281", "front": "o almoço", "back": "lunch", "example": "O almoço aqui é muito gostoso.", "exampleEn": "The lunch here is very tasty." },
    { "id": "pt-0282", "front": "a viagem", "back": "trip / journey", "example": "A viagem durou seis horas.", "exampleEn": "The trip lasted six hours." },
    { "id": "pt-0283", "front": "o colega", "back": "colleague, coworker", "example": "Meu colega me ajudou com o projeto.", "exampleEn": "My colleague helped me with the project." },
    { "id": "pt-0284", "front": "a toalha", "back": "towel", "example": "Preciso de uma toalha limpa.", "exampleEn": "I need a clean towel." },
    { "id": "pt-0285", "front": "as costas", "back": "the back", "example": "Ele tem dor nas costas toda manhã.", "exampleEn": "He has back pain every morning." },
    { "id": "pt-0286", "front": "o jantar", "back": "dinner", "example": "Vamos jantar fora esta noite.", "exampleEn": "We are going to have dinner out tonight." },
    { "id": "pt-0287", "front": "o bilhete", "back": "ticket", "example": "Preciso comprar um bilhete de volta.", "exampleEn": "I need to buy a return ticket." },
    { "id": "pt-0288", "front": "o escritório", "back": "office", "example": "Ela trabalha no escritório todo dia.", "exampleEn": "She works in the office every day." },
    { "id": "pt-0289", "front": "o tapete", "back": "rug, carpet", "example": "O tapete da sala é azul.", "exampleEn": "The living room rug is blue." },
    { "id": "pt-0290", "front": "a perna", "back": "the leg", "example": "Ela quebrou a perna no acidente.", "exampleEn": "She broke her leg in the accident." },
    { "id": "pt-0291", "front": "o café da manhã", "back": "breakfast", "example": "O café da manhã é servido às sete.", "exampleEn": "Breakfast is served at seven." },
    { "id": "pt-0292", "front": "a passagem", "back": "fare / ticket (travel)", "example": "A passagem de avião foi barata.", "exampleEn": "The plane ticket was cheap." },
    { "id": "pt-0293", "front": "o negócio", "back": "business, deal", "example": "Ele abriu um negócio próprio ano passado.", "exampleEn": "He opened his own business last year." },
    { "id": "pt-0294", "front": "a sala de estar", "back": "living room", "example": "A família se reúne na sala de estar.", "exampleEn": "The family gathers in the living room." },
    { "id": "pt-0295", "front": "o dedo", "back": "the finger", "example": "Ela cortou o dedo com a faca.", "exampleEn": "She cut her finger with the knife." },
    { "id": "pt-0296", "front": "o lanche", "back": "snack", "example": "Comi um lanche rápido entre as aulas.", "exampleEn": "I ate a quick snack between classes." },
    { "id": "pt-0297", "front": "o hotel", "back": "hotel", "example": "O hotel fica perto da praia.", "exampleEn": "The hotel is near the beach." },
    { "id": "pt-0298", "front": "o cliente", "back": "client, customer", "example": "O cliente ligou para reclamar.", "exampleEn": "The customer called to complain." },
    { "id": "pt-0299", "front": "o quintal", "back": "backyard", "example": "As crianças brincam no quintal.", "exampleEn": "The children play in the backyard." },
    { "id": "pt-0300", "front": "o pulmão", "back": "the lung", "example": "Fumar faz mal aos pulmões.", "exampleEn": "Smoking is bad for the lungs." },
    { "id": "pt-0301", "front": "a receita", "back": "recipe", "example": "Ela me ensinou a receita do bolo.", "exampleEn": "She taught me the cake recipe." },
    { "id": "pt-0302", "front": "o quarto de hotel", "back": "hotel room", "example": "O quarto de hotel tem vista para o mar.", "exampleEn": "The hotel room has a sea view." },
    { "id": "pt-0303", "front": "a fatura", "back": "invoice, bill", "example": "Preciso enviar a fatura para o cliente.", "exampleEn": "I need to send the invoice to the client." },
    { "id": "pt-0304", "front": "o avô", "back": "grandfather", "example": "Meu avô conta histórias incríveis.", "exampleEn": "My grandfather tells amazing stories." },
    { "id": "pt-0305", "front": "a saúde", "back": "health", "example": "A saúde é mais importante que o dinheiro.", "exampleEn": "Health is more important than money." },
    { "id": "pt-0306", "front": "o ingrediente", "back": "ingredient", "example": "O ingrediente principal é o alho.", "exampleEn": "The main ingredient is garlic." },
    { "id": "pt-0307", "front": "a recepção", "back": "reception / front desk", "example": "Deixe a chave na recepção.", "exampleEn": "Leave the key at reception." },
    { "id": "pt-0308", "front": "o lucro", "back": "profit", "example": "A empresa teve lucro este trimestre.", "exampleEn": "The company made a profit this quarter." },
    { "id": "pt-0309", "front": "a avó", "back": "grandmother", "example": "A avó faz bolo todo domingo.", "exampleEn": "Grandma makes cake every Sunday." },
    { "id": "pt-0310", "front": "a dor", "back": "pain / ache", "example": "Eu sinto uma dor forte na cabeça.", "exampleEn": "I feel a strong pain in my head." },
    { "id": "pt-0311", "front": "o frango", "back": "chicken", "example": "Prefiro frango em vez de carne vermelha.", "exampleEn": "I prefer chicken instead of red meat." },
    { "id": "pt-0312", "front": "a saída", "back": "exit / departure", "example": "A saída do metrô fica ali.", "exampleEn": "The metro exit is right there." },
    { "id": "pt-0313", "front": "o prejuízo", "back": "loss (financial)", "example": "O negócio teve prejuízo no primeiro ano.", "exampleEn": "The business had a loss in the first year." },
    { "id": "pt-0314", "front": "o marido", "back": "husband", "example": "O marido dela trabalha no hospital.", "exampleEn": "Her husband works at the hospital." },
    { "id": "pt-0315", "front": "a febre", "back": "fever", "example": "A criança está com febre alta.", "exampleEn": "The child has a high fever." },
    { "id": "pt-0316", "front": "o peixe", "back": "fish", "example": "O peixe fresco chega todos os dias.", "exampleEn": "Fresh fish arrives every day." },
    { "id": "pt-0317", "front": "o mapa", "back": "map", "example": "Você tem um mapa da cidade?", "exampleEn": "Do you have a map of the city?" },
    { "id": "pt-0318", "front": "o imposto", "back": "tax", "example": "Todo mundo paga imposto sobre a renda.", "exampleEn": "Everyone pays income tax." },
    { "id": "pt-0319", "front": "a esposa", "back": "wife", "example": "Minha esposa gosta de ler à noite.", "exampleEn": "My wife likes to read at night." },
    { "id": "pt-0320", "front": "o resfriado", "back": "a cold (illness)", "example": "Peguei um resfriado na semana passada.", "exampleEn": "I caught a cold last week." },
    { "id": "pt-0321", "front": "o camarão", "back": "shrimp", "example": "O camarão grelhado é meu favorito.", "exampleEn": "Grilled shrimp is my favorite." },
    { "id": "pt-0322", "front": "a direção", "back": "direction", "example": "Pode me dar a direção certa?", "exampleEn": "Can you give me the right direction?" },
    { "id": "pt-0323", "front": "o investimento", "back": "investment", "example": "Esse investimento rendeu muito bem.", "exampleEn": "That investment paid off very well." },
    { "id": "pt-0324", "front": "o bebê", "back": "baby", "example": "O bebê está dormindo agora.", "exampleEn": "The baby is sleeping now." },
    { "id": "pt-0325", "front": "a tosse", "back": "cough", "example": "Essa tosse não passa de jeito nenhum.", "exampleEn": "This cough just won't go away." },
    { "id": "pt-0326", "front": "a cebola", "back": "onion", "example": "Refogue a cebola em azeite.", "exampleEn": "Sauté the onion in olive oil." },
    { "id": "pt-0327", "front": "a esquina", "back": "street corner", "example": "Vire à esquerda na esquina.", "exampleEn": "Turn left at the corner." },
    { "id": "pt-0328", "front": "o orçamento", "back": "budget, quote", "example": "O orçamento do projeto foi aprovado.", "exampleEn": "The project budget was approved." },
    { "id": "pt-0329", "front": "o sobrinho", "back": "nephew", "example": "Meu sobrinho tem cinco anos.", "exampleEn": "My nephew is five years old." },
    { "id": "pt-0330", "front": "o remédio", "back": "medicine / medication", "example": "O médico receitou um remédio forte.", "exampleEn": "The doctor prescribed a strong medicine." },
    { "id": "pt-0331", "front": "o alho", "back": "garlic", "example": "Adicione o alho quando a cebola dourar.", "exampleEn": "Add the garlic when the onion turns golden." },
    { "id": "pt-0332", "front": "o semáforo", "back": "traffic light", "example": "Pare no semáforo vermelho.", "exampleEn": "Stop at the red traffic light." },
    { "id": "pt-0333", "front": "o desconto", "back": "discount", "example": "Consegui um desconto de vinte por cento.", "exampleEn": "I got a twenty percent discount." },
    { "id": "pt-0334", "front": "a sobrinha", "back": "niece", "example": "A sobrinha dela é muito esperta.", "exampleEn": "Her niece is very smart." },
    { "id": "pt-0335", "front": "a consulta", "back": "medical appointment", "example": "Tenho uma consulta amanhã de manhã.", "exampleEn": "I have an appointment tomorrow morning." },
    { "id": "pt-0336", "front": "o tomate", "back": "tomato", "example": "Esse molho leva tomate fresco.", "exampleEn": "This sauce uses fresh tomato." },
    { "id": "pt-0337", "front": "a ponte", "back": "bridge", "example": "Atravessamos a ponte de manhã.", "exampleEn": "We crossed the bridge in the morning." },
    { "id": "pt-0338", "front": "a dívida", "back": "debt", "example": "Ele está pagando a dívida do cartão.", "exampleEn": "He is paying off his credit card debt." },
    { "id": "pt-0339", "front": "o tio", "back": "uncle", "example": "O tio nos visita toda semana.", "exampleEn": "Our uncle visits us every week." },
    { "id": "pt-0340", "front": "o médico / a médica", "back": "doctor", "example": "A médica examinou o paciente com cuidado.", "exampleEn": "The doctor examined the patient carefully." },
    { "id": "pt-0341", "front": "a batata", "back": "potato", "example": "Quero batata frita com o hambúrguer.", "exampleEn": "I want french fries with the burger." },
    { "id": "pt-0342", "front": "a avenida", "back": "avenue", "example": "O hotel fica na avenida principal.", "exampleEn": "The hotel is on the main avenue." },
    { "id": "pt-0343", "front": "o cartão de crédito", "back": "credit card", "example": "Posso pagar com cartão de crédito?", "exampleEn": "Can I pay with a credit card?" },
    { "id": "pt-0344", "front": "a tia", "back": "aunt", "example": "A tia trouxe presentes para todos.", "exampleEn": "The aunt brought gifts for everyone." },
    { "id": "pt-0345", "front": "a alergia", "back": "allergy", "example": "Ele tem alergia a amendoim.", "exampleEn": "He has a peanut allergy." },
    { "id": "pt-0346", "front": "a cenoura", "back": "carrot", "example": "A sopa leva cenoura e batata.", "exampleEn": "The soup has carrot and potato." },
    { "id": "pt-0347", "front": "o bairro", "back": "neighborhood", "example": "Esse bairro é muito tranquilo.", "exampleEn": "This neighborhood is very quiet." },
    { "id": "pt-0348", "front": "a poupança", "back": "savings", "example": "Ela guarda dinheiro na poupança todo mês.", "exampleEn": "She puts money into her savings every month." },
    { "id": "pt-0349", "front": "o primo", "back": "cousin (male)", "example": "Meu primo mora em São Paulo.", "exampleEn": "My cousin lives in São Paulo." },
    { "id": "pt-0350", "front": "o curativo", "back": "bandage / plaster", "example": "Coloquei um curativo no corte.", "exampleEn": "I put a bandage on the cut." },
    { "id": "pt-0351", "front": "o feijão", "back": "beans", "example": "Feijão com arroz é o prato nacional.", "exampleEn": "Beans with rice is the national dish." },
    { "id": "pt-0352", "front": "o centro", "back": "city center / downtown", "example": "Vamos almoçar no centro hoje.", "exampleEn": "We're having lunch downtown today." },
    { "id": "pt-0353", "front": "o empréstimo", "back": "loan", "example": "Ele pediu um empréstimo ao banco.", "exampleEn": "He took out a loan from the bank." },
    { "id": "pt-0354", "front": "escovar os dentes", "back": "to brush teeth", "example": "Eu escovo os dentes após o café.", "exampleEn": "I brush my teeth after breakfast." },
    { "id": "pt-0355", "front": "cansado / cansada", "back": "tired", "example": "Estou muito cansada depois do trabalho.", "exampleEn": "I am very tired after work." },
    { "id": "pt-0356", "front": "o azeite", "back": "olive oil", "example": "Cozinho tudo com azeite extravirgem.", "exampleEn": "I cook everything with extra virgin olive oil." },
    { "id": "pt-0357", "front": "a praça", "back": "square / plaza", "example": "Nos encontramos na praça às três.", "exampleEn": "We're meeting at the square at three." },
    { "id": "pt-0358", "front": "a parcela", "back": "installment, payment", "example": "Pago a parcela do carro todo mês.", "exampleEn": "I pay the car installment every month." },
    { "id": "pt-0359", "front": "tomar banho", "back": "to take a shower", "example": "Ela toma banho cedo toda manhã.", "exampleEn": "She showers early every morning." },
    { "id": "pt-0360", "front": "animado / animada", "back": "excited / enthusiastic", "example": "Ele está muito animado com a viagem.", "exampleEn": "He is very excited about the trip." },
    { "id": "pt-0361", "front": "a manteiga", "back": "butter", "example": "Passe manteiga no pão torrado.", "exampleEn": "Spread butter on the toast." },
    { "id": "pt-0362", "front": "o museu", "back": "museum", "example": "O museu abre às dez da manhã.", "exampleEn": "The museum opens at ten in the morning." },
    { "id": "pt-0363", "front": "o recibo", "back": "receipt", "example": "Guarde o recibo da compra.", "exampleEn": "Keep the purchase receipt." },
    { "id": "pt-0364", "front": "se vestir", "back": "to get dressed", "example": "Ele se veste rápido antes do trabalho.", "exampleEn": "He gets dressed quickly before work." },
    { "id": "pt-0365", "front": "com raiva", "back": "angry", "example": "Ela ficou com raiva da situação.", "exampleEn": "She got angry about the situation." },
    { "id": "pt-0366", "front": "o queijo", "back": "cheese", "example": "Essa pizza tem muito queijo.", "exampleEn": "This pizza has a lot of cheese." },
    { "id": "pt-0367", "front": "a igreja", "back": "church", "example": "A igreja antiga fica no centro.", "exampleEn": "The old church is in the center." },
    { "id": "pt-0368", "front": "o sócio", "back": "business partner", "example": "Ela tem um sócio no restaurante.", "exampleEn": "She has a business partner in the restaurant." },
    { "id": "pt-0369", "front": "se pentear", "back": "to comb one's hair", "example": "A menina se penteia no banheiro.", "exampleEn": "The girl combs her hair in the bathroom." },
    { "id": "pt-0370", "front": "com medo", "back": "afraid / scared", "example": "A criança está com medo do escuro.", "exampleEn": "The child is afraid of the dark." },
    { "id": "pt-0371", "front": "o presunto", "back": "ham", "example": "O sanduíche tem presunto e queijo.", "exampleEn": "The sandwich has ham and cheese." },
    { "id": "pt-0372", "front": "o supermercado", "back": "supermarket", "example": "Há um supermercado perto daqui.", "exampleEn": "There is a supermarket near here." },
    { "id": "pt-0373", "front": "a concorrência", "back": "competition", "example": "A concorrência está cada vez maior.", "exampleEn": "The competition is getting bigger and bigger." },
    { "id": "pt-0374", "front": "fazer a cama", "back": "to make the bed", "example": "Faço a cama todos os dias.", "exampleEn": "I make the bed every day." },
    { "id": "pt-0375", "front": "surpreso / surpresa", "back": "surprised", "example": "Fiquei surpresa com a notícia.", "exampleEn": "I was surprised by the news." },
    { "id": "pt-0376", "front": "a farinha", "back": "flour", "example": "Misture a farinha com os ovos.", "exampleEn": "Mix the flour with the eggs." },
    { "id": "pt-0377", "front": "a farmácia", "back": "pharmacy", "example": "Preciso ir à farmácia comprar remédio.", "exampleEn": "I need to go to the pharmacy to buy medicine." },
    { "id": "pt-0378", "front": "o produto", "back": "product", "example": "Esse produto vende muito bem.", "exampleEn": "This product sells very well." },
    { "id": "pt-0379", "front": "lavar a louça", "back": "to wash the dishes", "example": "Quem vai lavar a louça hoje?", "exampleEn": "Who is going to wash the dishes today?" },
    { "id": "pt-0380", "front": "nervoso / nervosa", "back": "nervous", "example": "Estou nervosa antes da apresentação.", "exampleEn": "I am nervous before the presentation." },
    { "id": "pt-0381", "front": "o molho", "back": "sauce", "example": "Esse molho de tomate é incrível.", "exampleEn": "This tomato sauce is incredible." },
    { "id": "pt-0382", "front": "o correio", "back": "post office", "example": "O correio fecha ao meio-dia.", "exampleEn": "The post office closes at noon." },
    { "id": "pt-0383", "front": "o serviço", "back": "service", "example": "O serviço do hotel foi excelente.", "exampleEn": "The hotel service was excellent." },
    { "id": "pt-0384", "front": "varrer o chão", "back": "to sweep the floor", "example": "Ele varre o chão depois do jantar.", "exampleEn": "He sweeps the floor after dinner." },
    { "id": "pt-0385", "front": "preocupado / preocupada", "back": "worried", "example": "Ela está preocupada com o filho.", "exampleEn": "She is worried about her son." },
    { "id": "pt-0386", "front": "a sopa", "back": "soup", "example": "Uma sopa quente é ótima no inverno.", "exampleEn": "A hot soup is great in winter." },
    { "id": "pt-0387", "front": "a delegacia", "back": "police station", "example": "A delegacia fica na próxima rua.", "exampleEn": "The police station is on the next street." },
    { "id": "pt-0388", "front": "a venda", "back": "sale, selling", "example": "As vendas aumentaram no fim do ano.", "exampleEn": "Sales increased at the end of the year." },
    { "id": "pt-0389", "front": "a camisa", "back": "shirt", "example": "Essa camisa azul combina com a calça.", "exampleEn": "That blue shirt matches the pants." },
    { "id": "pt-0390", "front": "com vergonha", "back": "ashamed / embarrassed", "example": "Ele ficou com vergonha na frente de todos.", "exampleEn": "He felt embarrassed in front of everyone." },
    { "id": "pt-0391", "front": "a salada", "back": "salad", "example": "Peço sempre salada como entrada.", "exampleEn": "I always order salad as a starter." },
    { "id": "pt-0392", "front": "o ponto de ônibus", "back": "bus stop", "example": "Espere no ponto de ônibus ali.", "exampleEn": "Wait at the bus stop over there." },
    { "id": "pt-0393", "front": "o aluno", "back": "student (male)", "example": "O aluno tirou uma nota ótima.", "exampleEn": "The student got a great grade." },
    { "id": "pt-0394", "front": "a calça", "back": "pants, trousers", "example": "Preciso comprar uma calça nova.", "exampleEn": "I need to buy new pants." },
    { "id": "pt-0395", "front": "aliviado / aliviada", "back": "relieved", "example": "Fiquei aliviada quando ele chegou em casa.", "exampleEn": "I felt relieved when he got home." },
    { "id": "pt-0396", "front": "a entrada", "back": "starter, appetizer", "example": "A entrada do restaurante foi deliciosa.", "exampleEn": "The restaurant's starter was delicious." },
    { "id": "pt-0397", "front": "a linha", "back": "line / route", "example": "Qual linha de metrô vai ao centro?", "exampleEn": "Which metro line goes to the center?" },
    { "id": "pt-0398", "front": "a aluna", "back": "student (female)", "example": "A aluna estudou muito para a prova.", "exampleEn": "The student studied a lot for the test." },
    { "id": "pt-0399", "front": "o vestido", "back": "dress", "example": "Ela usou um vestido bonito na festa.", "exampleEn": "She wore a beautiful dress at the party." },
    { "id": "pt-0400", "front": "com saudade", "back": "missing someone / nostalgic", "example": "Estou com saudade da minha família.", "exampleEn": "I miss my family." },
    { "id": "pt-0401", "front": "o prato principal", "back": "main course", "example": "O prato principal demora vinte minutos.", "exampleEn": "The main course takes twenty minutes." },
    { "id": "pt-0402", "front": "a balsa", "back": "ferry", "example": "A balsa sai às oito da manhã.", "exampleEn": "The ferry leaves at eight in the morning." },
    { "id": "pt-0403", "front": "o professor", "back": "teacher (male)", "example": "O professor explicou a matéria devagar.", "exampleEn": "The teacher explained the subject slowly." },
    { "id": "pt-0404", "front": "a saia", "back": "skirt", "example": "A saia dela é muito elegante.", "exampleEn": "Her skirt is very elegant." },
    { "id": "pt-0405", "front": "com ciúme", "back": "jealous", "example": "Ele ficou com ciúme do novo amigo.", "exampleEn": "He got jealous of the new friend." },
    { "id": "pt-0406", "front": "o vinho", "back": "wine", "example": "Vamos pedir uma garrafa de vinho tinto.", "exampleEn": "Let's order a bottle of red wine." },
    { "id": "pt-0407", "front": "o barco", "back": "boat", "example": "Alugamos um barco na praia.", "exampleEn": "We rented a boat at the beach." },
    { "id": "pt-0408", "front": "a professora", "back": "teacher (female)", "example": "A professora deu muita lição de casa.", "exampleEn": "The teacher gave a lot of homework." },
    { "id": "pt-0409", "front": "o casaco", "back": "coat, jacket", "example": "Vista o casaco, está frio lá fora.", "exampleEn": "Put on your coat, it's cold outside." },
    { "id": "pt-0410", "front": "entediado / entediada", "back": "bored", "example": "A criança está entediada em casa.", "exampleEn": "The child is bored at home." },
    { "id": "pt-0411", "front": "a cerveja", "back": "beer", "example": "Ela pediu uma cerveja gelada.", "exampleEn": "She ordered a cold beer." },
    { "id": "pt-0412", "front": "a moto", "back": "motorcycle", "example": "Ele chegou de moto muito rápido.", "exampleEn": "He arrived by motorcycle very quickly." },
    { "id": "pt-0413", "front": "a prova", "back": "test, exam", "example": "A prova de matemática foi muito difícil.", "exampleEn": "The math test was very difficult." },
    { "id": "pt-0414", "front": "o tênis", "back": "sneakers", "example": "Meu tênis novo é muito confortável.", "exampleEn": "My new sneakers are very comfortable." },
    { "id": "pt-0415", "front": "orgulhoso / orgulhosa", "back": "proud", "example": "Estou orgulhosa do meu trabalho.", "exampleEn": "I am proud of my work." },
    { "id": "pt-0416", "front": "o chá", "back": "tea", "example": "Tomo chá de camomila antes de dormir.", "exampleEn": "I drink chamomile tea before sleeping." },
    { "id": "pt-0417", "front": "o caminhão", "back": "truck", "example": "Um caminhão grande bloqueou a rua.", "exampleEn": "A large truck blocked the street." },
    { "id": "pt-0418", "front": "a nota", "back": "grade, note", "example": "Ele tirou nota dez na redação.", "exampleEn": "He got a ten on the essay." },
    { "id": "pt-0419", "front": "a sandália", "back": "sandal", "example": "No verão, uso sandália todos os dias.", "exampleEn": "In summer, I wear sandals every day." },
    { "id": "pt-0420", "front": "a tempestade", "back": "storm", "example": "Uma tempestade forte chegou à cidade.", "exampleEn": "A strong storm hit the city." },
    { "id": "pt-0421", "front": "o copo", "back": "glass, cup", "example": "Encha meu copo de água, por favor.", "exampleEn": "Fill my glass with water, please." },
    { "id": "pt-0422", "front": "o helicóptero", "back": "helicopter", "example": "O helicóptero sobrevoou a cidade.", "exampleEn": "The helicopter flew over the city." },
    { "id": "pt-0423", "front": "a aula", "back": "class, lesson", "example": "A aula de inglês começa às sete.", "exampleEn": "The English class starts at seven." },
    { "id": "pt-0424", "front": "a bota", "back": "boot", "example": "As botas dela são de couro marrom.", "exampleEn": "Her boots are brown leather." },
    { "id": "pt-0425", "front": "o trovão", "back": "thunder", "example": "O trovão acordou todo mundo à noite.", "exampleEn": "The thunder woke everyone up at night." },
    { "id": "pt-0426", "front": "o garfo", "back": "fork", "example": "O garfo caiu no chão.", "exampleEn": "The fork fell on the floor." },
    { "id": "pt-0427", "front": "a decolagem", "back": "takeoff", "example": "A decolagem está prevista para as seis.", "exampleEn": "The takeoff is scheduled for six." },
    { "id": "pt-0428", "front": "a matéria", "back": "subject (school)", "example": "Qual é sua matéria favorita?", "exampleEn": "What is your favorite subject?" },
    { "id": "pt-0429", "front": "a meia", "back": "sock", "example": "Não acho o par de meias.", "exampleEn": "I can't find the pair of socks." },
    { "id": "pt-0430", "front": "o relâmpago", "back": "lightning", "example": "Vi um relâmpago atravessar o céu.", "exampleEn": "I saw lightning cross the sky." },
    { "id": "pt-0431", "front": "a faca", "back": "knife", "example": "Preciso de uma faca para cortar a carne.", "exampleEn": "I need a knife to cut the meat." },
    { "id": "pt-0432", "front": "o pouso", "back": "landing", "example": "O pouso foi suave e tranquilo.", "exampleEn": "The landing was smooth and calm." },
    { "id": "pt-0433", "front": "o dever de casa", "back": "homework", "example": "Você já fez o dever de casa?", "exampleEn": "Have you already done your homework?" },
    { "id": "pt-0434", "front": "a cueca", "back": "underwear (men's)", "example": "Comprei três cuecas novas.", "exampleEn": "I bought three new pairs of underwear." },
    { "id": "pt-0435", "front": "a neblina", "back": "fog / mist", "example": "Há muita neblina na estrada hoje.", "exampleEn": "There is a lot of fog on the road today." },
    { "id": "pt-0436", "front": "a colher", "back": "spoon", "example": "Use a colher para mexer o molho.", "exampleEn": "Use the spoon to stir the sauce." },
    { "id": "pt-0437", "front": "o voo", "back": "flight", "example": "O voo para Lisboa dura dez horas.", "exampleEn": "The flight to Lisbon takes ten hours." },
    { "id": "pt-0438", "front": "a faculdade", "back": "university, college", "example": "Ela está na faculdade de medicina.", "exampleEn": "She is in medical school." },
    { "id": "pt-0439", "front": "o sutiã", "back": "bra", "example": "O sutiã está no armário.", "exampleEn": "The bra is in the wardrobe." },
    { "id": "pt-0440", "front": "a neve", "back": "snow", "example": "Nunca vi neve na minha vida.", "exampleEn": "I have never seen snow in my life." },
    { "id": "pt-0441", "front": "o guardanapo", "back": "napkin", "example": "Pode me trazer um guardanapo?", "exampleEn": "Can you bring me a napkin?" },
    { "id": "pt-0442", "front": "o embarque", "back": "boarding", "example": "O embarque começa daqui a pouco.", "exampleEn": "Boarding starts in a little while." },
    { "id": "pt-0443", "front": "o diploma", "back": "diploma, degree", "example": "Ele recebeu o diploma em dezembro.", "exampleEn": "He received his diploma in December." },
    { "id": "pt-0444", "front": "o pijama", "back": "pajamas", "example": "Vou trocar o pijama agora.", "exampleEn": "I'm going to change out of my pajamas now." },
    { "id": "pt-0445", "front": "úmido / úmida", "back": "humid / damp", "example": "O verão aqui é muito úmido.", "exampleEn": "The summer here is very humid." },
    { "id": "pt-0446", "front": "gostoso", "back": "tasty, delicious", "example": "Esse bolo está muito gostoso.", "exampleEn": "This cake is very tasty." },
    { "id": "pt-0447", "front": "o desembarque", "back": "arrival / disembarkation", "example": "O desembarque foi demorado hoje.", "exampleEn": "Disembarkation took a long time today." },
    { "id": "pt-0448", "front": "a turma", "back": "class, group (students)", "example": "A turma tem trinta alunos.", "exampleEn": "The class has thirty students." },
    { "id": "pt-0449", "front": "o chapéu", "back": "hat", "example": "Ele usa chapéu quando faz sol.", "exampleEn": "He wears a hat when it's sunny." },
    { "id": "pt-0450", "front": "ensolarado / ensolarada", "back": "sunny", "example": "Hoje está um dia lindo e ensolarado.", "exampleEn": "Today is a beautiful sunny day." },
    { "id": "pt-0451", "front": "salgado", "back": "salty", "example": "A sopa ficou muito salgada hoje.", "exampleEn": "The soup was too salty today." },
    { "id": "pt-0452", "front": "a alfândega", "back": "customs", "example": "Fui parado na alfândega do aeroporto.", "exampleEn": "I was stopped at airport customs." },
    { "id": "pt-0453", "front": "a bolsa de estudos", "back": "scholarship", "example": "Ela ganhou uma bolsa de estudos integral.", "exampleEn": "She won a full scholarship." },
    { "id": "pt-0454", "front": "a bolsa", "back": "bag, purse", "example": "As chaves estão dentro da bolsa.", "exampleEn": "The keys are inside the bag." },
    { "id": "pt-0455", "front": "nublado / nublada", "back": "cloudy", "example": "O céu está nublado esta tarde.", "exampleEn": "The sky is cloudy this afternoon." },
    { "id": "pt-0456", "front": "doce", "back": "sweet", "example": "Adoro sobremesas doces depois do jantar.", "exampleEn": "I love sweet desserts after dinner." },
    { "id": "pt-0457", "front": "o visto", "back": "visa", "example": "Preciso de um visto para entrar no país.", "exampleEn": "I need a visa to enter the country." },
    { "id": "pt-0458", "front": "o estágio", "back": "internship", "example": "Ele faz estágio em uma empresa de tecnologia.", "exampleEn": "He is doing an internship at a tech company." },
    { "id": "pt-0459", "front": "o cinto", "back": "belt", "example": "Esse cinto não combina com o sapato.", "exampleEn": "That belt doesn't match the shoe." },
    { "id": "pt-0460", "front": "a previsão do tempo", "back": "weather forecast", "example": "A previsão do tempo indica chuva amanhã.", "exampleEn": "The weather forecast shows rain tomorrow." },
    { "id": "pt-0461", "front": "amargo", "back": "bitter", "example": "Esse café sem açúcar é amargo demais.", "exampleEn": "This coffee without sugar is too bitter." },
    { "id": "pt-0462", "front": "a bagagem", "back": "luggage / baggage", "example": "Perdi minha bagagem no aeroporto.", "exampleEn": "I lost my luggage at the airport." },
    { "id": "pt-0463", "front": "o aplicativo", "back": "app, application", "example": "Baixei um aplicativo novo no celular.", "exampleEn": "I downloaded a new app on my phone." },
    { "id": "pt-0464", "front": "o tamanho", "back": "size", "example": "Qual é o seu tamanho de camisa?", "exampleEn": "What is your shirt size?" },
    { "id": "pt-0465", "front": "a seca", "back": "drought", "example": "A seca está afetando toda a região.", "exampleEn": "The drought is affecting the whole region." },
    { "id": "pt-0466", "front": "apimentado", "back": "spicy", "example": "A comida mexicana é muito apimentada.", "exampleEn": "Mexican food is very spicy." },
    { "id": "pt-0467", "front": "o endereço", "back": "address", "example": "Qual é o endereço do hotel?", "exampleEn": "What is the hotel's address?" },
    { "id": "pt-0468", "front": "a internet", "back": "internet", "example": "A internet aqui está muito lenta.", "exampleEn": "The internet here is very slow." },
    { "id": "pt-0469", "front": "o provador", "back": "fitting room", "example": "Posso usar o provador, por favor?", "exampleEn": "Can I use the fitting room, please?" },
    { "id": "pt-0470", "front": "a enchente", "back": "flood", "example": "A enchente destruiu várias casas.", "exampleEn": "The flood destroyed several houses." },
    { "id": "pt-0471", "front": "azedo", "back": "sour", "example": "Esse iogurte está azedo.", "exampleEn": "This yogurt is sour." },
    { "id": "pt-0472", "front": "a plataforma", "back": "platform", "example": "O trem chega na plataforma dois.", "exampleEn": "The train arrives at platform two." },
    { "id": "pt-0473", "front": "a senha", "back": "password", "example": "Nunca compartilhe sua senha com ninguém.", "exampleEn": "Never share your password with anyone." },
    { "id": "pt-0474", "front": "a promoção", "back": "sale, promotion", "example": "A loja está em promoção hoje.", "exampleEn": "The store is having a sale today." },
    { "id": "pt-0475", "front": "o arco-íris", "back": "rainbow", "example": "Apareceu um arco-íris depois da chuva.", "exampleEn": "A rainbow appeared after the rain." },
    { "id": "pt-0476", "front": "grelhado", "back": "grilled", "example": "Prefiro peixe grelhado a frito.", "exampleEn": "I prefer grilled fish to fried." },
    { "id": "pt-0477", "front": "o horário", "back": "schedule / timetable", "example": "Qual é o horário do próximo ônibus?", "exampleEn": "What is the schedule for the next bus?" },
    { "id": "pt-0478", "front": "o arquivo", "back": "file, document", "example": "Salve o arquivo antes de fechar.", "exampleEn": "Save the file before closing." },
    { "id": "pt-0479", "front": "o caixa", "back": "cashier, checkout", "example": "A fila do caixa está grande.", "exampleEn": "The checkout line is long." },
    { "id": "pt-0480", "front": "o amanhecer", "back": "dawn / sunrise", "example": "Ele acorda todo dia ao amanhecer.", "exampleEn": "He wakes up every day at dawn." },
    { "id": "pt-0481", "front": "cozido", "back": "cooked, boiled", "example": "Ovo cozido é prático no café da manhã.", "exampleEn": "Boiled egg is practical for breakfast." },
    { "id": "pt-0482", "front": "a chegada", "back": "arrival", "example": "A chegada do trem está atrasada.", "exampleEn": "The train's arrival is delayed." },
    { "id": "pt-0483", "front": "a rede", "back": "network", "example": "A rede da empresa caiu hoje.", "exampleEn": "The company network went down today." },
    { "id": "pt-0484", "front": "a sacola", "back": "shopping bag", "example": "Você quer uma sacola de papel?", "exampleEn": "Do you want a paper bag?" },
    { "id": "pt-0485", "front": "o anoitecer", "back": "dusk / sunset", "example": "Sentamos na praia ao anoitecer.", "exampleEn": "We sat on the beach at dusk." },
    { "id": "pt-0486", "front": "frito", "back": "fried", "example": "Frango frito é muito popular aqui.", "exampleEn": "Fried chicken is very popular here." },
    { "id": "pt-0487", "front": "a partida", "back": "departure", "example": "A partida é às seis da manhã.", "exampleEn": "The departure is at six in the morning." },
    { "id": "pt-0488", "front": "o programa", "back": "program, software", "example": "Preciso instalar esse programa no computador.", "exampleEn": "I need to install this program on the computer." },
    { "id": "pt-0489", "front": "o carrinho", "back": "shopping cart", "example": "O carrinho está cheio de comida.", "exampleEn": "The cart is full of food." },
    { "id": "pt-0490", "front": "o século", "back": "century", "example": "Esse edifício tem mais de um século.", "exampleEn": "That building is more than a century old." },
    { "id": "pt-0491", "front": "assado", "back": "roasted, baked", "example": "O frango assado ficou perfeito.", "exampleEn": "The roasted chicken turned out perfect." },
    { "id": "pt-0492", "front": "o atraso", "back": "delay", "example": "O voo tem um atraso de duas horas.", "exampleEn": "The flight has a two-hour delay." },
    { "id": "pt-0493", "front": "o sistema", "back": "system", "example": "O sistema está em manutenção agora.", "exampleEn": "The system is under maintenance right now." },
    { "id": "pt-0494", "front": "a vitrine", "back": "store window, display", "example": "Vi um vestido lindo na vitrine.", "exampleEn": "I saw a beautiful dress in the window display." },
    { "id": "pt-0495", "front": "o inverno", "back": "winter", "example": "No inverno, as noites são muito longas.", "exampleEn": "In winter, the nights are very long." },
    { "id": "pt-0496", "front": "cru", "back": "raw", "example": "Não como peixe cru.", "exampleEn": "I don't eat raw fish." },
    { "id": "pt-0497", "front": "o trânsito", "back": "traffic", "example": "O trânsito está horrível nessa hora.", "exampleEn": "The traffic is terrible at this hour." },
    { "id": "pt-0498", "front": "a tela", "back": "screen", "example": "A tela do meu celular quebrou.", "exampleEn": "The screen of my phone broke." },
    { "id": "pt-0499", "front": "o troco", "back": "change (money)", "example": "Aqui está o seu troco.", "exampleEn": "Here is your change." },
    { "id": "pt-0500", "front": "o verão", "back": "summer", "example": "No verão, vamos sempre à praia.", "exampleEn": "In summer, we always go to the beach." }
  ]
};
if (typeof module !== "undefined" && module.exports) module.exports = deck;
if (typeof window !== "undefined") { var WL = (window.WL = window.WL || {}); (WL.__decks = WL.__decks || []).push(deck); }
