// Agora deck. Free.
var deck = {
  "id": "bundled:spanish",
  "name": "Spanish 500",
  "lang": "es",
  "cards": [
    { "id": "es-0001", "front": "hola", "back": "hello", "example": "Hola, ¿cómo estás?", "exampleEn": "Hello, how are you?" },
    { "id": "es-0002", "front": "adiós", "back": "goodbye", "example": "Adiós, hasta mañana.", "exampleEn": "Goodbye, see you tomorrow." },
    { "id": "es-0003", "front": "buenos días", "back": "good morning", "example": "Buenos días, señora.", "exampleEn": "Good morning, ma'am." },
    { "id": "es-0004", "front": "buenas tardes", "back": "good afternoon", "example": "Buenas tardes a todos.", "exampleEn": "Good afternoon, everyone." },
    { "id": "es-0005", "front": "buenas noches", "back": "good night", "example": "Buenas noches, que descanses.", "exampleEn": "Good night, sleep well." },
    { "id": "es-0006", "front": "por favor", "back": "please", "example": "Un café, por favor.", "exampleEn": "A coffee, please." },
    { "id": "es-0007", "front": "gracias", "back": "thank you", "example": "Muchas gracias por tu ayuda.", "exampleEn": "Thank you very much for your help." },
    { "id": "es-0008", "front": "de nada", "back": "you're welcome", "example": "De nada, fue un placer.", "exampleEn": "You're welcome, it was a pleasure." },
    { "id": "es-0009", "front": "perdón", "back": "sorry / excuse me", "example": "Perdón, no te oí.", "exampleEn": "Sorry, I didn't hear you." },
    { "id": "es-0010", "front": "lo siento", "back": "I'm sorry", "example": "Lo siento mucho por el retraso.", "exampleEn": "I'm very sorry for the delay." },
    { "id": "es-0011", "front": "sí", "back": "yes", "example": "Sí, me gusta mucho.", "exampleEn": "Yes, I like it a lot." },
    { "id": "es-0012", "front": "no", "back": "no", "example": "No, gracias.", "exampleEn": "No, thank you." },
    { "id": "es-0013", "front": "bienvenido", "back": "welcome", "example": "Bienvenido a nuestra casa.", "exampleEn": "Welcome to our home." },
    { "id": "es-0014", "front": "mucho gusto", "back": "nice to meet you", "example": "Mucho gusto, soy Ana.", "exampleEn": "Nice to meet you, I'm Ana." },
    { "id": "es-0015", "front": "¿cómo estás?", "back": "how are you?", "example": "Hola Pedro, ¿cómo estás?", "exampleEn": "Hi Pedro, how are you?" },
    { "id": "es-0016", "front": "hasta luego", "back": "see you later", "example": "Me voy ya, hasta luego.", "exampleEn": "I'm leaving now, see you later." },
    { "id": "es-0017", "front": "cero", "back": "zero", "example": "El marcador está en cero.", "exampleEn": "The score is at zero." },
    { "id": "es-0018", "front": "uno", "back": "one", "example": "Solo quiero uno.", "exampleEn": "I only want one." },
    { "id": "es-0019", "front": "dos", "back": "two", "example": "Tengo dos hermanos.", "exampleEn": "I have two brothers." },
    { "id": "es-0020", "front": "tres", "back": "three", "example": "Son las tres de la tarde.", "exampleEn": "It's three in the afternoon." },
    { "id": "es-0021", "front": "cuatro", "back": "four", "example": "La mesa tiene cuatro patas.", "exampleEn": "The table has four legs." },
    { "id": "es-0022", "front": "cinco", "back": "five", "example": "Llego en cinco minutos.", "exampleEn": "I'll be there in five minutes." },
    { "id": "es-0023", "front": "seis", "back": "six", "example": "El niño tiene seis años.", "exampleEn": "The boy is six years old." },
    { "id": "es-0024", "front": "siete", "back": "seven", "example": "La semana tiene siete días.", "exampleEn": "The week has seven days." },
    { "id": "es-0025", "front": "ocho", "back": "eight", "example": "Trabajo ocho horas al día.", "exampleEn": "I work eight hours a day." },
    { "id": "es-0026", "front": "nueve", "back": "nine", "example": "Faltan nueve días.", "exampleEn": "There are nine days left." },
    { "id": "es-0027", "front": "diez", "back": "ten", "example": "Hay diez personas aquí.", "exampleEn": "There are ten people here." },
    { "id": "es-0028", "front": "once", "back": "eleven", "example": "El tren sale a las once.", "exampleEn": "The train leaves at eleven." },
    { "id": "es-0029", "front": "doce", "back": "twelve", "example": "El año tiene doce meses.", "exampleEn": "The year has twelve months." },
    { "id": "es-0030", "front": "trece", "back": "thirteen", "example": "Tengo trece monedas.", "exampleEn": "I have thirteen coins." },
    { "id": "es-0031", "front": "catorce", "back": "fourteen", "example": "Mi prima cumple catorce años.", "exampleEn": "My cousin is turning fourteen." },
    { "id": "es-0032", "front": "quince", "back": "fifteen", "example": "Espera quince minutos.", "exampleEn": "Wait fifteen minutes." },
    { "id": "es-0033", "front": "dieciséis", "back": "sixteen", "example": "Hay dieciséis estudiantes.", "exampleEn": "There are sixteen students." },
    { "id": "es-0034", "front": "diecisiete", "back": "seventeen", "example": "Mi hermano tiene diecisiete años.", "exampleEn": "My brother is seventeen years old." },
    { "id": "es-0035", "front": "dieciocho", "back": "eighteen", "example": "Se vota a los dieciocho años.", "exampleEn": "You can vote at eighteen." },
    { "id": "es-0036", "front": "diecinueve", "back": "nineteen", "example": "Quedan diecinueve días.", "exampleEn": "There are nineteen days left." },
    { "id": "es-0037", "front": "veinte", "back": "twenty", "example": "El libro cuesta veinte euros.", "exampleEn": "The book costs twenty euros." },
    { "id": "es-0038", "front": "treinta", "back": "thirty", "example": "Mi padre tiene treinta años.", "exampleEn": "My father is thirty years old." },
    { "id": "es-0039", "front": "cuarenta", "back": "forty", "example": "Hay cuarenta sillas en la sala.", "exampleEn": "There are forty chairs in the room." },
    { "id": "es-0040", "front": "cincuenta", "back": "fifty", "example": "El billete es de cincuenta euros.", "exampleEn": "It's a fifty-euro bill." },
    { "id": "es-0041", "front": "sesenta", "back": "sixty", "example": "Mi abuela tiene sesenta años.", "exampleEn": "My grandmother is sixty years old." },
    { "id": "es-0042", "front": "setenta", "back": "seventy", "example": "El camino mide setenta metros.", "exampleEn": "The path is seventy meters long." },
    { "id": "es-0043", "front": "ochenta", "back": "eighty", "example": "Vinieron ochenta invitados.", "exampleEn": "Eighty guests came." },
    { "id": "es-0044", "front": "noventa", "back": "ninety", "example": "Faltan noventa páginas.", "exampleEn": "There are ninety pages left." },
    { "id": "es-0045", "front": "cien", "back": "one hundred", "example": "Tengo cien dólares.", "exampleEn": "I have a hundred dollars." },
    { "id": "es-0046", "front": "mil", "back": "one thousand", "example": "El coche cuesta mil euros.", "exampleEn": "The car costs a thousand euros." },
    { "id": "es-0047", "front": "lunes", "back": "Monday", "example": "El lunes empiezo a trabajar.", "exampleEn": "I start work on Monday." },
    { "id": "es-0048", "front": "martes", "back": "Tuesday", "example": "Tengo cita el martes.", "exampleEn": "I have an appointment on Tuesday." },
    { "id": "es-0049", "front": "miércoles", "back": "Wednesday", "example": "El miércoles vamos al cine.", "exampleEn": "On Wednesday we're going to the movies." },
    { "id": "es-0050", "front": "jueves", "back": "Thursday", "example": "Los jueves estudio inglés.", "exampleEn": "On Thursdays I study English." },
    { "id": "es-0051", "front": "viernes", "back": "Friday", "example": "El viernes salgo con amigos.", "exampleEn": "On Friday I'm going out with friends." },
    { "id": "es-0052", "front": "sábado", "back": "Saturday", "example": "El sábado descanso en casa.", "exampleEn": "On Saturday I rest at home." },
    { "id": "es-0053", "front": "domingo", "back": "Sunday", "example": "El domingo visito a mi familia.", "exampleEn": "On Sunday I visit my family." },
    { "id": "es-0054", "front": "enero", "back": "January", "example": "Mi cumpleaños es en enero.", "exampleEn": "My birthday is in January." },
    { "id": "es-0055", "front": "febrero", "back": "February", "example": "Febrero es el mes más corto.", "exampleEn": "February is the shortest month." },
    { "id": "es-0056", "front": "marzo", "back": "March", "example": "En marzo empieza la primavera.", "exampleEn": "Spring begins in March." },
    { "id": "es-0057", "front": "abril", "back": "April", "example": "Llueve mucho en abril.", "exampleEn": "It rains a lot in April." },
    { "id": "es-0058", "front": "mayo", "back": "May", "example": "Nos casamos en mayo.", "exampleEn": "We got married in May." },
    { "id": "es-0059", "front": "junio", "back": "June", "example": "Las clases terminan en junio.", "exampleEn": "Classes end in June." },
    { "id": "es-0060", "front": "julio", "back": "July", "example": "En julio hace mucho calor.", "exampleEn": "It's very hot in July." },
    { "id": "es-0061", "front": "agosto", "back": "August", "example": "Viajamos a la playa en agosto.", "exampleEn": "We travel to the beach in August." },
    { "id": "es-0062", "front": "septiembre", "back": "September", "example": "El curso empieza en septiembre.", "exampleEn": "The school year starts in September." },
    { "id": "es-0063", "front": "octubre", "back": "October", "example": "En octubre caen las hojas.", "exampleEn": "The leaves fall in October." },
    { "id": "es-0064", "front": "noviembre", "back": "November", "example": "Noviembre es un mes frío.", "exampleEn": "November is a cold month." },
    { "id": "es-0065", "front": "diciembre", "back": "December", "example": "La fiesta es en diciembre.", "exampleEn": "The party is in December." },
    { "id": "es-0066", "front": "hoy", "back": "today", "example": "Hoy tengo mucho trabajo.", "exampleEn": "Today I have a lot of work." },
    { "id": "es-0067", "front": "mañana", "back": "tomorrow", "example": "Mañana voy al médico.", "exampleEn": "Tomorrow I'm going to the doctor." },
    { "id": "es-0068", "front": "ayer", "back": "yesterday", "example": "Ayer comí con mi familia.", "exampleEn": "Yesterday I had lunch with my family." },
    { "id": "es-0069", "front": "ahora", "back": "now", "example": "Ahora no puedo hablar.", "exampleEn": "I can't talk right now." },
    { "id": "es-0070", "front": "siempre", "back": "always", "example": "Siempre llego temprano.", "exampleEn": "I always arrive early." },
    { "id": "es-0071", "front": "nunca", "back": "never", "example": "Nunca como carne.", "exampleEn": "I never eat meat." },
    { "id": "es-0072", "front": "el día", "back": "day", "example": "El día está muy soleado.", "exampleEn": "The day is very sunny." },
    { "id": "es-0073", "front": "la semana", "back": "week", "example": "La semana pasada llovió.", "exampleEn": "It rained last week." },
    { "id": "es-0074", "front": "el mes", "back": "month", "example": "Este mes voy a ahorrar.", "exampleEn": "This month I'm going to save money." },
    { "id": "es-0075", "front": "el año", "back": "year", "example": "El año tiene doce meses.", "exampleEn": "The year has twelve months." },
    { "id": "es-0076", "front": "la hora", "back": "hour / time", "example": "¿Qué hora es?", "exampleEn": "What time is it?" },
    { "id": "es-0077", "front": "temprano", "back": "early", "example": "Me levanto muy temprano.", "exampleEn": "I get up very early." },
    { "id": "es-0078", "front": "tarde", "back": "late", "example": "Llegaste tarde otra vez.", "exampleEn": "You were late again." },
    { "id": "es-0079", "front": "qué", "back": "what", "example": "¿Qué quieres comer?", "exampleEn": "What do you want to eat?" },
    { "id": "es-0080", "front": "quién", "back": "who", "example": "¿Quién es esa mujer?", "exampleEn": "Who is that woman?" },
    { "id": "es-0081", "front": "cuándo", "back": "when", "example": "¿Cuándo llegas a casa?", "exampleEn": "When do you get home?" },
    { "id": "es-0082", "front": "dónde", "back": "where", "example": "¿Dónde está el baño?", "exampleEn": "Where is the bathroom?" },
    { "id": "es-0083", "front": "por qué", "back": "why", "example": "¿Por qué estás triste?", "exampleEn": "Why are you sad?" },
    { "id": "es-0084", "front": "cómo", "back": "how", "example": "¿Cómo se dice esto?", "exampleEn": "How do you say this?" },
    { "id": "es-0085", "front": "cuánto", "back": "how much", "example": "¿Cuánto cuesta el café?", "exampleEn": "How much does the coffee cost?" },
    { "id": "es-0086", "front": "cuál", "back": "which", "example": "¿Cuál prefieres, té o café?", "exampleEn": "Which do you prefer, tea or coffee?" },
    { "id": "es-0087", "front": "yo", "back": "I", "example": "Yo vivo en Madrid.", "exampleEn": "I live in Madrid." },
    { "id": "es-0088", "front": "tú", "back": "you (informal)", "example": "Tú hablas muy bien.", "exampleEn": "You speak very well." },
    { "id": "es-0089", "front": "él", "back": "he", "example": "Él trabaja en un banco.", "exampleEn": "He works at a bank." },
    { "id": "es-0090", "front": "ella", "back": "she", "example": "Ella es mi profesora.", "exampleEn": "She is my teacher." },
    { "id": "es-0091", "front": "usted", "back": "you (formal)", "example": "¿Usted habla inglés?", "exampleEn": "Do you speak English?" },
    { "id": "es-0092", "front": "nosotros", "back": "we", "example": "Nosotros vamos al parque.", "exampleEn": "We're going to the park." },
    { "id": "es-0093", "front": "ellos", "back": "they", "example": "Ellos viven cerca de aquí.", "exampleEn": "They live near here." },
    { "id": "es-0094", "front": "me", "back": "me", "example": "Me gusta este libro.", "exampleEn": "I like this book." },
    { "id": "es-0095", "front": "ser", "back": "to be (permanent)", "example": "Quiero ser médico.", "exampleEn": "I want to be a doctor." },
    { "id": "es-0096", "front": "estar", "back": "to be (state/location)", "example": "Voy a estar en casa.", "exampleEn": "I'm going to be at home." },
    { "id": "es-0097", "front": "tener", "back": "to have", "example": "Tengo dos perros.", "exampleEn": "I have two dogs." },
    { "id": "es-0098", "front": "hacer", "back": "to do / make", "example": "Tengo mucho que hacer hoy.", "exampleEn": "I have a lot to do today." },
    { "id": "es-0099", "front": "ir", "back": "to go", "example": "Voy a ir al mercado.", "exampleEn": "I'm going to go to the market." },
    { "id": "es-0100", "front": "ver", "back": "to see / watch", "example": "Quiero ver esa película.", "exampleEn": "I want to see that movie." },
    { "id": "es-0101", "front": "dar", "back": "to give", "example": "Te voy a dar un regalo.", "exampleEn": "I'm going to give you a gift." },
    { "id": "es-0102", "front": "saber", "back": "to know (facts)", "example": "No sé la respuesta.", "exampleEn": "I don't know the answer." },
    { "id": "es-0103", "front": "querer", "back": "to want / love", "example": "Quiero un vaso de agua.", "exampleEn": "I want a glass of water." },
    { "id": "es-0104", "front": "poder", "back": "to be able to", "example": "No puedo abrir la puerta.", "exampleEn": "I can't open the door." },
    { "id": "es-0105", "front": "decir", "back": "to say / tell", "example": "¿Qué quieres decir?", "exampleEn": "What do you mean?" },
    { "id": "es-0106", "front": "hablar", "back": "to speak", "example": "Hablo español todos los días.", "exampleEn": "I speak Spanish every day." },
    { "id": "es-0107", "front": "comer", "back": "to eat", "example": "Vamos a comer pizza.", "exampleEn": "We're going to eat pizza." },
    { "id": "es-0108", "front": "beber", "back": "to drink", "example": "Quiero beber agua fría.", "exampleEn": "I want to drink cold water." },
    { "id": "es-0109", "front": "vivir", "back": "to live", "example": "Quiero vivir cerca del mar.", "exampleEn": "I want to live near the sea." },
    { "id": "es-0110", "front": "trabajar", "back": "to work", "example": "Trabajo en una oficina.", "exampleEn": "I work in an office." },
    { "id": "es-0111", "front": "estudiar", "back": "to study", "example": "Estudio inglés por la noche.", "exampleEn": "I study English at night." },
    { "id": "es-0112", "front": "comprar", "back": "to buy", "example": "Voy a comprar pan.", "exampleEn": "I'm going to buy bread." },
    { "id": "es-0113", "front": "leer", "back": "to read", "example": "Me gusta leer novelas.", "exampleEn": "I like to read novels." },
    { "id": "es-0114", "front": "escribir", "back": "to write", "example": "Voy a escribir una carta.", "exampleEn": "I'm going to write a letter." },
    { "id": "es-0115", "front": "dormir", "back": "to sleep", "example": "Necesito dormir ocho horas.", "exampleEn": "I need to sleep eight hours." },
    { "id": "es-0116", "front": "comprender", "back": "to understand", "example": "No comprendo la pregunta.", "exampleEn": "I don't understand the question." },
    { "id": "es-0117", "front": "venir", "back": "to come", "example": "¿Puedes venir mañana?", "exampleEn": "Can you come tomorrow?" },
    { "id": "es-0118", "front": "llegar", "back": "to arrive", "example": "El tren va a llegar tarde.", "exampleEn": "The train is going to arrive late." },
    { "id": "es-0119", "front": "salir", "back": "to leave / go out", "example": "Salgo de casa a las ocho.", "exampleEn": "I leave the house at eight." },
    { "id": "es-0120", "front": "abrir", "back": "to open", "example": "¿Puedes abrir la ventana?", "exampleEn": "Can you open the window?" },
    { "id": "es-0121", "front": "cerrar", "back": "to close", "example": "Voy a cerrar la puerta.", "exampleEn": "I'm going to close the door." },
    { "id": "es-0122", "front": "gustar", "back": "to like (be pleasing)", "example": "Me gusta el chocolate.", "exampleEn": "I like chocolate." },
    { "id": "es-0123", "front": "pensar", "back": "to think", "example": "Pienso que tienes razón.", "exampleEn": "I think you're right." },
    { "id": "es-0124", "front": "necesitar", "back": "to need", "example": "Necesito ayuda con esto.", "exampleEn": "I need help with this." },
    { "id": "es-0125", "front": "usar", "back": "to use", "example": "Uso el teléfono cada día.", "exampleEn": "I use my phone every day." },
    { "id": "es-0126", "front": "esperar", "back": "to wait / hope", "example": "Te espero en la puerta.", "exampleEn": "I'll wait for you at the door." },
    { "id": "es-0127", "front": "caminar", "back": "to walk", "example": "Me gusta caminar por el parque.", "exampleEn": "I like to walk through the park." },
    { "id": "es-0128", "front": "escuchar", "back": "to listen", "example": "Escucho música en el coche.", "exampleEn": "I listen to music in the car." },
    { "id": "es-0129", "front": "jugar", "back": "to play", "example": "Los niños quieren jugar fuera.", "exampleEn": "The kids want to play outside." },
    { "id": "es-0130", "front": "la familia", "back": "family", "example": "Mi familia es muy grande.", "exampleEn": "My family is very large." },
    { "id": "es-0131", "front": "la madre", "back": "mother", "example": "Mi madre cocina muy bien.", "exampleEn": "My mother cooks very well." },
    { "id": "es-0132", "front": "el padre", "back": "father", "example": "Mi padre trabaja mucho.", "exampleEn": "My father works a lot." },
    { "id": "es-0133", "front": "el hijo", "back": "son", "example": "Su hijo tiene cinco años.", "exampleEn": "His son is five years old." },
    { "id": "es-0134", "front": "la hija", "back": "daughter", "example": "Mi hija estudia medicina.", "exampleEn": "My daughter is studying medicine." },
    { "id": "es-0135", "front": "el hermano", "back": "brother", "example": "Mi hermano vive en México.", "exampleEn": "My brother lives in Mexico." },
    { "id": "es-0136", "front": "la hermana", "back": "sister", "example": "Mi hermana es enfermera.", "exampleEn": "My sister is a nurse." },
    { "id": "es-0137", "front": "el amigo", "back": "friend (male)", "example": "Mi amigo viene esta noche.", "exampleEn": "My friend is coming tonight." },
    { "id": "es-0138", "front": "la amiga", "back": "friend (female)", "example": "Voy al cine con mi amiga.", "exampleEn": "I'm going to the movies with my friend." },
    { "id": "es-0139", "front": "el niño", "back": "child / boy", "example": "El niño juega en el jardín.", "exampleEn": "The boy is playing in the garden." },
    { "id": "es-0140", "front": "la mujer", "back": "woman / wife", "example": "Esa mujer es mi vecina.", "exampleEn": "That woman is my neighbor." },
    { "id": "es-0141", "front": "el hombre", "back": "man", "example": "El hombre lee el periódico.", "exampleEn": "The man is reading the newspaper." },
    { "id": "es-0142", "front": "la comida", "back": "food / meal", "example": "La comida está deliciosa.", "exampleEn": "The food is delicious." },
    { "id": "es-0143", "front": "el agua", "back": "water", "example": "Bebo mucha agua al día.", "exampleEn": "I drink a lot of water each day." },
    { "id": "es-0144", "front": "el pan", "back": "bread", "example": "Compro pan fresco cada mañana.", "exampleEn": "I buy fresh bread every morning." },
    { "id": "es-0145", "front": "la leche", "back": "milk", "example": "Tomo leche con el café.", "exampleEn": "I have milk with my coffee." },
    { "id": "es-0146", "front": "el café", "back": "coffee", "example": "Me gusta el café sin azúcar.", "exampleEn": "I like coffee without sugar." },
    { "id": "es-0147", "front": "la fruta", "back": "fruit", "example": "La fruta es muy sana.", "exampleEn": "Fruit is very healthy." },
    { "id": "es-0148", "front": "la manzana", "back": "apple", "example": "Como una manzana cada día.", "exampleEn": "I eat an apple every day." },
    { "id": "es-0149", "front": "la carne", "back": "meat", "example": "No como mucha carne.", "exampleEn": "I don't eat much meat." },
    { "id": "es-0150", "front": "el pescado", "back": "fish (food)", "example": "El pescado está muy fresco.", "exampleEn": "The fish is very fresh." },
    { "id": "es-0151", "front": "el huevo", "back": "egg", "example": "Quiero un huevo frito.", "exampleEn": "I want a fried egg." },
    { "id": "es-0152", "front": "el arroz", "back": "rice", "example": "El arroz con pollo está rico.", "exampleEn": "The rice with chicken is delicious." },
    { "id": "es-0153", "front": "la sal", "back": "salt", "example": "Falta un poco de sal.", "exampleEn": "It needs a little salt." },
    { "id": "es-0154", "front": "la casa", "back": "house / home", "example": "Mi casa está cerca del parque.", "exampleEn": "My house is close to the park." },
    { "id": "es-0155", "front": "la puerta", "back": "door", "example": "Cierra la puerta, por favor.", "exampleEn": "Close the door, please." },
    { "id": "es-0156", "front": "la ventana", "back": "window", "example": "Abre la ventana, hace calor.", "exampleEn": "Open the window, it's hot." },
    { "id": "es-0157", "front": "la mesa", "back": "table", "example": "La comida está en la mesa.", "exampleEn": "The food is on the table." },
    { "id": "es-0158", "front": "la silla", "back": "chair", "example": "Siéntate en esta silla.", "exampleEn": "Sit down in this chair." },
    { "id": "es-0159", "front": "la cama", "back": "bed", "example": "Voy a la cama temprano.", "exampleEn": "I go to bed early." },
    { "id": "es-0160", "front": "la cocina", "back": "kitchen", "example": "Mi madre está en la cocina.", "exampleEn": "My mother is in the kitchen." },
    { "id": "es-0161", "front": "el baño", "back": "bathroom", "example": "¿Dónde está el baño?", "exampleEn": "Where is the bathroom?" },
    { "id": "es-0162", "front": "la luz", "back": "light", "example": "Apaga la luz, por favor.", "exampleEn": "Turn off the light, please." },
    { "id": "es-0163", "front": "la llave", "back": "key", "example": "No encuentro mi llave.", "exampleEn": "I can't find my key." },
    { "id": "es-0164", "front": "el teléfono", "back": "telephone", "example": "Mi teléfono no funciona.", "exampleEn": "My phone isn't working." },
    { "id": "es-0165", "front": "el dinero", "back": "money", "example": "No tengo dinero hoy.", "exampleEn": "I don't have any money today." },
    { "id": "es-0166", "front": "el libro", "back": "book", "example": "Este libro es muy bueno.", "exampleEn": "This book is very good." },
    { "id": "es-0167", "front": "la cabeza", "back": "head", "example": "Me duele la cabeza.", "exampleEn": "I have a headache." },
    { "id": "es-0168", "front": "la mano", "back": "hand", "example": "Lávate las manos antes de comer.", "exampleEn": "Wash your hands before eating." },
    { "id": "es-0169", "front": "el ojo", "back": "eye", "example": "Ella tiene los ojos verdes.", "exampleEn": "She has green eyes." },
    { "id": "es-0170", "front": "la boca", "back": "mouth", "example": "Abre la boca, por favor.", "exampleEn": "Open your mouth, please." },
    { "id": "es-0171", "front": "el pie", "back": "foot", "example": "Me duele el pie derecho.", "exampleEn": "My right foot hurts." },
    { "id": "es-0172", "front": "el brazo", "back": "arm", "example": "Se rompió el brazo jugando.", "exampleEn": "He broke his arm while playing." },
    { "id": "es-0173", "front": "el corazón", "back": "heart", "example": "El corazón late muy rápido.", "exampleEn": "The heart is beating very fast." },
    { "id": "es-0174", "front": "la nariz", "back": "nose", "example": "Tengo la nariz fría.", "exampleEn": "My nose is cold." },
    { "id": "es-0175", "front": "la ciudad", "back": "city", "example": "Vivo en una ciudad grande.", "exampleEn": "I live in a big city." },
    { "id": "es-0176", "front": "la calle", "back": "street", "example": "La tienda está en esta calle.", "exampleEn": "The store is on this street." },
    { "id": "es-0177", "front": "la tienda", "back": "shop / store", "example": "Voy a la tienda a comprar leche.", "exampleEn": "I'm going to the store to buy milk." },
    { "id": "es-0178", "front": "el mercado", "back": "market", "example": "Compro verduras en el mercado.", "exampleEn": "I buy vegetables at the market." },
    { "id": "es-0179", "front": "el restaurante", "back": "restaurant", "example": "Cenamos en un restaurante italiano.", "exampleEn": "We had dinner at an Italian restaurant." },
    { "id": "es-0180", "front": "la escuela", "back": "school", "example": "Los niños van a la escuela.", "exampleEn": "The children go to school." },
    { "id": "es-0181", "front": "el hospital", "back": "hospital", "example": "El hospital está muy cerca.", "exampleEn": "The hospital is very close." },
    { "id": "es-0182", "front": "el parque", "back": "park", "example": "Caminamos por el parque.", "exampleEn": "We walk through the park." },
    { "id": "es-0183", "front": "el banco", "back": "bank", "example": "Voy al banco esta tarde.", "exampleEn": "I'm going to the bank this afternoon." },
    { "id": "es-0184", "front": "el trabajo", "back": "work / job", "example": "Mi trabajo es interesante.", "exampleEn": "My job is interesting." },
    { "id": "es-0185", "front": "la oficina", "back": "office", "example": "Trabajo en una oficina pequeña.", "exampleEn": "I work in a small office." },
    { "id": "es-0186", "front": "el jefe", "back": "boss", "example": "Mi jefe es muy amable.", "exampleEn": "My boss is very kind." },
    { "id": "es-0187", "front": "la empresa", "back": "company", "example": "Trabajo en una empresa grande.", "exampleEn": "I work at a large company." },
    { "id": "es-0188", "front": "el sol", "back": "sun", "example": "El sol brilla hoy.", "exampleEn": "The sun is shining today." },
    { "id": "es-0189", "front": "la luna", "back": "moon", "example": "La luna está muy clara esta noche.", "exampleEn": "The moon is very bright tonight." },
    { "id": "es-0190", "front": "el árbol", "back": "tree", "example": "El árbol da mucha sombra.", "exampleEn": "The tree gives a lot of shade." },
    { "id": "es-0191", "front": "la flor", "back": "flower", "example": "Le regalé una flor a mi madre.", "exampleEn": "I gave my mother a flower." },
    { "id": "es-0192", "front": "el mar", "back": "sea", "example": "Me gusta nadar en el mar.", "exampleEn": "I like swimming in the sea." },
    { "id": "es-0193", "front": "la montaña", "back": "mountain", "example": "Subimos a la montaña el domingo.", "exampleEn": "We climbed the mountain on Sunday." },
    { "id": "es-0194", "front": "el cielo", "back": "sky", "example": "El cielo está azul hoy.", "exampleEn": "The sky is blue today." },
    { "id": "es-0195", "front": "el perro", "back": "dog", "example": "Mi perro corre en el jardín.", "exampleEn": "My dog runs in the garden." },
    { "id": "es-0196", "front": "el gato", "back": "cat", "example": "El gato duerme en el sofá.", "exampleEn": "The cat sleeps on the sofa." },
    { "id": "es-0197", "front": "el coche", "back": "car", "example": "Mi coche es de color rojo.", "exampleEn": "My car is red." },
    { "id": "es-0198", "front": "el tren", "back": "train", "example": "El tren sale a las nueve.", "exampleEn": "The train leaves at nine." },
    { "id": "es-0199", "front": "el autobús", "back": "bus", "example": "Tomo el autobús al trabajo.", "exampleEn": "I take the bus to work." },
    { "id": "es-0200", "front": "el avión", "back": "airplane", "example": "El avión llega a las seis.", "exampleEn": "The plane arrives at six." },
    { "id": "es-0201", "front": "la bicicleta", "back": "bicycle", "example": "Voy al parque en bicicleta.", "exampleEn": "I go to the park by bike." },
    { "id": "es-0202", "front": "grande", "back": "big", "example": "Tienen una casa muy grande.", "exampleEn": "They have a very large house." },
    { "id": "es-0203", "front": "pequeño", "back": "small", "example": "Mi cuarto es pequeño.", "exampleEn": "My room is small." },
    { "id": "es-0204", "front": "bueno", "back": "good", "example": "Es un buen amigo.", "exampleEn": "He is a good friend." },
    { "id": "es-0205", "front": "malo", "back": "bad", "example": "Hoy hace mal tiempo.", "exampleEn": "The weather is bad today." },
    { "id": "es-0206", "front": "nuevo", "back": "new", "example": "Compré un coche nuevo.", "exampleEn": "I bought a new car." },
    { "id": "es-0207", "front": "viejo", "back": "old", "example": "Ese edificio es muy viejo.", "exampleEn": "That building is very old." },
    { "id": "es-0208", "front": "bonito", "back": "pretty / nice", "example": "Es un pueblo muy bonito.", "exampleEn": "It's a very pretty town." },
    { "id": "es-0209", "front": "alto", "back": "tall / high", "example": "Mi hermano es muy alto.", "exampleEn": "My brother is very tall." },
    { "id": "es-0210", "front": "bajo", "back": "short / low", "example": "La mesa es muy baja.", "exampleEn": "The table is very low." },
    { "id": "es-0211", "front": "fácil", "back": "easy", "example": "El examen fue muy fácil.", "exampleEn": "The exam was very easy." },
    { "id": "es-0212", "front": "difícil", "back": "difficult", "example": "Esta pregunta es difícil.", "exampleEn": "This question is difficult." },
    { "id": "es-0213", "front": "caliente", "back": "hot", "example": "El café está muy caliente.", "exampleEn": "The coffee is very hot." },
    { "id": "es-0214", "front": "frío", "back": "cold", "example": "El agua está fría.", "exampleEn": "The water is cold." },
    { "id": "es-0215", "front": "rápido", "back": "fast", "example": "Ese coche es muy rápido.", "exampleEn": "That car is very fast." },
    { "id": "es-0216", "front": "feliz", "back": "happy", "example": "Estoy muy feliz hoy.", "exampleEn": "I'm very happy today." },
    { "id": "es-0217", "front": "triste", "back": "sad", "example": "Se puso triste con la noticia.", "exampleEn": "She became sad when she heard the news." },
    { "id": "es-0218", "front": "caro", "back": "expensive", "example": "Ese reloj es muy caro.", "exampleEn": "That watch is very expensive." },
    { "id": "es-0219", "front": "barato", "back": "cheap", "example": "Este hotel es muy barato.", "exampleEn": "This hotel is very cheap." },
    { "id": "es-0220", "front": "rojo", "back": "red", "example": "Me gusta tu vestido rojo.", "exampleEn": "I like your red dress." },
    { "id": "es-0221", "front": "azul", "back": "blue", "example": "El cielo es azul.", "exampleEn": "The sky is blue." },
    { "id": "es-0222", "front": "verde", "back": "green", "example": "La hierba es verde.", "exampleEn": "The grass is green." },
    { "id": "es-0223", "front": "amarillo", "back": "yellow", "example": "El sol parece amarillo.", "exampleEn": "The sun looks yellow." },
    { "id": "es-0224", "front": "negro", "back": "black", "example": "Llevo un abrigo negro.", "exampleEn": "I'm wearing a black coat." },
    { "id": "es-0225", "front": "blanco", "back": "white", "example": "Las paredes son blancas.", "exampleEn": "The walls are white." },
    { "id": "es-0226", "front": "marrón", "back": "brown", "example": "Tiene los ojos de color marrón.", "exampleEn": "She has brown eyes." },
    { "id": "es-0227", "front": "la derecha", "back": "right", "example": "Gira a la derecha en la esquina.", "exampleEn": "Turn right at the corner." },
    { "id": "es-0228", "front": "la izquierda", "back": "left", "example": "La tienda está a la izquierda.", "exampleEn": "The store is on the left." },
    { "id": "es-0229", "front": "cerca", "back": "near", "example": "Vivo cerca de la escuela.", "exampleEn": "I live close to the school." },
    { "id": "es-0230", "front": "lejos", "back": "far", "example": "El aeropuerto está muy lejos.", "exampleEn": "The airport is very far away." },
    { "id": "es-0231", "front": "aquí", "back": "here", "example": "Ven aquí, por favor.", "exampleEn": "Come here, please." },
    { "id": "es-0232", "front": "el tiempo", "back": "weather / time", "example": "Hoy hace buen tiempo.", "exampleEn": "The weather is nice today." },
    { "id": "es-0233", "front": "la lluvia", "back": "rain", "example": "La lluvia no para de caer.", "exampleEn": "The rain won't stop falling." },
    { "id": "es-0234", "front": "el viento", "back": "wind", "example": "Hace mucho viento hoy.", "exampleEn": "It's very windy today." },
    { "id": "es-0235", "front": "la nieve", "back": "snow", "example": "La nieve cubre las montañas.", "exampleEn": "The snow covers the mountains." },
    { "id": "es-0236", "front": "el calor", "back": "heat", "example": "En verano hace mucho calor.", "exampleEn": "It gets very hot in summer." },
    { "id": "es-0237", "front": "el invierno", "back": "winter", "example": "El invierno es muy frío aquí.", "exampleEn": "Winter is very cold here." },
    { "id": "es-0238", "front": "el verano", "back": "summer", "example": "En verano vamos a la playa.", "exampleEn": "In summer we go to the beach." },
    { "id": "es-0239", "front": "y", "back": "and", "example": "Quiero pan y leche.", "exampleEn": "I want bread and milk." },
    { "id": "es-0240", "front": "o", "back": "or", "example": "¿Té o café?", "exampleEn": "Tea or coffee?" },
    { "id": "es-0241", "front": "pero", "back": "but", "example": "Quiero ir, pero estoy cansado.", "exampleEn": "I want to go, but I'm tired." },
    { "id": "es-0242", "front": "porque", "back": "because", "example": "No salgo porque llueve.", "exampleEn": "I'm not going out because it's raining." },
    { "id": "es-0243", "front": "también", "back": "also / too", "example": "Yo también quiero ir.", "exampleEn": "I want to go too." },
    { "id": "es-0244", "front": "muy", "back": "very", "example": "Estoy muy cansado.", "exampleEn": "I'm very tired." },
    { "id": "es-0245", "front": "mucho", "back": "a lot / much", "example": "Te quiero mucho.", "exampleEn": "I love you very much." },
    { "id": "es-0246", "front": "más", "back": "more", "example": "Quiero más café, por favor.", "exampleEn": "I'd like more coffee, please." },
    { "id": "es-0247", "front": "con", "back": "with", "example": "Voy al cine con mi amiga.", "exampleEn": "I'm going to the movies with my friend." },
    { "id": "es-0248", "front": "sin", "back": "without", "example": "Tomo el café sin azúcar.", "exampleEn": "I drink my coffee without sugar." },
    { "id": "es-0249", "front": "el nombre", "back": "name", "example": "¿Cuál es tu nombre?", "exampleEn": "What is your name?" },
    { "id": "es-0250", "front": "la pregunta", "back": "question", "example": "Tengo una pregunta para ti.", "exampleEn": "I have a question for you." },
    { "id": "es-0251", "front": "el menú", "back": "menu", "example": "¿Me puede traer el menú, por favor?", "exampleEn": "Can you bring me the menu, please?" },
    { "id": "es-0252", "front": "el aeropuerto", "back": "airport", "example": "El aeropuerto está muy lejos del centro.", "exampleEn": "The airport is very far from the city center." },
    { "id": "es-0253", "front": "el salario", "back": "salary, wage", "example": "Mi salario aumentó este año.", "exampleEn": "My salary increased this year." },
    { "id": "es-0254", "front": "el abuelo", "back": "grandfather", "example": "Mi abuelo vive con nosotros en casa.", "exampleEn": "My grandfather lives with us at home." },
    { "id": "es-0255", "front": "el cuerpo", "back": "the body", "example": "El cuerpo humano tiene muchos huesos.", "exampleEn": "The human body has many bones." },
    { "id": "es-0256", "front": "la carta", "back": "menu / letter", "example": "El camarero nos trajo la carta enseguida.", "exampleEn": "The waiter brought us the menu right away." },
    { "id": "es-0257", "front": "la estación de tren", "back": "train station", "example": "Nos encontramos en la estación de tren.", "exampleEn": "We meet at the train station." },
    { "id": "es-0258", "front": "el sueldo", "back": "pay, wages", "example": "El sueldo mínimo es muy bajo aquí.", "exampleEn": "The minimum wage is very low here." },
    { "id": "es-0259", "front": "la abuela", "back": "grandmother", "example": "La abuela prepara el desayuno cada mañana.", "exampleEn": "Grandmother prepares breakfast every morning." },
    { "id": "es-0260", "front": "la piel", "back": "skin", "example": "Tienes la piel muy suave.", "exampleEn": "You have very soft skin." },
    { "id": "es-0261", "front": "el camarero", "back": "waiter", "example": "El camarero tomó nuestro pedido.", "exampleEn": "The waiter took our order." },
    { "id": "es-0262", "front": "el metro", "back": "subway / metro", "example": "Tomo el metro para ir al trabajo.", "exampleEn": "I take the subway to go to work." },
    { "id": "es-0263", "front": "la factura", "back": "invoice, bill", "example": "Necesito pagar la factura del gas.", "exampleEn": "I need to pay the gas bill." },
    { "id": "es-0264", "front": "el marido", "back": "husband", "example": "Mi marido llega a casa a las seis.", "exampleEn": "My husband arrives home at six." },
    { "id": "es-0265", "front": "el hueso", "back": "bone", "example": "Me duele un hueso del pie.", "exampleEn": "One of the bones in my foot hurts." },
    { "id": "es-0266", "front": "la camarera", "back": "waitress", "example": "La camarera nos recomendó el pollo.", "exampleEn": "The waitress recommended the chicken to us." },
    { "id": "es-0267", "front": "el taxi", "back": "taxi", "example": "Pedimos un taxi desde el hotel.", "exampleEn": "We ordered a taxi from the hotel." },
    { "id": "es-0268", "front": "el presupuesto", "back": "budget", "example": "El presupuesto del proyecto es limitado.", "exampleEn": "The project budget is limited." },
    { "id": "es-0269", "front": "la esposa", "back": "wife", "example": "Su esposa trabaja en el hospital.", "exampleEn": "His wife works at the hospital." },
    { "id": "es-0270", "front": "el músculo", "back": "muscle", "example": "Ese músculo me duele después del ejercicio.", "exampleEn": "That muscle hurts after exercise." },
    { "id": "es-0271", "front": "la cuenta", "back": "the bill / check", "example": "¿Nos puede traer la cuenta?", "exampleEn": "Can you bring us the bill?" },
    { "id": "es-0272", "front": "el barco", "back": "boat / ship", "example": "Cruzamos el río en barco.", "exampleEn": "We crossed the river by boat." },
    { "id": "es-0273", "front": "la reunión", "back": "meeting", "example": "Tengo una reunión importante a las tres.", "exampleEn": "I have an important meeting at three." },
    { "id": "es-0274", "front": "el hijo único", "back": "only child", "example": "Carlos es hijo único y tiene su propio cuarto.", "exampleEn": "Carlos is an only child and has his own room." },
    { "id": "es-0275", "front": "la espalda", "back": "back (body)", "example": "Me duele mucho la espalda hoy.", "exampleEn": "My back hurts a lot today." },
    { "id": "es-0276", "front": "la propina", "back": "tip / gratuity", "example": "Dejamos una buena propina.", "exampleEn": "We left a good tip." },
    { "id": "es-0277", "front": "el billete", "back": "ticket", "example": "Compré el billete de ida y vuelta.", "exampleEn": "I bought the round-trip ticket." },
    { "id": "es-0278", "front": "el contrato", "back": "contract", "example": "Firmé el contrato esta mañana.", "exampleEn": "I signed the contract this morning." },
    { "id": "es-0279", "front": "el sobrino", "back": "nephew", "example": "Mi sobrino tiene cinco años.", "exampleEn": "My nephew is five years old." },
    { "id": "es-0280", "front": "el pecho", "back": "chest", "example": "Siento dolor en el pecho cuando respiro.", "exampleEn": "I feel pain in my chest when I breathe." },
    { "id": "es-0281", "front": "la reserva", "back": "reservation", "example": "Tengo una reserva para las ocho.", "exampleEn": "I have a reservation for eight o'clock." },
    { "id": "es-0282", "front": "el pasaporte", "back": "passport", "example": "No olvides tu pasaporte en casa.", "exampleEn": "Don't forget your passport at home." },
    { "id": "es-0283", "front": "la cuenta bancaria", "back": "bank account", "example": "Abrí una cuenta bancaria nueva.", "exampleEn": "I opened a new bank account." },
    { "id": "es-0284", "front": "la sobrina", "back": "niece", "example": "La sobrina de Ana visita los domingos.", "exampleEn": "Ana's niece visits on Sundays." },
    { "id": "es-0285", "front": "el hombro", "back": "shoulder", "example": "Lleva la mochila en el hombro derecho.", "exampleEn": "He carries the backpack on his right shoulder." },
    { "id": "es-0286", "front": "el plato", "back": "plate / dish", "example": "El plato del día es paella.", "exampleEn": "Today's dish is paella." },
    { "id": "es-0287", "front": "la maleta", "back": "suitcase", "example": "Mi maleta pesa demasiado.", "exampleEn": "My suitcase weighs too much." },
    { "id": "es-0288", "front": "el préstamo", "back": "loan", "example": "Pedí un préstamo para comprar el coche.", "exampleEn": "I applied for a loan to buy the car." },
    { "id": "es-0289", "front": "el cuarto", "back": "bedroom / room", "example": "Ordeno mi cuarto antes de desayunar.", "exampleEn": "I tidy my room before having breakfast." },
    { "id": "es-0290", "front": "la rodilla", "back": "knee", "example": "Me lastimé la rodilla jugando fútbol.", "exampleEn": "I hurt my knee playing soccer." },
    { "id": "es-0291", "front": "el postre", "back": "dessert", "example": "De postre quiero helado de chocolate.", "exampleEn": "For dessert I want chocolate ice cream." },
    { "id": "es-0292", "front": "el vuelo", "back": "flight", "example": "El vuelo sale a las ocho de la mañana.", "exampleEn": "The flight leaves at eight in the morning." },
    { "id": "es-0293", "front": "la deuda", "back": "debt", "example": "Quiero pagar mi deuda pronto.", "exampleEn": "I want to pay off my debt soon." },
    { "id": "es-0294", "front": "el salón", "back": "living room", "example": "La familia se reúne en el salón por la tarde.", "exampleEn": "The family gathers in the living room in the afternoon." },
    { "id": "es-0295", "front": "el cuello", "back": "neck", "example": "Tengo el cuello rígido esta mañana.", "exampleEn": "My neck is stiff this morning." },
    { "id": "es-0296", "front": "el primer plato", "back": "first course / starter", "example": "De primer plato pedí sopa de tomate.", "exampleEn": "For the first course I ordered tomato soup." },
    { "id": "es-0297", "front": "la salida", "back": "departure / exit", "example": "La salida del tren es en cinco minutos.", "exampleEn": "The train departure is in five minutes." },
    { "id": "es-0298", "front": "la inversión", "back": "investment", "example": "Es una buena inversión a largo plazo.", "exampleEn": "It is a good long-term investment." },
    { "id": "es-0299", "front": "el comedor", "back": "dining room", "example": "Cenamos juntos en el comedor.", "exampleEn": "We have dinner together in the dining room." },
    { "id": "es-0300", "front": "la oreja", "back": "ear (outer)", "example": "Le duele la oreja izquierda.", "exampleEn": "Her left ear hurts." },
    { "id": "es-0301", "front": "el segundo plato", "back": "main course", "example": "De segundo plato tomé filete de ternera.", "exampleEn": "For the main course I had a veal steak." },
    { "id": "es-0302", "front": "la llegada", "back": "arrival", "example": "La llegada del vuelo se retrasa una hora.", "exampleEn": "The flight arrival is delayed one hour." },
    { "id": "es-0303", "front": "el descuento", "back": "discount", "example": "Me dieron un descuento del diez por ciento.", "exampleEn": "They gave me a ten percent discount." },
    { "id": "es-0304", "front": "el jardín", "back": "garden / yard", "example": "Los niños juegan en el jardín.", "exampleEn": "The children play in the garden." },
    { "id": "es-0305", "front": "el diente", "back": "tooth", "example": "Me duele un diente desde ayer.", "exampleEn": "A tooth has been hurting since yesterday." },
    { "id": "es-0306", "front": "el desayuno", "back": "breakfast", "example": "El desayuno incluye tostadas y zumo.", "exampleEn": "Breakfast includes toast and juice." },
    { "id": "es-0307", "front": "el andén", "back": "platform (train)", "example": "El tren sale del andén número tres.", "exampleEn": "The train leaves from platform three." },
    { "id": "es-0308", "front": "la ganancia", "back": "profit, earnings", "example": "La empresa reportó una gran ganancia.", "exampleEn": "The company reported a large profit." },
    { "id": "es-0309", "front": "el piso", "back": "apartment / floor", "example": "Vivimos en un piso en el centro.", "exampleEn": "We live in an apartment downtown." },
    { "id": "es-0310", "front": "la lengua", "back": "tongue", "example": "Me quemé la lengua con el té.", "exampleEn": "I burned my tongue with the tea." },
    { "id": "es-0311", "front": "el almuerzo", "back": "lunch", "example": "Comemos el almuerzo a las dos.", "exampleEn": "We eat lunch at two o'clock." },
    { "id": "es-0312", "front": "la parada", "back": "stop (bus/metro)", "example": "La próxima parada es la Plaza Mayor.", "exampleEn": "The next stop is Plaza Mayor." },
    { "id": "es-0313", "front": "la pérdida", "back": "loss", "example": "Sufrieron una pérdida económica importante.", "exampleEn": "They suffered a significant financial loss." },
    { "id": "es-0314", "front": "el despertador", "back": "alarm clock", "example": "Pongo el despertador a las siete.", "exampleEn": "I set the alarm clock for seven." },
    { "id": "es-0315", "front": "el dedo", "back": "finger / toe", "example": "Me corté el dedo con un cuchillo.", "exampleEn": "I cut my finger with a knife." },
    { "id": "es-0316", "front": "la cena", "back": "dinner / supper", "example": "La cena estuvo deliciosa anoche.", "exampleEn": "Dinner was delicious last night." },
    { "id": "es-0317", "front": "el semáforo", "back": "traffic light", "example": "Para en el semáforo rojo.", "exampleEn": "Stop at the red traffic light." },
    { "id": "es-0318", "front": "el impuesto", "back": "tax", "example": "Hay que pagar el impuesto antes de abril.", "exampleEn": "You have to pay the tax before April." },
    { "id": "es-0319", "front": "despertarse", "back": "to wake up", "example": "Me despierto temprano todos los días.", "exampleEn": "I wake up early every day." },
    { "id": "es-0320", "front": "el tobillo", "back": "ankle", "example": "Se torció el tobillo en las escaleras.", "exampleEn": "She twisted her ankle on the stairs." },
    { "id": "es-0321", "front": "el aperitivo", "back": "appetizer / aperitif", "example": "Tomamos unas aceitunas de aperitivo.", "exampleEn": "We had some olives as an appetizer." },
    { "id": "es-0322", "front": "el cruce", "back": "crossroads / intersection", "example": "Gira a la derecha en el cruce.", "exampleEn": "Turn right at the intersection." },
    { "id": "es-0323", "front": "la tarjeta de crédito", "back": "credit card", "example": "Pagué con mi tarjeta de crédito.", "exampleEn": "I paid with my credit card." },
    { "id": "es-0324", "front": "ducharse", "back": "to shower", "example": "Ella se ducha antes de ir al trabajo.", "exampleEn": "She showers before going to work." },
    { "id": "es-0325", "front": "el estómago", "back": "stomach", "example": "Me duele el estómago después de comer.", "exampleEn": "My stomach hurts after eating." },
    { "id": "es-0326", "front": "la sopa", "back": "soup", "example": "La sopa de lentejas está muy rica.", "exampleEn": "The lentil soup is very tasty." },
    { "id": "es-0327", "front": "la acera", "back": "sidewalk / pavement", "example": "Camina por la acera, no por la calle.", "exampleEn": "Walk on the sidewalk, not on the road." },
    { "id": "es-0328", "front": "el efectivo", "back": "cash", "example": "Prefiero pagar en efectivo.", "exampleEn": "I prefer to pay in cash." },
    { "id": "es-0329", "front": "lavarse los dientes", "back": "to brush one's teeth", "example": "Me lavo los dientes después de cada comida.", "exampleEn": "I brush my teeth after every meal." },
    { "id": "es-0330", "front": "la salud", "back": "health", "example": "La salud es lo más importante.", "exampleEn": "Health is the most important thing." },
    { "id": "es-0331", "front": "la ensalada", "back": "salad", "example": "Quiero una ensalada mixta, por favor.", "exampleEn": "I would like a mixed salad, please." },
    { "id": "es-0332", "front": "el puente", "back": "bridge", "example": "Cruzamos el puente sobre el río.", "exampleEn": "We cross the bridge over the river." },
    { "id": "es-0333", "front": "la bolsa de valores", "back": "stock market", "example": "La bolsa de valores subió hoy.", "exampleEn": "The stock market went up today." },
    { "id": "es-0334", "front": "vestirse", "back": "to get dressed", "example": "Los niños se visten solos por la mañana.", "exampleEn": "The children get dressed on their own in the morning." },
    { "id": "es-0335", "front": "la enfermedad", "back": "illness / disease", "example": "Esa enfermedad se contagia fácilmente.", "exampleEn": "That illness spreads easily." },
    { "id": "es-0336", "front": "el bocadillo", "back": "sandwich (baguette)", "example": "Me comí un bocadillo de jamón.", "exampleEn": "I ate a ham sandwich." },
    { "id": "es-0337", "front": "la rotonda", "back": "roundabout", "example": "Toma la segunda salida en la rotonda.", "exampleEn": "Take the second exit at the roundabout." },
    { "id": "es-0338", "front": "el empleado", "back": "employee", "example": "El empleado llegó tarde a la oficina.", "exampleEn": "The employee arrived late to the office." },
    { "id": "es-0339", "front": "desayunar", "back": "to have breakfast", "example": "Solemos desayunar a las ocho en familia.", "exampleEn": "We usually have breakfast at eight as a family." },
    { "id": "es-0340", "front": "el dolor", "back": "pain / ache", "example": "El dolor de cabeza no me deja trabajar.", "exampleEn": "The headache won't let me work." },
    { "id": "es-0341", "front": "el sándwich", "back": "sandwich (sliced bread)", "example": "Preparo un sándwich de queso para llevar.", "exampleEn": "I'm making a cheese sandwich to go." },
    { "id": "es-0342", "front": "todo recto", "back": "straight ahead", "example": "Sigue todo recto hasta el final.", "exampleEn": "Keep going straight ahead to the end." },
    { "id": "es-0343", "front": "el cliente", "back": "client, customer", "example": "El cliente siempre tiene la razón.", "exampleEn": "The customer is always right." },
    { "id": "es-0344", "front": "almorzar", "back": "to have lunch", "example": "¿Dónde almuerzas hoy?", "exampleEn": "Where are you having lunch today?" },
    { "id": "es-0345", "front": "la fiebre", "back": "fever", "example": "El niño tiene fiebre alta.", "exampleEn": "The child has a high fever." },
    { "id": "es-0346", "front": "la tapa", "back": "tapa / small snack", "example": "En ese bar sirven tapas gratis.", "exampleEn": "In that bar they serve free tapas." },
    { "id": "es-0347", "front": "girar", "back": "to turn", "example": "Tienes que girar a la izquierda aquí.", "exampleEn": "You have to turn left here." },
    { "id": "es-0348", "front": "el proveedor", "back": "supplier, vendor", "example": "Buscamos un proveedor confiable.", "exampleEn": "We are looking for a reliable supplier." },
    { "id": "es-0349", "front": "cenar", "back": "to have dinner", "example": "Cenamos a las nueve en España.", "exampleEn": "We have dinner at nine in Spain." },
    { "id": "es-0350", "front": "la tos", "back": "cough", "example": "Tengo tos desde hace tres días.", "exampleEn": "I have had a cough for three days." },
    { "id": "es-0351", "front": "el aceite", "back": "oil", "example": "Añade un poco de aceite de oliva.", "exampleEn": "Add a little olive oil." },
    { "id": "es-0352", "front": "cruzar", "back": "to cross", "example": "Hay que cruzar la avenida con cuidado.", "exampleEn": "You have to cross the avenue carefully." },
    { "id": "es-0353", "front": "la solicitud", "back": "application, request", "example": "Envié mi solicitud de empleo ayer.", "exampleEn": "I sent my job application yesterday." },
    { "id": "es-0354", "front": "acostarse", "back": "to go to bed", "example": "Los niños se acuestan a las diez.", "exampleEn": "The children go to bed at ten." },
    { "id": "es-0355", "front": "el resfriado", "back": "cold (illness)", "example": "Me agarré un resfriado esta semana.", "exampleEn": "I caught a cold this week." },
    { "id": "es-0356", "front": "el vinagre", "back": "vinegar", "example": "Aliña la ensalada con aceite y vinagre.", "exampleEn": "Dress the salad with oil and vinegar." },
    { "id": "es-0357", "front": "el mapa", "back": "map", "example": "Consulta el mapa antes de salir.", "exampleEn": "Check the map before leaving." },
    { "id": "es-0358", "front": "el currículum", "back": "résumé, CV", "example": "Actualicé mi currículum esta semana.", "exampleEn": "I updated my résumé this week." },
    { "id": "es-0359", "front": "la rutina", "back": "routine", "example": "Tengo una rutina fija cada mañana.", "exampleEn": "I have a fixed routine every morning." },
    { "id": "es-0360", "front": "el medicamento", "back": "medicine / medication", "example": "Toma el medicamento dos veces al día.", "exampleEn": "Take the medicine twice a day." },
    { "id": "es-0361", "front": "la pimienta", "back": "pepper (spice)", "example": "Le pongo pimienta negra a la carne.", "exampleEn": "I put black pepper on the meat." },
    { "id": "es-0362", "front": "la dirección", "back": "address / direction", "example": "¿Cuál es la dirección del hotel?", "exampleEn": "What is the address of the hotel?" },
    { "id": "es-0363", "front": "la entrevista", "back": "interview", "example": "Tengo una entrevista de trabajo mañana.", "exampleEn": "I have a job interview tomorrow." },
    { "id": "es-0364", "front": "la ropa", "back": "clothing / clothes", "example": "Necesito lavar la ropa hoy.", "exampleEn": "I need to do the laundry today." },
    { "id": "es-0365", "front": "la pastilla", "back": "pill / tablet", "example": "El médico me recetó una pastilla para el dolor.", "exampleEn": "The doctor prescribed me a pill for the pain." },
    { "id": "es-0366", "front": "el azúcar", "back": "sugar", "example": "¿Cuánto azúcar quieres en el café?", "exampleEn": "How much sugar do you want in your coffee?" },
    { "id": "es-0367", "front": "perderse", "back": "to get lost", "example": "Es fácil perderse en esta ciudad.", "exampleEn": "It's easy to get lost in this city." },
    { "id": "es-0368", "front": "el negocio", "back": "business, deal", "example": "Abrió un negocio de comida rápida.", "exampleEn": "He opened a fast food business." },
    { "id": "es-0369", "front": "la camisa", "back": "shirt", "example": "Lleva una camisa blanca al trabajo.", "exampleEn": "He wears a white shirt to work." },
    { "id": "es-0370", "front": "la herida", "back": "wound / injury", "example": "Limpié la herida con agua.", "exampleEn": "I cleaned the wound with water." },
    { "id": "es-0371", "front": "la harina", "back": "flour", "example": "Necesito harina para hacer el pastel.", "exampleEn": "I need flour to make the cake." },
    { "id": "es-0372", "front": "el hotel", "back": "hotel", "example": "Reservé una habitación en el hotel.", "exampleEn": "I booked a room at the hotel." },
    { "id": "es-0373", "front": "la competencia", "back": "competition", "example": "La competencia en este mercado es fuerte.", "exampleEn": "Competition in this market is fierce." },
    { "id": "es-0374", "front": "la camiseta", "back": "T-shirt", "example": "Prefiero una camiseta cómoda en casa.", "exampleEn": "I prefer a comfortable T-shirt at home." },
    { "id": "es-0375", "front": "el médico", "back": "doctor", "example": "El médico me dijo que descanse.", "exampleEn": "The doctor told me to rest." },
    { "id": "es-0376", "front": "la mantequilla", "back": "butter", "example": "Unta la tostada con mantequilla.", "exampleEn": "Spread butter on the toast." },
    { "id": "es-0377", "front": "la habitación", "back": "room", "example": "La habitación tiene una vista al mar.", "exampleEn": "The room has a view of the sea." },
    { "id": "es-0378", "front": "el producto", "back": "product", "example": "Lanzaron un producto nuevo esta semana.", "exampleEn": "They launched a new product this week." },
    { "id": "es-0379", "front": "el pantalón", "back": "trousers / pants", "example": "Ese pantalón azul te queda bien.", "exampleEn": "Those blue trousers suit you well." },
    { "id": "es-0380", "front": "cansado", "back": "tired", "example": "Estoy muy cansado después del trabajo.", "exampleEn": "I am very tired after work." },
    { "id": "es-0381", "front": "el queso", "back": "cheese", "example": "Este queso manchego está muy bueno.", "exampleEn": "This Manchego cheese is very good." },
    { "id": "es-0382", "front": "la recepción", "back": "reception / front desk", "example": "Deja las llaves en la recepción.", "exampleEn": "Leave the keys at the reception desk." },
    { "id": "es-0383", "front": "el servicio", "back": "service", "example": "El servicio al cliente es excelente.", "exampleEn": "The customer service is excellent." },
    { "id": "es-0384", "front": "la falda", "back": "skirt", "example": "Ella lleva una falda larga hoy.", "exampleEn": "She is wearing a long skirt today." },
    { "id": "es-0385", "front": "enfermo", "back": "sick / ill", "example": "Mi hermano está enfermo en cama.", "exampleEn": "My brother is sick in bed." },
    { "id": "es-0386", "front": "el jamón", "back": "ham", "example": "Compramos jamón serrano en el mercado.", "exampleEn": "We bought cured ham at the market." },
    { "id": "es-0387", "front": "el equipaje", "back": "luggage / baggage", "example": "Facturamos el equipaje en el mostrador.", "exampleEn": "We checked the luggage at the counter." },
    { "id": "es-0388", "front": "el pedido", "back": "order", "example": "El pedido llegará mañana a casa.", "exampleEn": "The order will arrive at home tomorrow." },
    { "id": "es-0389", "front": "el vestido", "back": "dress", "example": "Compré un vestido para la boda.", "exampleEn": "I bought a dress for the wedding." },
    { "id": "es-0390", "front": "sano", "back": "healthy", "example": "Quiero llevar una vida sana.", "exampleEn": "I want to lead a healthy life." },
    { "id": "es-0391", "front": "el pollo", "back": "chicken", "example": "El pollo asado huele muy bien.", "exampleEn": "The roast chicken smells really good." },
    { "id": "es-0392", "front": "la aduana", "back": "customs", "example": "Pasamos por la aduana sin problemas.", "exampleEn": "We went through customs without any problems." },
    { "id": "es-0393", "front": "la entrega", "back": "delivery", "example": "La entrega fue rápida y puntual.", "exampleEn": "The delivery was fast and on time." },
    { "id": "es-0394", "front": "el abrigo", "back": "coat / overcoat", "example": "Ponte el abrigo; hace mucho frío.", "exampleEn": "Put on your coat; it is very cold." },
    { "id": "es-0395", "front": "la alegría", "back": "joy / happiness", "example": "Su llegada me llenó de alegría.", "exampleEn": "Her arrival filled me with joy." },
    { "id": "es-0396", "front": "el cerdo", "back": "pork", "example": "La chuleta de cerdo está en el menú.", "exampleEn": "The pork chop is on the menu." },
    { "id": "es-0397", "front": "el visado", "back": "visa", "example": "Necesito un visado para entrar al país.", "exampleEn": "I need a visa to enter the country." },
    { "id": "es-0398", "front": "el gerente", "back": "manager", "example": "El gerente aprobó el nuevo proyecto.", "exampleEn": "The manager approved the new project." },
    { "id": "es-0399", "front": "la chaqueta", "back": "jacket", "example": "Dejé mi chaqueta en la silla.", "exampleEn": "I left my jacket on the chair." },
    { "id": "es-0400", "front": "el miedo", "back": "fear", "example": "Los niños tienen miedo a la oscuridad.", "exampleEn": "Children are afraid of the dark." },
    { "id": "es-0401", "front": "el marisco", "back": "seafood / shellfish", "example": "En la costa comemos mucho marisco.", "exampleEn": "On the coast we eat a lot of seafood." },
    { "id": "es-0402", "front": "la tarjeta de embarque", "back": "boarding pass", "example": "Muestra tu tarjeta de embarque en la puerta.", "exampleEn": "Show your boarding pass at the gate." },
    { "id": "es-0403", "front": "la clase", "back": "class, lesson", "example": "La clase de historia empieza a las nueve.", "exampleEn": "History class starts at nine." },
    { "id": "es-0404", "front": "los zapatos", "back": "shoes", "example": "Estos zapatos me aprietan un poco.", "exampleEn": "These shoes are a bit tight on me." },
    { "id": "es-0405", "front": "la rabia", "back": "anger / rage", "example": "Sentí mucha rabia al escuchar eso.", "exampleEn": "I felt a lot of anger when I heard that." },
    { "id": "es-0406", "front": "los camarones", "back": "shrimp / prawns", "example": "Los camarones a la plancha están riquísimos.", "exampleEn": "The grilled shrimp are delicious." },
    { "id": "es-0407", "front": "el turista", "back": "tourist", "example": "La ciudad está llena de turistas en verano.", "exampleEn": "The city is full of tourists in summer." },
    { "id": "es-0408", "front": "el profesor", "back": "teacher, professor", "example": "El profesor explicó el tema muy bien.", "exampleEn": "The teacher explained the topic very well." },
    { "id": "es-0409", "front": "las zapatillas", "back": "sneakers / slippers", "example": "En casa uso zapatillas para estar cómodo.", "exampleEn": "At home I wear slippers to be comfortable." },
    { "id": "es-0410", "front": "la vergüenza", "back": "shame / embarrassment", "example": "Le dio vergüenza hablar en público.", "exampleEn": "She felt embarrassed speaking in public." },
    { "id": "es-0411", "front": "la cebolla", "back": "onion", "example": "Sofríe la cebolla en aceite caliente.", "exampleEn": "Sauté the onion in hot oil." },
    { "id": "es-0412", "front": "el viaje", "back": "trip / journey", "example": "El viaje en tren dura dos horas.", "exampleEn": "The train journey lasts two hours." },
    { "id": "es-0413", "front": "el alumno", "back": "student, pupil", "example": "El alumno hizo todas las tareas.", "exampleEn": "The student did all the homework." },
    { "id": "es-0414", "front": "los calcetines", "back": "socks", "example": "No encuentro los calcetines limpios.", "exampleEn": "I cannot find the clean socks." },
    { "id": "es-0415", "front": "la sorpresa", "back": "surprise", "example": "La fiesta fue una sorpresa para ella.", "exampleEn": "The party was a surprise for her." },
    { "id": "es-0416", "front": "el ajo", "back": "garlic", "example": "Esta salsa lleva mucho ajo.", "exampleEn": "This sauce has a lot of garlic in it." },
    { "id": "es-0417", "front": "viajar", "back": "to travel", "example": "Me encanta viajar a países nuevos.", "exampleEn": "I love to travel to new countries." },
    { "id": "es-0418", "front": "la tarea", "back": "homework, assignment", "example": "No terminé la tarea a tiempo.", "exampleEn": "I did not finish the homework on time." },
    { "id": "es-0419", "front": "el jersey", "back": "sweater / jumper", "example": "Me pongo el jersey cuando tengo frío.", "exampleEn": "I put on my sweater when I am cold." },
    { "id": "es-0420", "front": "la soledad", "back": "loneliness", "example": "Siente mucha soledad viviendo solo.", "exampleEn": "He feels a lot of loneliness living alone." },
    { "id": "es-0421", "front": "el tomate", "back": "tomato", "example": "Cortamos el tomate para la ensalada.", "exampleEn": "We sliced the tomato for the salad." },
    { "id": "es-0422", "front": "el destino", "back": "destination", "example": "¿Cuál es tu destino final?", "exampleEn": "What is your final destination?" },
    { "id": "es-0423", "front": "el examen", "back": "exam, test", "example": "Estudié mucho para el examen final.", "exampleEn": "I studied a lot for the final exam." },
    { "id": "es-0424", "front": "el cinturón", "back": "belt", "example": "Necesito un cinturón para este pantalón.", "exampleEn": "I need a belt for these trousers." },
    { "id": "es-0425", "front": "el orgullo", "back": "pride", "example": "Siento orgullo por lo que lograste.", "exampleEn": "I feel pride for what you achieved." },
    { "id": "es-0426", "front": "la patata", "back": "potato", "example": "La tortilla española se hace con patata.", "exampleEn": "Spanish omelette is made with potato." },
    { "id": "es-0427", "front": "el centro", "back": "city center / downtown", "example": "El museo está en el centro de la ciudad.", "exampleEn": "The museum is in the city center." },
    { "id": "es-0428", "front": "la nota", "back": "grade, mark", "example": "Saqué una buena nota en matemáticas.", "exampleEn": "I got a good grade in mathematics." },
    { "id": "es-0429", "front": "el bolso", "back": "handbag / purse", "example": "Ella lleva el bolso al supermercado.", "exampleEn": "She takes her handbag to the supermarket." },
    { "id": "es-0430", "front": "la esperanza", "back": "hope", "example": "Tenemos esperanza de que todo mejore.", "exampleEn": "We have hope that everything will improve." },
    { "id": "es-0431", "front": "la zanahoria", "back": "carrot", "example": "Añade zanahoria rallada a la ensalada.", "exampleEn": "Add grated carrot to the salad." },
    { "id": "es-0432", "front": "el barrio", "back": "neighborhood", "example": "Vivo en un barrio tranquilo.", "exampleEn": "I live in a quiet neighborhood." },
    { "id": "es-0433", "front": "la carrera", "back": "degree program, career", "example": "Estudia la carrera de medicina.", "exampleEn": "She is studying the medicine degree program." },
    { "id": "es-0434", "front": "las gafas", "back": "glasses", "example": "Mi padre lleva gafas para leer.", "exampleEn": "My father wears glasses to read." },
    { "id": "es-0435", "front": "nervioso", "back": "nervous", "example": "Estoy nervioso antes del examen.", "exampleEn": "I am nervous before the exam." },
    { "id": "es-0436", "front": "el pimiento", "back": "bell pepper", "example": "El pimiento rojo es más dulce.", "exampleEn": "The red bell pepper is sweeter." },
    { "id": "es-0437", "front": "la plaza", "back": "square / plaza", "example": "La plaza está llena de gente los domingos.", "exampleEn": "The square is full of people on Sundays." },
    { "id": "es-0438", "front": "la universidad", "back": "university", "example": "Empezó la universidad el año pasado.", "exampleEn": "He started university last year." },
    { "id": "es-0439", "front": "el probador", "back": "fitting room", "example": "Puedo probarme la camisa en el probador.", "exampleEn": "I can try on the shirt in the fitting room." },
    { "id": "es-0440", "front": "emocionado", "back": "excited", "example": "Está emocionado con el viaje.", "exampleEn": "He is excited about the trip." },
    { "id": "es-0441", "front": "la lechuga", "back": "lettuce", "example": "Lava bien la lechuga antes de usarla.", "exampleEn": "Wash the lettuce well before using it." },
    { "id": "es-0442", "front": "la avenida", "back": "avenue", "example": "Vive en una avenida muy transitada.", "exampleEn": "She lives on a very busy avenue." },
    { "id": "es-0443", "front": "la beca", "back": "scholarship", "example": "Ganó una beca para estudiar en Europa.", "exampleEn": "She won a scholarship to study in Europe." },
    { "id": "es-0444", "front": "la talla", "back": "size (clothing)", "example": "¿Qué talla usas?", "exampleEn": "What size do you wear?" },
    { "id": "es-0445", "front": "enojado", "back": "angry", "example": "Está enojado porque llegaste tarde.", "exampleEn": "He is angry because you arrived late." },
    { "id": "es-0446", "front": "el limón", "back": "lemon", "example": "Exprime el limón sobre el pescado.", "exampleEn": "Squeeze the lemon over the fish." },
    { "id": "es-0447", "front": "la esquina", "back": "corner", "example": "Espérame en la esquina de la calle.", "exampleEn": "Wait for me on the street corner." },
    { "id": "es-0448", "front": "el horario", "back": "schedule, timetable", "example": "Mi horario de clases cambia cada semestre.", "exampleEn": "My class schedule changes every semester." },
    { "id": "es-0449", "front": "el precio", "back": "price", "example": "El precio de ese abrigo es muy alto.", "exampleEn": "The price of that coat is very high." },
    { "id": "es-0450", "front": "asustado", "back": "scared / frightened", "example": "El perro estaba asustado por el ruido.", "exampleEn": "The dog was scared by the noise." },
    { "id": "es-0451", "front": "la naranja", "back": "orange", "example": "Me tomo un zumo de naranja cada mañana.", "exampleEn": "I have an orange juice every morning." },
    { "id": "es-0452", "front": "el museo", "back": "museum", "example": "El museo abre a las diez de la mañana.", "exampleEn": "The museum opens at ten in the morning." },
    { "id": "es-0453", "front": "el laboratorio", "back": "laboratory, lab", "example": "Hacemos experimentos en el laboratorio.", "exampleEn": "We do experiments in the laboratory." },
    { "id": "es-0454", "front": "la oferta", "back": "sale / offer", "example": "Hay una gran oferta en la tienda hoy.", "exampleEn": "There is a big sale at the store today." },
    { "id": "es-0455", "front": "el otoño", "back": "autumn / fall", "example": "Las hojas caen en otoño.", "exampleEn": "The leaves fall in autumn." },
    { "id": "es-0456", "front": "la fresa", "back": "strawberry", "example": "Las fresas con nata son un postre clásico.", "exampleEn": "Strawberries with cream are a classic dessert." },
    { "id": "es-0457", "front": "la catedral", "back": "cathedral", "example": "La catedral es el edificio más antiguo.", "exampleEn": "The cathedral is the oldest building." },
    { "id": "es-0458", "front": "la materia", "back": "subject, course", "example": "Mi materia favorita es la biología.", "exampleEn": "My favorite subject is biology." },
    { "id": "es-0459", "front": "la caja", "back": "checkout / cash register", "example": "Hay mucha cola en la caja.", "exampleEn": "There is a long queue at the checkout." },
    { "id": "es-0460", "front": "la primavera", "back": "spring", "example": "Las flores brotan en primavera.", "exampleEn": "Flowers bloom in spring." },
    { "id": "es-0461", "front": "la uva", "back": "grape", "example": "Comemos doce uvas en Nochevieja.", "exampleEn": "We eat twelve grapes on New Year's Eve." },
    { "id": "es-0462", "front": "el monumento", "back": "monument", "example": "Tomamos fotos del monumento histórico.", "exampleEn": "We took photos of the historic monument." },
    { "id": "es-0463", "front": "la computadora", "back": "computer", "example": "Uso la computadora para hacer mis trabajos.", "exampleEn": "I use the computer to do my assignments." },
    { "id": "es-0464", "front": "pagar", "back": "to pay", "example": "¿Puedo pagar con tarjeta?", "exampleEn": "Can I pay by card?" },
    { "id": "es-0465", "front": "la tormenta", "back": "storm", "example": "Anoche hubo una tormenta muy fuerte.", "exampleEn": "There was a very strong storm last night." },
    { "id": "es-0466", "front": "el pastel", "back": "cake / pastry", "example": "Compramos un pastel de cumpleaños.", "exampleEn": "We bought a birthday cake." },
    { "id": "es-0467", "front": "la biblioteca", "back": "library", "example": "La biblioteca cierra a las nueve.", "exampleEn": "The library closes at nine." },
    { "id": "es-0468", "front": "el teléfono inteligente", "back": "smartphone", "example": "Mi teléfono inteligente tiene poca batería.", "exampleEn": "My smartphone has low battery." },
    { "id": "es-0469", "front": "el recibo", "back": "receipt", "example": "Guarda el recibo por si acaso.", "exampleEn": "Keep the receipt just in case." },
    { "id": "es-0470", "front": "el trueno", "back": "thunder", "example": "El trueno me despertó de madrugada.", "exampleEn": "The thunder woke me up in the early hours of the morning." },
    { "id": "es-0471", "front": "el helado", "back": "ice cream", "example": "Me apetece un helado de vainilla.", "exampleEn": "I feel like a vanilla ice cream." },
    { "id": "es-0472", "front": "el ayuntamiento", "back": "city hall / town hall", "example": "El ayuntamiento está frente a la plaza.", "exampleEn": "The town hall is in front of the square." },
    { "id": "es-0473", "front": "la contraseña", "back": "password", "example": "Cambié mi contraseña por seguridad.", "exampleEn": "I changed my password for security." },
    { "id": "es-0474", "front": "devolver", "back": "to return (an item)", "example": "Quiero devolver este vestido; es muy grande.", "exampleEn": "I want to return this dress; it is too big." },
    { "id": "es-0475", "front": "el relámpago", "back": "lightning", "example": "Vi un relámpago cruzar el cielo.", "exampleEn": "I saw a lightning bolt cross the sky." },
    { "id": "es-0476", "front": "el vino", "back": "wine", "example": "Pedimos una botella de vino tinto.", "exampleEn": "We ordered a bottle of red wine." },
    { "id": "es-0477", "front": "la farmacia", "back": "pharmacy", "example": "Hay una farmacia cerca del hotel.", "exampleEn": "There is a pharmacy near the hotel." },
    { "id": "es-0478", "front": "la red", "back": "network, internet", "example": "La red está muy lenta hoy.", "exampleEn": "The network is very slow today." },
    { "id": "es-0479", "front": "el supermercado", "back": "supermarket", "example": "Voy al supermercado a comprar comida.", "exampleEn": "I am going to the supermarket to buy food." },
    { "id": "es-0480", "front": "la niebla", "back": "fog / mist", "example": "Hay mucha niebla en la carretera.", "exampleEn": "There is a lot of fog on the road." },
    { "id": "es-0481", "front": "la cerveza", "back": "beer", "example": "Me pone una cerveza bien fría.", "exampleEn": "Pour me a nice cold beer." },
    { "id": "es-0482", "front": "la comisaría", "back": "police station", "example": "Fui a la comisaría a poner una denuncia.", "exampleEn": "I went to the police station to file a report." },
    { "id": "es-0483", "front": "el correo electrónico", "back": "email", "example": "Te mandé un correo electrónico esta mañana.", "exampleEn": "I sent you an email this morning." },
    { "id": "es-0484", "front": "el centro comercial", "back": "shopping mall", "example": "Pasamos la tarde en el centro comercial.", "exampleEn": "We spent the afternoon at the shopping mall." },
    { "id": "es-0485", "front": "la sombra", "back": "shadow / shade", "example": "Nos sentamos a la sombra del árbol.", "exampleEn": "We sat in the shade of the tree." },
    { "id": "es-0486", "front": "el zumo", "back": "juice", "example": "El zumo de naranja está recién hecho.", "exampleEn": "The orange juice is freshly squeezed." },
    { "id": "es-0487", "front": "el cajero automático", "back": "ATM", "example": "Necesito encontrar un cajero automático.", "exampleEn": "I need to find an ATM." },
    { "id": "es-0488", "front": "el sitio web", "back": "website", "example": "El sitio web de la empresa está caído.", "exampleEn": "The company's website is down." },
    { "id": "es-0489", "front": "limpiar", "back": "to clean", "example": "Limpiamos la casa los sábados.", "exampleEn": "We clean the house on Saturdays." },
    { "id": "es-0490", "front": "la helada", "back": "frost", "example": "Esta mañana hubo helada en el jardín.", "exampleEn": "There was frost in the garden this morning." },
    { "id": "es-0491", "front": "el té", "back": "tea", "example": "Prefiero el té verde sin azúcar.", "exampleEn": "I prefer green tea without sugar." },
    { "id": "es-0492", "front": "la gasolinera", "back": "gas station", "example": "Para en la gasolinera a llenar el depósito.", "exampleEn": "Stop at the gas station to fill the tank." },
    { "id": "es-0493", "front": "la aplicación", "back": "app, application", "example": "Descargué una aplicación para aprender idiomas.", "exampleEn": "I downloaded an app to learn languages." },
    { "id": "es-0494", "front": "ordenar", "back": "to tidy up", "example": "Por favor, ordena tu cuarto antes de salir.", "exampleEn": "Please tidy up your room before going out." },
    { "id": "es-0495", "front": "húmedo", "back": "humid / damp", "example": "El clima es muy húmedo en verano.", "exampleEn": "The climate is very humid in summer." },
    { "id": "es-0496", "front": "cocinar", "back": "to cook", "example": "Me encanta cocinar para mis amigos.", "exampleEn": "I love cooking for my friends." },
    { "id": "es-0497", "front": "el aparcamiento", "back": "parking lot", "example": "No hay aparcamiento libre aquí.", "exampleEn": "There is no free parking here." },
    { "id": "es-0498", "front": "el archivo", "back": "file, document", "example": "Guarda el archivo antes de cerrar.", "exampleEn": "Save the file before closing." },
    { "id": "es-0499", "front": "planchar", "back": "to iron", "example": "Plancho la camisa antes de ponerla.", "exampleEn": "I iron the shirt before putting it on." },
    { "id": "es-0500", "front": "seco", "back": "dry", "example": "El desierto es un lugar muy seco.", "exampleEn": "The desert is a very dry place." }
  ]
};
if (typeof module !== "undefined" && module.exports) module.exports = deck;
if (typeof window !== "undefined") { var WL = (window.WL = window.WL || {}); (WL.__decks = WL.__decks || []).push(deck); }
