// Agora deck. Free.
var deck = {
  "id": "bundled:portuguese",
  "name": "Portuguese 250",
  "lang": "pt",
  "cards": [
    { "id": "pt-0001", "front": "oi", "back": "hi", "example": "Oi, tudo bem?" },
    { "id": "pt-0002", "front": "olá", "back": "hello", "example": "Olá, como você está?" },
    { "id": "pt-0003", "front": "tchau", "back": "bye", "example": "Tchau, até logo!" },
    { "id": "pt-0004", "front": "bom dia", "back": "good morning", "example": "Bom dia, dormiu bem?" },
    { "id": "pt-0005", "front": "boa tarde", "back": "good afternoon", "example": "Boa tarde, posso ajudar?" },
    { "id": "pt-0006", "front": "boa noite", "back": "good evening / good night", "example": "Boa noite, durma bem." },
    { "id": "pt-0007", "front": "por favor", "back": "please", "example": "Um café, por favor." },
    { "id": "pt-0008", "front": "obrigado", "back": "thank you (male speaker)", "example": "Obrigado pela ajuda!" },
    { "id": "pt-0009", "front": "obrigada", "back": "thank you (female speaker)", "example": "Obrigada pelo presente." },
    { "id": "pt-0010", "front": "de nada", "back": "you're welcome", "example": "De nada, foi um prazer." },
    { "id": "pt-0011", "front": "com licença", "back": "excuse me", "example": "Com licença, posso passar?" },
    { "id": "pt-0012", "front": "desculpa", "back": "sorry", "example": "Desculpa pelo atraso." },
    { "id": "pt-0013", "front": "sim", "back": "yes", "example": "Sim, eu concordo." },
    { "id": "pt-0014", "front": "não", "back": "no / not", "example": "Não, obrigado." },
    { "id": "pt-0015", "front": "talvez", "back": "maybe", "example": "Talvez eu vá amanhã." },
    { "id": "pt-0016", "front": "tudo bem", "back": "all good / okay", "example": "Tudo bem, não se preocupe." },
    { "id": "pt-0017", "front": "até logo", "back": "see you later", "example": "Até logo, pessoal!" },
    { "id": "pt-0018", "front": "até amanhã", "back": "see you tomorrow", "example": "Até amanhã na escola." },
    { "id": "pt-0019", "front": "prazer", "back": "nice to meet you", "example": "Prazer em conhecer você." },
    { "id": "pt-0020", "front": "bem-vindo", "back": "welcome", "example": "Bem-vindo ao Brasil!" },
    { "id": "pt-0021", "front": "zero", "back": "zero", "example": "O placar está zero a zero." },
    { "id": "pt-0022", "front": "um", "back": "one", "example": "Eu quero um café." },
    { "id": "pt-0023", "front": "dois", "back": "two", "example": "Tenho dois irmãos." },
    { "id": "pt-0024", "front": "três", "back": "three", "example": "São três horas." },
    { "id": "pt-0025", "front": "quatro", "back": "four", "example": "A mesa tem quatro cadeiras." },
    { "id": "pt-0026", "front": "cinco", "back": "five", "example": "Comprei cinco maçãs." },
    { "id": "pt-0027", "front": "seis", "back": "six", "example": "Acordo às seis da manhã." },
    { "id": "pt-0028", "front": "sete", "back": "seven", "example": "A semana tem sete dias." },
    { "id": "pt-0029", "front": "oito", "back": "eight", "example": "Ela tem oito anos." },
    { "id": "pt-0030", "front": "nove", "back": "nine", "example": "Faltam nove minutos." },
    { "id": "pt-0031", "front": "dez", "back": "ten", "example": "Custou dez reais." },
    { "id": "pt-0032", "front": "onze", "back": "eleven", "example": "O ônibus chega às onze." },
    { "id": "pt-0033", "front": "doze", "back": "twelve", "example": "Comprei doze ovos." },
    { "id": "pt-0034", "front": "treze", "back": "thirteen", "example": "Ele tem treze anos." },
    { "id": "pt-0035", "front": "quatorze", "back": "fourteen", "example": "São quatorze quilômetros." },
    { "id": "pt-0036", "front": "quinze", "back": "fifteen", "example": "Espere quinze minutos." },
    { "id": "pt-0037", "front": "dezesseis", "back": "sixteen", "example": "Ela faz dezesseis anos hoje." },
    { "id": "pt-0038", "front": "dezessete", "back": "seventeen", "example": "Tem dezessete pessoas aqui." },
    { "id": "pt-0039", "front": "dezoito", "back": "eighteen", "example": "Aos dezoito anos ele votou." },
    { "id": "pt-0040", "front": "dezenove", "back": "nineteen", "example": "O quarto fica no andar dezenove." },
    { "id": "pt-0041", "front": "vinte", "back": "twenty", "example": "Tenho vinte reais na carteira." },
    { "id": "pt-0042", "front": "trinta", "back": "thirty", "example": "A aula dura trinta minutos." },
    { "id": "pt-0043", "front": "quarenta", "back": "forty", "example": "Ele tem quarenta anos." },
    { "id": "pt-0044", "front": "cinquenta", "back": "fifty", "example": "O ingresso custa cinquenta reais." },
    { "id": "pt-0045", "front": "sessenta", "back": "sixty", "example": "Uma hora tem sessenta minutos." },
    { "id": "pt-0046", "front": "setenta", "back": "seventy", "example": "A vovó tem setenta anos." },
    { "id": "pt-0047", "front": "oitenta", "back": "eighty", "example": "O carro ia a oitenta por hora." },
    { "id": "pt-0048", "front": "noventa", "back": "ninety", "example": "Faltam noventa dias para as férias." },
    { "id": "pt-0049", "front": "cem", "back": "one hundred", "example": "Ganhei cem reais." },
    { "id": "pt-0050", "front": "mil", "back": "one thousand", "example": "A passagem custa mil reais." },
    { "id": "pt-0051", "front": "segunda-feira", "back": "Monday", "example": "Trabalho na segunda-feira." },
    { "id": "pt-0052", "front": "terça-feira", "back": "Tuesday", "example": "Tenho aula na terça-feira." },
    { "id": "pt-0053", "front": "quarta-feira", "back": "Wednesday", "example": "Vamos sair na quarta-feira." },
    { "id": "pt-0054", "front": "quinta-feira", "back": "Thursday", "example": "A reunião é na quinta-feira." },
    { "id": "pt-0055", "front": "sexta-feira", "back": "Friday", "example": "Adoro a sexta-feira." },
    { "id": "pt-0056", "front": "sábado", "back": "Saturday", "example": "No sábado eu descanso." },
    { "id": "pt-0057", "front": "domingo", "back": "Sunday", "example": "Almoçamos juntos no domingo." },
    { "id": "pt-0058", "front": "janeiro", "back": "January", "example": "Meu aniversário é em janeiro." },
    { "id": "pt-0059", "front": "fevereiro", "back": "February", "example": "O Carnaval é em fevereiro." },
    { "id": "pt-0060", "front": "março", "back": "March", "example": "As aulas começam em março." },
    { "id": "pt-0061", "front": "abril", "back": "April", "example": "Chove muito em abril." },
    { "id": "pt-0062", "front": "maio", "back": "May", "example": "Viajamos em maio." },
    { "id": "pt-0063", "front": "junho", "back": "June", "example": "A festa junina é em junho." },
    { "id": "pt-0064", "front": "julho", "back": "July", "example": "Faz frio em julho aqui." },
    { "id": "pt-0065", "front": "agosto", "back": "August", "example": "As férias terminam em agosto." },
    { "id": "pt-0066", "front": "setembro", "back": "September", "example": "A primavera começa em setembro." },
    { "id": "pt-0067", "front": "outubro", "back": "October", "example": "O evento é em outubro." },
    { "id": "pt-0068", "front": "novembro", "back": "November", "example": "Visito a família em novembro." },
    { "id": "pt-0069", "front": "dezembro", "back": "December", "example": "O Natal é em dezembro." },
    { "id": "pt-0070", "front": "hoje", "back": "today", "example": "Hoje está muito quente." },
    { "id": "pt-0071", "front": "amanhã", "back": "tomorrow", "example": "Amanhã eu viajo." },
    { "id": "pt-0072", "front": "ontem", "back": "yesterday", "example": "Ontem eu fui ao cinema." },
    { "id": "pt-0073", "front": "agora", "back": "now", "example": "Preciso sair agora." },
    { "id": "pt-0074", "front": "depois", "back": "later / after", "example": "A gente conversa depois." },
    { "id": "pt-0075", "front": "antes", "back": "before", "example": "Cheguei antes de você." },
    { "id": "pt-0076", "front": "sempre", "back": "always", "example": "Eu sempre tomo café." },
    { "id": "pt-0077", "front": "nunca", "back": "never", "example": "Nunca fui ao Japão." },
    { "id": "pt-0078", "front": "às vezes", "back": "sometimes", "example": "Às vezes eu corro de manhã." },
    { "id": "pt-0079", "front": "cedo", "back": "early", "example": "Acordei muito cedo hoje." },
    { "id": "pt-0080", "front": "tarde", "back": "late", "example": "Ele chegou tarde na festa." },
    { "id": "pt-0081", "front": "a hora", "back": "the hour / time", "example": "Que horas são agora?" },
    { "id": "pt-0082", "front": "o dia", "back": "the day", "example": "Tenha um bom dia!" },
    { "id": "pt-0083", "front": "a semana", "back": "the week", "example": "A semana passou rápido." },
    { "id": "pt-0084", "front": "o mês", "back": "the month", "example": "Esse mês foi difícil." },
    { "id": "pt-0085", "front": "o ano", "back": "the year", "example": "Feliz ano novo!" },
    { "id": "pt-0086", "front": "o minuto", "back": "the minute", "example": "Espere um minuto, por favor." },
    { "id": "pt-0087", "front": "a manhã", "back": "the morning", "example": "Estudo de manhã." },
    { "id": "pt-0088", "front": "a noite", "back": "the night", "example": "A noite está fria." },
    { "id": "pt-0089", "front": "quem", "back": "who", "example": "Quem é aquele homem?" },
    { "id": "pt-0090", "front": "o que", "back": "what", "example": "O que você quer comer?" },
    { "id": "pt-0091", "front": "onde", "back": "where", "example": "Onde fica o banheiro?" },
    { "id": "pt-0092", "front": "quando", "back": "when", "example": "Quando você chega?" },
    { "id": "pt-0093", "front": "por que", "back": "why", "example": "Por que você está triste?" },
    { "id": "pt-0094", "front": "como", "back": "how", "example": "Como você está?" },
    { "id": "pt-0095", "front": "quanto", "back": "how much", "example": "Quanto custa isso?" },
    { "id": "pt-0096", "front": "qual", "back": "which", "example": "Qual é o seu nome?" },
    { "id": "pt-0097", "front": "eu", "back": "I", "example": "Eu gosto de música." },
    { "id": "pt-0098", "front": "você", "back": "you", "example": "Você fala inglês?" },
    { "id": "pt-0099", "front": "ele", "back": "he", "example": "Ele é meu amigo." },
    { "id": "pt-0100", "front": "ela", "back": "she", "example": "Ela trabalha no banco." },
    { "id": "pt-0101", "front": "nós", "back": "we", "example": "Nós vamos à praia." },
    { "id": "pt-0102", "front": "eles", "back": "they (masc.)", "example": "Eles jogam futebol." },
    { "id": "pt-0103", "front": "elas", "back": "they (fem.)", "example": "Elas estudam juntas." },
    { "id": "pt-0104", "front": "meu", "back": "my (masc.)", "example": "Esse é o meu carro." },
    { "id": "pt-0105", "front": "minha", "back": "my (fem.)", "example": "Essa é a minha casa." },
    { "id": "pt-0106", "front": "seu", "back": "your (masc.)", "example": "Qual é o seu nome?" },
    { "id": "pt-0107", "front": "isso", "back": "this / that", "example": "Isso é muito bom." },
    { "id": "pt-0108", "front": "este", "back": "this (masc.)", "example": "Este livro é meu." },
    { "id": "pt-0109", "front": "aquele", "back": "that (over there)", "example": "Aquele prédio é alto." },
    { "id": "pt-0110", "front": "ser", "back": "to be (permanent)", "example": "Eu sou brasileiro." },
    { "id": "pt-0111", "front": "estar", "back": "to be (temporary)", "example": "Eu estou cansado hoje." },
    { "id": "pt-0112", "front": "ter", "back": "to have", "example": "Eu tenho dois gatos." },
    { "id": "pt-0113", "front": "fazer", "back": "to do / to make", "example": "O que você vai fazer?" },
    { "id": "pt-0114", "front": "ir", "back": "to go", "example": "Eu vou ao mercado." },
    { "id": "pt-0115", "front": "vir", "back": "to come", "example": "Você vem à festa?" },
    { "id": "pt-0116", "front": "querer", "back": "to want", "example": "Eu quero um suco." },
    { "id": "pt-0117", "front": "poder", "back": "can / to be able to", "example": "Você pode me ajudar?" },
    { "id": "pt-0118", "front": "saber", "back": "to know (facts)", "example": "Eu não sei a resposta." },
    { "id": "pt-0119", "front": "conhecer", "back": "to know (people/places)", "example": "Quero conhecer o Rio." },
    { "id": "pt-0120", "front": "ver", "back": "to see", "example": "Eu vejo um pássaro." },
    { "id": "pt-0121", "front": "ouvir", "back": "to hear / to listen", "example": "Eu gosto de ouvir música." },
    { "id": "pt-0122", "front": "falar", "back": "to speak / to talk", "example": "Eu falo português." },
    { "id": "pt-0123", "front": "dizer", "back": "to say / to tell", "example": "O que você quer dizer?" },
    { "id": "pt-0124", "front": "comer", "back": "to eat", "example": "Eu gosto de comer pizza." },
    { "id": "pt-0125", "front": "beber", "back": "to drink", "example": "Eu vou beber água." },
    { "id": "pt-0126", "front": "dormir", "back": "to sleep", "example": "Eu durmo oito horas." },
    { "id": "pt-0127", "front": "acordar", "back": "to wake up", "example": "Eu acordo às sete." },
    { "id": "pt-0128", "front": "trabalhar", "back": "to work", "example": "Eu trabalho de casa." },
    { "id": "pt-0129", "front": "estudar", "back": "to study", "example": "Eu estudo português." },
    { "id": "pt-0130", "front": "gostar", "back": "to like", "example": "Eu gosto de você." },
    { "id": "pt-0131", "front": "precisar", "back": "to need", "example": "Eu preciso de ajuda." },
    { "id": "pt-0132", "front": "comprar", "back": "to buy", "example": "Eu vou comprar pão." },
    { "id": "pt-0133", "front": "pagar", "back": "to pay", "example": "Eu vou pagar a conta." },
    { "id": "pt-0134", "front": "andar", "back": "to walk", "example": "Gosto de andar no parque." },
    { "id": "pt-0135", "front": "morar", "back": "to live (reside)", "example": "Eu moro em São Paulo." },
    { "id": "pt-0136", "front": "escrever", "back": "to write", "example": "Eu vou escrever uma carta." },
    { "id": "pt-0137", "front": "ler", "back": "to read", "example": "Eu gosto de ler livros." },
    { "id": "pt-0138", "front": "abrir", "back": "to open", "example": "Pode abrir a janela?" },
    { "id": "pt-0139", "front": "fechar", "back": "to close", "example": "Feche a porta, por favor." },
    { "id": "pt-0140", "front": "ajudar", "back": "to help", "example": "Posso ajudar você?" },
    { "id": "pt-0141", "front": "a água", "back": "the water", "example": "Eu bebo muita água." },
    { "id": "pt-0142", "front": "o café", "back": "the coffee", "example": "O café está quente." },
    { "id": "pt-0143", "front": "o pão", "back": "the bread", "example": "Comprei pão fresco." },
    { "id": "pt-0144", "front": "o leite", "back": "the milk", "example": "O leite está na geladeira." },
    { "id": "pt-0145", "front": "o arroz", "back": "the rice", "example": "Gosto de arroz com feijão." },
    { "id": "pt-0146", "front": "a carne", "back": "the meat", "example": "A carne está saborosa." },
    { "id": "pt-0147", "front": "a fruta", "back": "the fruit", "example": "Eu como fruta toda manhã." },
    { "id": "pt-0148", "front": "o ovo", "back": "the egg", "example": "Comi um ovo no café." },
    { "id": "pt-0149", "front": "o suco", "back": "the juice", "example": "Quero um suco de laranja." },
    { "id": "pt-0150", "front": "a comida", "back": "the food", "example": "A comida está deliciosa." },
    { "id": "pt-0151", "front": "o açúcar", "back": "the sugar", "example": "Não uso açúcar no café." },
    { "id": "pt-0152", "front": "o sal", "back": "the salt", "example": "Falta um pouco de sal." },
    { "id": "pt-0153", "front": "a família", "back": "the family", "example": "Amo a minha família." },
    { "id": "pt-0154", "front": "a mãe", "back": "the mother", "example": "Minha mãe cozinha bem." },
    { "id": "pt-0155", "front": "o pai", "back": "the father", "example": "Meu pai trabalha muito." },
    { "id": "pt-0156", "front": "o filho", "back": "the son", "example": "O filho deles é alto." },
    { "id": "pt-0157", "front": "a filha", "back": "the daughter", "example": "A filha dela tem cinco anos." },
    { "id": "pt-0158", "front": "o irmão", "back": "the brother", "example": "Meu irmão mora longe." },
    { "id": "pt-0159", "front": "a irmã", "back": "the sister", "example": "Minha irmã é médica." },
    { "id": "pt-0160", "front": "o amigo", "back": "the friend (male)", "example": "Ele é meu melhor amigo." },
    { "id": "pt-0161", "front": "a amiga", "back": "the friend (female)", "example": "Ela é minha amiga de escola." },
    { "id": "pt-0162", "front": "o homem", "back": "the man", "example": "O homem está esperando." },
    { "id": "pt-0163", "front": "a mulher", "back": "the woman", "example": "A mulher é professora." },
    { "id": "pt-0164", "front": "a criança", "back": "the child", "example": "A criança está brincando." },
    { "id": "pt-0165", "front": "a casa", "back": "the house / home", "example": "Vou para casa agora." },
    { "id": "pt-0166", "front": "a porta", "back": "the door", "example": "Feche a porta, por favor." },
    { "id": "pt-0167", "front": "a janela", "back": "the window", "example": "Abra a janela." },
    { "id": "pt-0168", "front": "a mesa", "back": "the table", "example": "A comida está na mesa." },
    { "id": "pt-0169", "front": "a cadeira", "back": "the chair", "example": "Sente-se na cadeira." },
    { "id": "pt-0170", "front": "a cama", "back": "the bed", "example": "A cama é confortável." },
    { "id": "pt-0171", "front": "o banheiro", "back": "the bathroom", "example": "Onde fica o banheiro?" },
    { "id": "pt-0172", "front": "a cozinha", "back": "the kitchen", "example": "Ela está na cozinha." },
    { "id": "pt-0173", "front": "o quarto", "back": "the bedroom", "example": "Meu quarto é pequeno." },
    { "id": "pt-0174", "front": "a chave", "back": "the key", "example": "Perdi a chave de casa." },
    { "id": "pt-0175", "front": "a cabeça", "back": "the head", "example": "Minha cabeça dói." },
    { "id": "pt-0176", "front": "a mão", "back": "the hand", "example": "Lave a mão antes de comer." },
    { "id": "pt-0177", "front": "o olho", "back": "the eye", "example": "Ela tem olho castanho." },
    { "id": "pt-0178", "front": "o pé", "back": "the foot", "example": "Meu pé está doendo." },
    { "id": "pt-0179", "front": "a boca", "back": "the mouth", "example": "Abra a boca, por favor." },
    { "id": "pt-0180", "front": "o braço", "back": "the arm", "example": "Ele quebrou o braço." },
    { "id": "pt-0181", "front": "o coração", "back": "the heart", "example": "Meu coração bate forte." },
    { "id": "pt-0182", "front": "a cidade", "back": "the city", "example": "Esta cidade é grande." },
    { "id": "pt-0183", "front": "a rua", "back": "the street", "example": "A rua está movimentada." },
    { "id": "pt-0184", "front": "a loja", "back": "the store", "example": "A loja abre às nove." },
    { "id": "pt-0185", "front": "o mercado", "back": "the market", "example": "Vou ao mercado comprar frutas." },
    { "id": "pt-0186", "front": "a escola", "back": "the school", "example": "As crianças vão à escola." },
    { "id": "pt-0187", "front": "o trabalho", "back": "the work / job", "example": "Gosto do meu trabalho." },
    { "id": "pt-0188", "front": "o hospital", "back": "the hospital", "example": "Ela está no hospital." },
    { "id": "pt-0189", "front": "o restaurante", "back": "the restaurant", "example": "O restaurante é ótimo." },
    { "id": "pt-0190", "front": "o banco", "back": "the bank", "example": "Preciso ir ao banco." },
    { "id": "pt-0191", "front": "a praia", "back": "the beach", "example": "Adoro ir à praia." },
    { "id": "pt-0192", "front": "o parque", "back": "the park", "example": "As crianças brincam no parque." },
    { "id": "pt-0193", "front": "o dinheiro", "back": "the money", "example": "Não tenho dinheiro hoje." },
    { "id": "pt-0194", "front": "o telefone", "back": "the telephone", "example": "O telefone está tocando." },
    { "id": "pt-0195", "front": "o celular", "back": "the cell phone", "example": "Meu celular descarregou." },
    { "id": "pt-0196", "front": "o computador", "back": "the computer", "example": "Trabalho no computador." },
    { "id": "pt-0197", "front": "o livro", "back": "the book", "example": "Este livro é interessante." },
    { "id": "pt-0198", "front": "o carro", "back": "the car", "example": "Meu carro é vermelho." },
    { "id": "pt-0199", "front": "o ônibus", "back": "the bus", "example": "Vou pegar o ônibus." },
    { "id": "pt-0200", "front": "o trem", "back": "the train", "example": "O trem está atrasado." },
    { "id": "pt-0201", "front": "o avião", "back": "the airplane", "example": "O avião vai decolar." },
    { "id": "pt-0202", "front": "a bicicleta", "back": "the bicycle", "example": "Ando de bicicleta no parque." },
    { "id": "pt-0203", "front": "a árvore", "back": "the tree", "example": "A árvore é muito alta." },
    { "id": "pt-0204", "front": "a flor", "back": "the flower", "example": "Ela me deu uma flor." },
    { "id": "pt-0205", "front": "o sol", "back": "the sun", "example": "O sol está forte hoje." },
    { "id": "pt-0206", "front": "a lua", "back": "the moon", "example": "A lua está linda esta noite." },
    { "id": "pt-0207", "front": "o céu", "back": "the sky", "example": "O céu está azul." },
    { "id": "pt-0208", "front": "o mar", "back": "the sea", "example": "O mar está calmo." },
    { "id": "pt-0209", "front": "o cachorro", "back": "the dog", "example": "Meu cachorro é muito amigável." },
    { "id": "pt-0210", "front": "o gato", "back": "the cat", "example": "O gato está dormindo." },
    { "id": "pt-0211", "front": "o pássaro", "back": "the bird", "example": "O pássaro está cantando." },
    { "id": "pt-0212", "front": "a chuva", "back": "the rain", "example": "A chuva começou cedo." },
    { "id": "pt-0213", "front": "o vento", "back": "the wind", "example": "O vento está forte." },
    { "id": "pt-0214", "front": "o frio", "back": "the cold", "example": "Estou com frio." },
    { "id": "pt-0215", "front": "o calor", "back": "the heat", "example": "Está fazendo muito calor." },
    { "id": "pt-0216", "front": "o tempo", "back": "the weather / time", "example": "Como está o tempo hoje?" },
    { "id": "pt-0217", "front": "grande", "back": "big / large", "example": "A casa é muito grande." },
    { "id": "pt-0218", "front": "pequeno", "back": "small", "example": "O gato é pequeno." },
    { "id": "pt-0219", "front": "bom", "back": "good", "example": "Este filme é bom." },
    { "id": "pt-0220", "front": "ruim", "back": "bad", "example": "O dia foi ruim." },
    { "id": "pt-0221", "front": "bonito", "back": "beautiful / handsome", "example": "Que dia bonito!" },
    { "id": "pt-0222", "front": "feio", "back": "ugly", "example": "O prédio é feio." },
    { "id": "pt-0223", "front": "novo", "back": "new", "example": "Comprei um carro novo." },
    { "id": "pt-0224", "front": "velho", "back": "old", "example": "Este livro é muito velho." },
    { "id": "pt-0225", "front": "quente", "back": "hot", "example": "O café está quente." },
    { "id": "pt-0226", "front": "feliz", "back": "happy", "example": "Estou muito feliz hoje." },
    { "id": "pt-0227", "front": "triste", "back": "sad", "example": "Ela ficou triste com a notícia." },
    { "id": "pt-0228", "front": "fácil", "back": "easy", "example": "A prova foi fácil." },
    { "id": "pt-0229", "front": "difícil", "back": "difficult", "example": "O exercício é difícil." },
    { "id": "pt-0230", "front": "caro", "back": "expensive", "example": "Este restaurante é caro." },
    { "id": "pt-0231", "front": "barato", "back": "cheap", "example": "Achei um celular barato." },
    { "id": "pt-0232", "front": "rápido", "back": "fast / quick", "example": "O trem é muito rápido." },
    { "id": "pt-0233", "front": "branco", "back": "white", "example": "Ela usa um vestido branco." },
    { "id": "pt-0234", "front": "preto", "back": "black", "example": "Meu gato é preto." },
    { "id": "pt-0235", "front": "vermelho", "back": "red", "example": "O carro é vermelho." },
    { "id": "pt-0236", "front": "azul", "back": "blue", "example": "O céu está azul." },
    { "id": "pt-0237", "front": "verde", "back": "green", "example": "A folha é verde." },
    { "id": "pt-0238", "front": "amarelo", "back": "yellow", "example": "O sol é amarelo." },
    { "id": "pt-0239", "front": "a cor", "back": "the color", "example": "Qual é a sua cor favorita?" },
    { "id": "pt-0240", "front": "aqui", "back": "here", "example": "Venha aqui, por favor." },
    { "id": "pt-0241", "front": "ali", "back": "there", "example": "O carro está ali." },
    { "id": "pt-0242", "front": "perto", "back": "near / close", "example": "A loja fica perto daqui." },
    { "id": "pt-0243", "front": "longe", "back": "far", "example": "A praia fica longe." },
    { "id": "pt-0244", "front": "à direita", "back": "to the right", "example": "Vire à direita na esquina." },
    { "id": "pt-0245", "front": "à esquerda", "back": "to the left", "example": "A padaria fica à esquerda." },
    { "id": "pt-0246", "front": "em cima", "back": "on top / above", "example": "O livro está em cima da mesa." },
    { "id": "pt-0247", "front": "embaixo", "back": "under / below", "example": "O gato está embaixo da cama." },
    { "id": "pt-0248", "front": "muito", "back": "very / a lot", "example": "Eu gosto muito de você." },
    { "id": "pt-0249", "front": "pouco", "back": "little / few", "example": "Falo um pouco de português." },
    { "id": "pt-0250", "front": "também", "back": "also / too", "example": "Eu também quero ir." }
  ]
};
if (typeof module !== "undefined" && module.exports) module.exports = deck;
