var WL = (typeof window !== "undefined") ? (window.WL = window.WL || {}) : {};
WL.__bundledDeck = {
  "id": "bundled:spanish-starter",
  "name": "Spanish Starter 40",
  "lang": "es",
  "cards": [
    { "id": "es-0001", "front": "hola", "back": "hello", "example": "Hola, ¿cómo estás?" },
    { "id": "es-0002", "front": "adiós", "back": "goodbye", "example": "Adiós, hasta mañana." },
    { "id": "es-0003", "front": "gracias", "back": "thank you", "example": "Muchas gracias por tu ayuda." },
    { "id": "es-0004", "front": "por favor", "back": "please", "example": "Una mesa para dos, por favor." },
    { "id": "es-0005", "front": "sí", "back": "yes", "example": "Sí, quiero un café." },
    { "id": "es-0006", "front": "no", "back": "no", "example": "No, gracias, estoy bien." },
    { "id": "es-0007", "front": "buenos días", "back": "good morning", "example": "Buenos días, ¿qué tal?" },
    { "id": "es-0008", "front": "buenas noches", "back": "good night", "example": "Buenas noches, que descanses." },
    { "id": "es-0009", "front": "el agua", "back": "the water", "example": "Quiero un vaso de agua, por favor." },
    { "id": "es-0010", "front": "el café", "back": "the coffee", "example": "Me gusta el café por la mañana." },
    { "id": "es-0011", "front": "la casa", "back": "the house", "example": "Mi casa está cerca del parque." },
    { "id": "es-0012", "front": "el perro", "back": "the dog", "example": "El perro corre en el parque." },
    { "id": "es-0013", "front": "el gato", "back": "the cat", "example": "El gato duerme en el sofá." },
    { "id": "es-0014", "front": "la comida", "back": "the food (meal)", "example": "La comida está muy rica." },
    { "id": "es-0015", "front": "el amigo", "back": "the friend (male)", "example": "Mi amigo vive en Madrid." },
    { "id": "es-0016", "front": "la familia", "back": "the family", "example": "Mi familia es muy grande." },
    { "id": "es-0017", "front": "el día", "back": "the day", "example": "Hoy es un buen día." },
    { "id": "es-0018", "front": "la noche", "back": "the night", "example": "Trabajo durante la noche." },
    { "id": "es-0019", "front": "el tiempo", "back": "the time / the weather", "example": "No tengo tiempo ahora." },
    { "id": "es-0020", "front": "la calle", "back": "the street", "example": "La tienda está en esta calle." },
    { "id": "es-0021", "front": "ser", "back": "to be (permanent)", "example": "Quiero ser médico." },
    { "id": "es-0022", "front": "estar", "back": "to be (state/location)", "example": "Estoy en la oficina." },
    { "id": "es-0023", "front": "tener", "back": "to have", "example": "Tengo dos hermanos." },
    { "id": "es-0024", "front": "hacer", "back": "to do / to make", "example": "¿Qué quieres hacer hoy?" },
    { "id": "es-0025", "front": "ir", "back": "to go", "example": "Voy a la escuela cada día." },
    { "id": "es-0026", "front": "comer", "back": "to eat", "example": "Me gusta comer fruta." },
    { "id": "es-0027", "front": "beber", "back": "to drink", "example": "Quiero beber un poco de agua." },
    { "id": "es-0028", "front": "hablar", "back": "to speak / to talk", "example": "Quiero hablar español bien." },
    { "id": "es-0029", "front": "querer", "back": "to want / to love", "example": "Quiero aprender más palabras." },
    { "id": "es-0030", "front": "poder", "back": "to be able to / can", "example": "¿Puedes ayudarme, por favor?" },
    { "id": "es-0031", "front": "grande", "back": "big / large", "example": "Esta ciudad es muy grande." },
    { "id": "es-0032", "front": "pequeño", "back": "small", "example": "Tengo un perro pequeño." },
    { "id": "es-0033", "front": "bueno", "back": "good", "example": "Este libro es muy bueno." },
    { "id": "es-0034", "front": "malo", "back": "bad", "example": "Hoy hace mal tiempo." },
    { "id": "es-0035", "front": "uno", "back": "one", "example": "Solo quiero uno, gracias." },
    { "id": "es-0036", "front": "dos", "back": "two", "example": "Tengo dos gatos en casa." },
    { "id": "es-0037", "front": "tres", "back": "three", "example": "Son las tres de la tarde." },
    { "id": "es-0038", "front": "hoy", "back": "today", "example": "Hoy voy al mercado." },
    { "id": "es-0039", "front": "mañana", "back": "tomorrow / morning", "example": "Mañana empieza mi trabajo nuevo." },
    { "id": "es-0040", "front": "¿dónde?", "back": "where?", "example": "¿Dónde está el baño?" }
  ]
};
if (typeof module !== "undefined" && module.exports) module.exports = WL.__bundledDeck;
